### ISSUE TITLE
Arrangement: the new test test_sgm fails a lot

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2171] opened 2017-06-13 07:58 UTC
The PR #2061 introduced a new test `Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_sgm.cpp`. Its compilation fails with older gcc versions:

```
CGAL-4.11-I-32/Arrangement_on_surface_2/TestReport_gimeno_CentOS6.gz:   ERROR:    compilation of test_sgm
CGAL-4.11-I-32/Arrangement_on_surface_2/TestReport_lrineau_CentOS5.gz:   ERROR:    compilation of test_sgm
CGAL-4.11-I-32/Arrangement_on_surface_2/TestReport_lrineau_CentOS6-32.gz:   ERROR:    compilation of test_sgm
CGAL-4.11-I-32/Arrangement_on_surface_2/TestReport_lrineau_CentOS6-CXX11-Boost157.gz:   ERROR:    compilation of test_sgm
```

https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-I-32.shtml#Arrangement_on_surface_2

(Well, more generally, the Arr_2 test results are even worst than KDS...)

**Comment by efifogel** [comment] 2017-06-13 15:33
The problems lies in the call to CGAL::convex_hull:

Point_3 points[] = {
    Point_3(1.0, 0.0, 0.0),
    Point_3(0.0, 1.0, 0.0),
    Point_3(0.0, 0.0, 1.0),
    Point_3(0.0, 0.0, 0.0)
  };
Gm_polyhedron P1;
CGAL::convex_hull_3(points, &points[4], P1);




   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment] 2017-06-13 17:19
Anyway, I've replaced the calls to convex_hull() with make_tetrahedron().
Hopefully, this will make this test compile on those platforms, but the
real problem is convex_hull()...
I've committed and pushed to mine.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment] 2017-06-13 17:43
I will look into this tomorrow.

**Comment by mglisse** [comment] 2017-06-16 12:55
The test also assumes that `Epeck::FT` is `Lazy_exact_nt<Gmpq>` in the last few lines. `3*sw!=1` should work in more cases.

**Comment by efifogel** [comment] 2017-06-18 19:55
Thanks.
I've fixed this as well.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment] 2017-06-18 19:55
I've pushed it all to mine.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment] 2017-06-19 13:58
Efi, I can see [what you have pushed][*]. Do you plan to create a pull-request based on that branch you pushed?

  [*]: https://github.com/CGAL/cgal/compare/master...efifogel:Sgm-bug_fix-efif?expand=1

**Comment by efifogel** [comment] 2017-06-19 19:25
Just did.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Closed** 2017-06-28 07:59 UTC
Labels: bug, Pkg::Arrangement_on_surface_2

**Comment by efifogel** [comment] 2017-07-29 10:15
I think this hasn't been fixed yet.
If so, it's a show stopper!

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment] 2017-07-31 07:21
What do you mean? You branch was merged on June 28th.

**Comment by efifogel** [comment] 2017-07-31 07:46
The additional test case that I've introduced to test the fix in this
branch revealed a problem with convex_hull_3(), which has nothing to do
with this fix (or this branch). Since then I've  simplified the code of the
test so that it doesn't use convex_hull_3() at all.

The problem is that, at least in release mode, convex_hull_3() sometimes
produces a polyhedron with the opposite orientation of facets. I've
conveyed this information to Andreas.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment] 2017-07-31 07:57
I can reproduce the issue and I've created #2320
