### ISSUE TITLE
inconsistent shortest path with CGAL/Surface_mesh_shortest_path

### ISSUE THREAD

**Issue by benno90** [CGAL/cgal#3993] opened 2019-06-08 19:20 UTC
I've done some testing with the [CGAL shortest path algorithm](https://doc.cgal.org/latest/Surface_mesh_shortest_path/index.html#Chapter_Surface_mesh_shortest_path) and I've come across an inconsistent result. The minimal code producing the wrong path can be downloaded [here](https://www.dropbox.com/s/k914a3vefvafr7o/cgal_discrete_geodesics_minimal_example2.tar.gz?dl=0). The archive contains a simple mesh in OFF format and a main.cpp (compilation via `g++ -frounding-math main.cpp -lCGAL -lgmp`). The minimal program requires the indices of the source and target point as arguments, the error is triggered with the arguments 4 and 11. The archive furthermore contains an image showing the mesh with the inconsistent path for the mentioned indices.

**Comment by benno90** [comment] 2019-06-12 06:10
Some more images. The algorithm seems to get stuck once it hits a boundary edge.
[surface_shortestpath_bug_images.tar.gz](https://github.com/CGAL/cgal/files/3279800/surface_shortestpath_bug_images.tar.gz)

**Comment by sloriot** [comment] 2019-06-13 12:42
I  confirm I can reproduce the issue with `./main 34 40` for example.

**Comment by sloriot** [comment] 2019-06-13 13:02
@Hippocrates if you have any advice to where to look at, it would be welcome. I already fixed in #3977 some wrong initializations.
@benno90 I won't be able to look at this before at least two weeks.

**Comment by benno90** [comment] 2019-06-22 06:58
No problem, looking forward to using the shortest path algorithm

**Comment by benno90** [comment] 2019-08-08 16:17
any progress on the problem?

**Comment by afabri** [comment] 2019-08-14 09:38
I reduced the data set:

![image](https://user-images.githubusercontent.com/3263539/63011109-eeeeca80-be87-11e9-900e-6800aa9c8f4b.png)

**Comment by benno90** [comment] 2019-09-11 08:13
I've noticed that the algorithm seems to work just fine for surface meshes with no
flat sections, i.e. surfaces with curvature everywhere.

I'm using it to compute distances form a few source points to all other surface mesh vertices.
I did this according to example 3.2 in the [documentation](https://doc.cgal.org/latest/Surface_mesh_shortest_path/index.html#Chapter_Surface_mesh_shortest_path).
Unfortunately this requires the reconstruction of the sequence tree for each source point.

Now I tried to specify all source points at the beginning (example 3.4) but then a shortest distance query only computes the distance to the nearest source point, is there a possibility to obtain the distances to all source points this way?

**Comment by MaelRL** [comment] 2019-10-03 13:19
There is no way but to construct multiple instances of the class `Surface_mesh_shortest_paths` with a single source. This is because internally it's a tree structure that extends branches till every vertex has found its closest source (and no more than that).

**Closed** 2019-10-18 12:25 UTC
Labels: Pkg::Surface_mesh_shortest_path, bug

**Comment by MaelRL** [comment] 2019-10-20 17:49
Thank you @benno90 for the bug report. A fix has been integrated and will be available in the bug fix release CGAL version 4.14.2, and in the next release v5.0 (soon).
