### ISSUE TITLE
CGAL error: assertion violation! 

### ISSUE THREAD

**Issue by Pravesh-Jamgade** [CGAL/cgal#3286] opened 2018-08-17 13:40 UTC
## Issue Details
I am building an application which uses cgal. cgal has built successfully.I built it in  debug ,release and relwithdebuginfo . My project upon compilation gives  me assertion of several different type. sometimes it gives in "**interval_nt.h**" or "**assertion_impl.h**" . 
![assertion](https://user-images.githubusercontent.com/27573314/44268257-8528ea00-a24e-11e8-84ea-a4987ef36aca.PNG)

And in file "**bipartite_nary_union_sorted_combined.h**" it gives message 

>CGAL_assertion_msg(!GM0.empty() || !GM1.empty()), 
> 		     "one operand must be full-dimensional"

My project uses several different types o input, as I change them one of the above error message appears.
## Source Code
Here's my code:
![overall](https://user-images.githubusercontent.com/27573314/44268363-e94bae00-a24e-11e8-82fa-287a4134cf00.PNG)

As you can see in the output window, theres already a exception. 

> CGAL::Uncertain_conversion_exception at memory location

At line 166, normally program runs and reads the OFF file. But in the output window,it shows the above message. **Still program continues**. The **exception remain unhandelled**. I think that may cause the application stop later in the execution process .

exception later in the process execution:
![finally](https://user-images.githubusercontent.com/27573314/44268586-8b6b9600-a24f-11e8-91c9-931ad3a06c02.PNG)

I use try-catch around the suspected code:

![caught](https://user-images.githubusercontent.com/27573314/44268630-b5bd5380-a24f-11e8-83b1-bcc8f4cea6b8.PNG)

These gives me:
microsoft c++ exception:int __cdecl main(int,char * __ptr64 * __ptr64 const)`

![err0r](https://user-images.githubusercontent.com/27573314/44268696-e3a29800-a24f-11e8-84c3-ec642e1fa512.PNG)

How should I handle these? is it because of cgal built in both DEBUG,RELEASE mode?
I do personally think, may be error is in my code as I explained earlier may be the reason of these behaviour. please correct me if im wrong. 

## Environment
* Operating system (Windows 64 bits):
* Compiler:  C/C++ Optimizing Compiler Version 19.14.26433  / (Visual studio 2017)
* Release or debug mode: Debug, release, relwithdebuginfo mode
* Specific flags used (if any):/MDd /Zi /Ob0 /Od /RTC1
* CGAL version: 4.13
* Boost version: 1.67.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment] 2018-08-17 14:18
Did you have a look at the restrictions listed [here](https://doc.cgal.org/latest/Minkowski_sum_3/index.html#Minkowski_sum_3Features)?

**Comment by Pravesh-Jamgade** [comment] 2018-08-27 09:42
@sloriot thanks for the link.
I got something new here
![myifc](https://user-images.githubusercontent.com/27573314/44653140-8060f480-aa0b-11e8-94f2-279c292c2263.PNG)

**Comment by osmaoui** [comment] 2020-06-05 10:01
any solution ?

**Comment by sloriot** [comment] 2021-12-08 08:08
Closing this issue as no minimal example was provided and nothing can be done as I can't reproduce.

**Closed by sloriot** 2021-12-08 08:08 UTC
Labels: Pkg::Nef_3
