### ISSUE TITLE
libCGAL_Core.so and libCGAL.so does not link to libmpfr.so

### ISSUE THREAD

**Issue by jasjuang** [CGAL/cgal#2701] opened 2018-01-01 07:48 UTC
I am on Ubuntu 16.04, GCC 5.4, latest CGAL.

## Issue Details

After going through the standard procedure of building CGAL, the below libraries are generated in the libs folder 

```
libCGAL_Core.so     libCGAL_Core.so.13.0.2  libCGAL_ImageIO.so.13      libCGAL.so     libCGAL.so.13.0.2
libCGAL_Core.so.13  libCGAL_ImageIO.so      libCGAL_ImageIO.so.13.0.2  libCGAL.so.13
```

I did `ldd` on each of them and here is the result

```
ldd libCGAL_Core.so
        linux-vdso.so.1 =>  (0x00007ffc9a7e7000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007ff18e335000)
        libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007ff18e10f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff18dd8d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff18da84000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff18d86e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff18d4a4000)
        libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007ff18d2a0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff18d098000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff18ce7b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff18e859000)
```
```
ldd libCGAL_ImageIO.so
        linux-vdso.so.1 =>  (0x00007ffffa783000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa1bb90b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa1bb589000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa1bb280000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa1bb06a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa1baca0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa1bbd5e000)
```
```
ldd libCGAL.so
        linux-vdso.so.1 =>  (0x00007ffc39dc0000)
        libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007f79ca3ff000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f79ca07d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f79c9d74000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f79c9b5e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f79c9794000)
        libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f79c9590000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f79c9388000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f79c916b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f79ca846000)
```

The weird thing is non of the cgal libraries are linked to `libmpfr.so`. I am pretty sure mpfr is required because without doing `sudo apt-get install libmpfr-dev` cgal won't even compile, and there is no `libmpfr.a` in the system so it can't be linked statically.  Can someone let me know why this is happening?

This is a problem because when I use CPack to package cgal into a deb file, I am using `CPACK_DEBIAN_PACKAGE_SHLIBDEPS` to check for dependencies, and since it's `ldd` based it couldn't find `libmpfr`, so when I unpack the deb file in another fresh installed computer it will automatically also download boost and gmp from apt to install but not mpfr. The cgal deb file I made does not "work out of the box" since I had to manually do `sudo apt-get install libmpfr-dev` to make it work on the fresh installed computer.

**Comment by mglisse** [comment] 2018-01-01 17:20
This is not a bug. Most of CGAL's code is in headers. The compiled libraries are quite small and only contain a very small part of CGAL, which does not use MPFR. If you look at existing debian CGAL packages, libcgal13 does not depend on MPFR, while libcgal-dev depends on libmpfr-dev, and that is exactly how it should be.

**Comment by lrineau** [comment] 2018-01-02 17:08
I agree with Marc: in principle the CGAL libraries (but maybe CGAL_Core) do not require the functions from GMP/MPFR.

But any that is strange because CGAL libraries *are* linked with GMP and MPFR, during the compilation. @jasjuang Do you have special linker flags? Could you give more on the compilation? Maybe compilation logs  with the command lines?

**Comment by lrineau** [comment] 2018-01-02 17:28
Good. So let's close this issue.

**Closed by lrineau** 2018-01-02 17:28 UTC
Labels: not a bug

**Comment by jasjuang** [comment] 2018-01-02 18:15
@mglisse @lrineau Just so I understand this, CGAL is linked to mpfr, but since it's not actually used when building the CGAL libraries, so it ends up not being linked (based on the link)? Which means I have to figure out a way to manually add mpfr dependencies in CPack?

On a side note, why are most implementations in header files instead of source files for CGAL. Isn't it a better practice to put implementations in source files?

**Comment by mglisse** [comment] 2018-01-02 18:45
> Just so I understand this, CGAL is linked to mpfr, but since it's not actually used when building the CGAL libraries, so it ends up not being linked (based on the ubuntu wiki)?

Yes.

> Which means I have to figure out a way to manually add mpfr dependencies in CPack?

I am not familiar with CPack, but that sounds right. You may also want to add more dependencies, depending on your goals, like libeigen3-dev: since this is a header-only library, it obviously won't show up in ldd's output...

> On a side note, why are most implementations in header files instead of source files for CGAL. Isn't it a better practice to put implementations in source files?

Depends on the language. For a C++ library using a lot of templates, it would make little sense.

**Comment by jasjuang** [comment] 2018-01-02 18:51
@mglisse thanks a lot for the clarification
