### ISSUE TITLE
Delaunay_triangulation_2<Gt> does not inherit Triangulation_2<Gt>

### ISSUE THREAD

**Issue by HugoDRV** [CGAL/cgal#3040] opened 2018-04-22 01:01 UTC
## Issue Details

The default template parameter Tds for Delaunay_triangulation_2<Gt> is different of the default template parameter Tds for Triangulation_2<Gt>. (Specifically, the former does not specify a Triangulation_face_base_2, which then defaults to a version without a Traits class).

This is annoying if I want to build a triangulation that is Delaunay, and then treat it like a non-Delaunay triangulation, without conserving the Delaunay property. Which is the case.

It can be avoided by directly specifying the Tds, but it looks like a (very small) design flaw. And it's not what's documented, also.

## Source Code

typedef Projection_traits_xy_3<Kernel> Gt;

Delaunay_triangulation_2<Gt> delaunay_tr;
// fill the triangulation
Triangulation_2<Gt> tr(delaunay_tr); // Does not compile, obscure templaty error message where a Traits class is actually void

## Environment

* CGAL version: Installed in April 2018 with ubuntu's apt install

**Comment by MaelRL** [comment] 2018-04-23 09:06
There is indeed an issue between what the doc says and what the code does, but the problem is more that `Triangulation_2` shouldn't use `Triangulation_face_base_2`, which is a remnant class that should have been removed and doesn't bring anything anymore.

It will be fixed in the future in another branch that is working on the triangulation packages.

In the meantime, I don't know what exactly you need to do with your triangulation, but:
- The class `Delaunay_triangulation_2<my_GT_class, my_TDS_class>` does have `Triangulation_2<my_GT_class, my_TDS_class>` so you shouldn't need to re-create an object to manipulate it as a `Triangulation_2`.
- If you really want to do it anyway, you can get the base type of the triangulation via the (undocumented) typedef `Delaunay_triangulation_2<my_GT_class, my_TDS_class>::Triangulation`.

**Closed** 2018-07-26 15:34 UTC
Labels: Has Pull Request, Pkg::Triangulation_2, doc bug
