### ISSUE TITLE
Incremental_neighbor_search cannot be instantiated

### ISSUE THREAD

**Issue by gilleswaeber** [CGAL/cgal#6286] opened 2022-01-29 21:58 UTC
I cannot get Incremental_neighbor_search to work. I also couldn't find any usage examples in the doc or on the web.

## Issue Details

Compilation error
```
In file included from main.cpp:6:
/usr/include/CGAL/Incremental_neighbor_search.h: In instantiation of 'class CGAL::Incremental_neighbor_search<CGAL::Search_traits_2<CGAL::Epick>, CGAL::Manhattan_distance_iso_box_point<CGAL::Search_traits_2<CGAL::Epick> > >':
main.cpp:13:20:   required from here
/usr/include/CGAL/Incremental_neighbor_search.h:46:45: error: invalid use of incomplete type 'CGAL::Incremental_neighbor_search<CGAL::Search_traits_2<CGAL::Epick>, CGAL::Manhattan_distance_iso_box_point<CGAL::Search_traits_2<CGAL::Epick> > >::Tree' {aka 'class CGAL::Kd_tree<CGAL::Search_traits_2<CGAL::Epick>, CGAL::Sliding_midpoint<CGAL::Search_traits_2<CGAL::Epick>, CGAL::Plane_separator<double> >, CGAL::Boolean_tag<false>, CGAL::Boolean_tag<false> >'}
   46 |     typedef typename Tree::Point_d_iterator Point_d_iterator;
```
followed by many more lines

## Source Code

```cpp
#include <iostream>

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Manhattan_distance_iso_box_point.h>
#include <CGAL/Search_traits_2.h>
#include <CGAL/Incremental_neighbor_search.h>

using K = CGAL::Exact_predicates_inexact_constructions_kernel;
using Point = K::Point_2;
using TreeTraits = CGAL::Search_traits_2<K>;
using Distance = CGAL::Manhattan_distance_iso_box_point<TreeTraits>;
using IncrNN = CGAL::Incremental_neighbor_search<TreeTraits, Distance>;
using Tree = IncrNN::Tree;

int main() {
	Tree tree;
	tree.insert({1,1});
	tree.insert({2,2});
	
	Point pQuery(0, 0);
	IncrNN nn(tree, {pQuery, pQuery});
	for (auto it = nn.begin(); it != nn.end(); ++it) {
		std::cout << it->first << " dist: " << it->second << "\n";
	}
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux, Fedora 35
* Compiler: g++ 11.2.1 20211203
* Release or debug mode: release
* Specific flags used (if any): 
* CGAL version: 5.3.1
* Boost version: 1.76
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by mglisse** [comment] 2022-01-31 08:23
If you read the message in details, it says that `Kd_tree` is incomplete. `#include <CGAL/Kd_tree.h` goes past that (to a different error though). Maybe we should add it to `Incremental_neighbor_search.h` since it is the default parameter.
The next error is that CGAL uses `Construct_cartesian_const_iterator_d` on a `Query_item` (just to determine its dimension!), it looks like a bug, but I am not that familiar with the list of concepts in this package. I guess most users query points. It seems to be a regression from when Clément introduced a cache.

**Comment by afabri** [comment] 2022-01-31 08:25
I confirm that the include is missing as I also just got beyond that point and hit the next bug.  I am on it.

**Comment by afabri** [comment] 2022-01-31 08:57
As  Marc wrote the bug is to try to construct a coordinate iterator from an iso rectangle.  We should think about making the function `Kd_tree::dim()` public.

**Comment by afabri** [comment] 2022-01-31 09:51
> For my use case, distance to point would have been sufficient. However, unless I'm missing something, the only GeneralDistance concepts that are in CGAL are the Manhattan_distance_iso_box_point and the Euclidean_distance_sphere_point.

You are right. And it should be a trivial exercise to add this to the package.   And thank you for the bug report.

**Comment by mglisse** [comment] 2022-01-31 09:59
> the only GeneralDistance concepts that are in CGAL are the Manhattan_distance_iso_box_point and the Euclidean_distance_sphere_point.

Actually there are a few more, the concept OrthogonalDistance refines GeneralDistance (that's not visible from the page on GeneralDistance, sorry) so its models Euclidean_distance and Weighted_Minkowski_distance are also fine, but indeed there is no plain Manhattan_distance.

**Comment by lrineau** [comment] 2022-02-09 19:32
Fixed by https://github.com/CGAL/cgal/pull/6287.

**Closed by lrineau** 2022-02-09 19:32 UTC
Labels: bug, Pkg::Spatial_searching, Has Pull Request
