### ISSUE TITLE
Inherit from Polyhedron_3

### ISSUE THREAD

**Issue by palanglois** [CGAL/cgal#4721] opened 2020-05-13 17:43 UTC
## Issue Details

Hi, I need to inherit from the Polyhedron class. I also need to use the Nef_Polyedron class, therefore I choosed the `CGAL::Homogeneous<CGAL::Exact_integer>`  Kernel. 
I tried to follow the information I found to properly inherit (reconnecting graph_traits and property_map), however I fail to compile my very simple program.

Here is the error I get: 

```
error: cannot convert ‘SemPolyhedron’ to ‘std::__iterator_traits<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >, void>::difference_type {aka long int}’ in initialization
       typename iterator_traits<_InputIterator>::difference_type __d = __n;
```

Thank you for your help !

## Source Code

main.cpp: 

```cpp
#include <CGAL/Exact_integer.h>
#include <CGAL/Homogeneous.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Polygon_mesh_processing/triangulate_hole.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
#include <vector>
#include <string>

typedef CGAL::Homogeneous<CGAL::Exact_integer>  Kernel;
typedef CGAL::Polyhedron_3<Kernel>     Polyhedron;
typedef typename Kernel::Point_3 Point;

using namespace std;


// Derived class
class SemPolyhedron : public Polyhedron {
public:
    typedef Polyhedron Base;

    SemPolyhedron(std::string _name);

    std::string getName() const;


private:
    const std::string name;

};

// Attempts to re-connect the concepts
namespace boost {
    template<>
    struct graph_traits<SemPolyhedron>
            : public boost::graph_traits<SemPolyhedron::Base> {
    };
    template<typename T>
    struct property_map<SemPolyhedron, T>
            : public boost::property_map<SemPolyhedron::Base, T> {
    };

    template <class T>
    struct property_map<SemPolyhedron, CGAL::dynamic_vertex_property_t<T> >
            : public property_map<SemPolyhedron::Base, CGAL::dynamic_vertex_property_t<T> >
    {};

    template <class T>
    struct property_map<SemPolyhedron, CGAL::dynamic_halfedge_property_t<T> >
            : public property_map<SemPolyhedron::Base, CGAL::dynamic_halfedge_property_t<T> >
    {};

    template <class T>
    struct property_map<SemPolyhedron, CGAL::dynamic_edge_property_t<T> >
            : public property_map<SemPolyhedron::Base, CGAL::dynamic_edge_property_t<T> >
    {};

}

namespace CGAL {

    template<class Tag>
    struct graph_has_property<SemPolyhedron, Tag>
            : public graph_has_property<SemPolyhedron::Base, Tag> {
    };

    template<typename T>
    typename boost::property_map<SemPolyhedron, CGAL::dynamic_vertex_property_t<T> >::const_type
    get(const CGAL::dynamic_vertex_property_t<T> &tag, SemPolyhedron &dm) {
        return get(tag, static_cast<SemPolyhedron::Base &>(dm));
    }

    template<typename T>
    typename boost::property_map<SemPolyhedron, CGAL::dynamic_halfedge_property_t<T> >::const_type
    get(const CGAL::dynamic_halfedge_property_t<T> &tag, SemPolyhedron &dm) {
        return get(tag, static_cast<SemPolyhedron::Base &>(dm));
    }

    template<typename T>
    typename boost::property_map<SemPolyhedron, CGAL::dynamic_edge_property_t<T> >::const_type
    get(const CGAL::dynamic_edge_property_t<T> &tag, SemPolyhedron &dm) {
        return get(tag, static_cast<SemPolyhedron::Base &>(dm));
    }
}

int main(int argc, char* argv[])
{
    string curName("test");
    vector<Point> pointCopies = {Point(0., 0., 0.), Point(0., 0., 1.), Point(0., 1., 0.)};
    vector<vector<size_t>> curPolygons = {{0, 1, 2}};
    SemPolyhedron mesh(curName);
    // Next line fails to compile
    CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(pointCopies, curPolygons, mesh);
    return 0;
}
```
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Ubuntu 16.04 64 Bts
* Compiler: g++ 5.4
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.0.2
* Boost version: 1.58.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7

**Comment by MaelRL** [comment] 2020-05-13 18:07
This compiles for me using CGAL 5.0.2 and gcc 9 / clang 8.

Could you please post the full error stack?

**Comment by palanglois** [comment] 2020-05-13 18:16
Sure !

```
[ 50%] Building CXX object CMakeFiles/cgal-test.dir/main.cpp.o
In file included from /usr/include/c++/5/bits/stl_algobase.h:66:0,
                 from /usr/include/c++/5/algorithm:61,
                 from /home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/config.h:447,
                 from /home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Exact_integer.h:17,
                 from /home/thefroggy/test/cgal_fail/main.cpp:1:
/usr/include/c++/5/bits/stl_iterator_base_funcs.h: In instantiation of ‘void std::advance(_InputIterator&, _Distance) [with _InputIterator = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; _Distance = SemPolyhedron]’:
/usr/local/include/boost/next_prior.hpp:47:21:   required from ‘static T boost::next_prior_detail::next_impl2<T, Distance, HasPlus>::call(T, Distance) [with T = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; Distance = SemPolyhedron; bool HasPlus = false]’
/usr/local/include/boost/next_prior.hpp:151:62:   required from ‘T boost::next(T, Distance) [with T = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; Distance = SemPolyhedron]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/boost/graph/Euler_operations.h:626:15:   required from ‘typename boost::graph_traits<G>::face_descriptor CGAL::Euler::add_face(const VertexRange&, Graph&) [with Graph = SemPolyhedron; VertexRange = std::vector<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > >, std::allocator<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > > > >; typename boost::graph_traits<G>::face_descriptor = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > >]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h:109:28:   required from ‘void CGAL::Polygon_mesh_processing::internal::Polygon_soup_to_polygon_mesh<PM, PointRange, PolygonRange>::operator()(PM&, bool) [with PM = SemPolyhedron; PointRange = std::vector<CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > >; PolygonRange = std::vector<std::vector<long unsigned int> >]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h:225:14:   required from ‘void CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(const PointRange&, const PolygonRange&, PolygonMesh&) [with PolygonMesh = SemPolyhedron; PointRange = std::vector<CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > >; PolygonRange = std::vector<std::vector<long unsigned int> >]’
/home/thefroggy/test/cgal_fail/main.cpp:92:95:   required from here
/usr/include/c++/5/bits/stl_iterator_base_funcs.h:176:71: error: cannot convert ‘SemPolyhedron’ to ‘std::__iterator_traits<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >, void>::difference_type {aka long int}’ in initialization
       typename iterator_traits<_InputIterator>::difference_type __d = __n;
```

**Comment by palanglois** [comment] 2020-05-13 19:50
For information, I just tried with CGAL 5.0.2 and gcc 9 and I still get the error:

```
Scanning dependencies of target cgal-test
[ 50%] Building CXX object CMakeFiles/cgal-test.dir/main.cpp.o
In file included from /usr/include/c++/9/bits/stl_algobase.h:66,
                 from /usr/include/c++/9/algorithm:61,
                 from /home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/config.h:447,
                 from /home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Exact_integer.h:17,
                 from /home/thefroggy/test/cgal_fail/main.cpp:1:
/usr/include/c++/9/bits/stl_iterator_base_funcs.h: In instantiation of ‘void std::advance(_InputIterator&, _Distance) [with _InputIterator = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; _Distance = SemPolyhedron]’:
/usr/local/include/boost/next_prior.hpp:47:21:   required from ‘static T boost::next_prior_detail::next_impl2<T, Distance, HasPlus>::call(T, Distance) [with T = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; Distance = SemPolyhedron; bool HasPlus = false]’
/usr/local/include/boost/next_prior.hpp:151:62:   required from ‘T boost::next(T, Distance) [with T = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >; Distance = SemPolyhedron]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/boost/graph/Euler_operations.h:626:15:   required from ‘typename boost::graph_traits<G>::face_descriptor CGAL::Euler::add_face(const VertexRange&, Graph&) [with Graph = SemPolyhedron; VertexRange = std::vector<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > >, std::allocator<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_vertex<CGAL::I_Polyhedron_vertex<CGAL::HalfedgeDS_vertex_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > > > >; typename boost::graph_traits<G>::face_descriptor = CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Homogeneous<CGAL::Gmpz> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Homogeneous<CGAL::Gmpz> > > > > > >]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h:109:28:   required from ‘void CGAL::Polygon_mesh_processing::internal::Polygon_soup_to_polygon_mesh<PM, PointRange, PolygonRange>::operator()(PM&, bool) [with PM = SemPolyhedron; PointRange = std::vector<CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > >; PolygonRange = std::vector<std::vector<long unsigned int> >]’
/home/thefroggy/Documents/Libs/CGAL-5.0.2/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h:225:14:   required from ‘void CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(const PointRange&, const PolygonRange&, PolygonMesh&) [with PolygonMesh = SemPolyhedron; PointRange = std::vector<CGAL::Point_3<CGAL::Homogeneous<CGAL::Gmpz> > >; PolygonRange = std::vector<std::vector<long unsigned int> >]’
/home/thefroggy/test/cgal_fail/main.cpp:93:95:   required from here
/usr/include/c++/9/bits/stl_iterator_base_funcs.h:205:71: error: cannot convert ‘SemPolyhedron’ to ‘std::__iterator_traits<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Homogeneous<CGAL::Gmpz>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > >, void>::difference_type’ {aka ‘long int’} in initialization
  205 |       typename iterator_traits<_InputIterator>::difference_type __d = __n;
      |                                                                       ^~~
      |                                                                       |
      |                                                                       SemPolyhedron
```

**Comment by sloriot** [comment] 2020-05-14 06:51
Could you try that [this example]https://doc.cgal.org/latest/Surface_mesh/Surface_mesh_2sm_derivation_8cpp-example.html) is working?

**Comment by palanglois** [comment] 2020-05-14 12:30
Hi Sebastien,

Thank you for your help. The example works on my machine. 
However, it uses Surface_mesh instead of Polyhedron_3 and it is thus not suitable for me because I can't access the Halfedge_handle, Facet_handle nor Vertex_handle.

Any idea how to overcome this issue ?

**Comment by sloriot** [comment] 2020-05-14 12:34
Did you try replacing Surface_mesh  by Polyhedron in the example?

**Comment by palanglois** [comment] 2020-05-14 12:45
Yes, then I get the exact same error as in the orroiginal post.

**Comment by sloriot** [comment] 2020-05-14 13:17
The simplest workaround I see is to add a member function to your derived class that downcast it to the base Polyhedron type and use it for all calls to CGAL functions. Alternatively, you can redefine the function `next(Halfedge_handle, SemPolyhedron)` to forward to the next function called on the base class.

The problem here is that the overload to `boost::next()` is too generic and the right function is not picked because the version with the downcasting is not a better match. For Surface_mesh it works because I guess the descriptor is not an iterator making `iterator_traits` substitution failing and invalidating boost `next` overload.

However, I don't know why we cannot reproduce that error locally.

My closing the issue as there is nothing more we can do I think but we can continue discussing here if you have more questions on this.

**Closed by sloriot** 2020-05-14 13:17 UTC
