### ISSUE TITLE
CGAL::Polygon_mesh_processing::corefine_and_compute_intersection generates an invalid mesh

### ISSUE THREAD

**Issue by sandboxgod** [CGAL/cgal#4197] opened 2019-08-28 15:39 UTC
## Issue Details

In our application, we are attempting to intersect two valid meshes but the result is an invalid mesh that throws assertions if you attempt to analyze the mesh (such as iterating through the faces/vertices after it has been generated).

## Source Code

To make this easy to reproduce, I added a cpp file inside of Surface_mesh/examples/Surface_mesh:

```cpp
#include <CGAL/Simple_cartesian.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/compute_normal.h>
#include <CGAL/Polygon_mesh_processing/connected_components.h>
#include <CGAL/Polygon_mesh_processing/corefinement.h>
#include <CGAL/Polygon_mesh_processing/measure.h>
#include <CGAL/Polygon_mesh_processing/remesh.h>
#include <iostream>
#include <fstream>

#include <boost/foreach.hpp>

typedef CGAL::Simple_cartesian<double>                       Kernel;
typedef Kernel::Point_3                                      Point;
typedef CGAL::Surface_mesh<Point>                            Mesh;

typedef boost::graph_traits<Mesh>::vertex_descriptor vertex_descriptor;

int main(int argc, char* argv[]) 
{
	std::cout << "Starting cc_test" << std::endl;
	Mesh sm1, sm2;
	std::ifstream in1("data/gum.off");
	in1 >> sm1;

	std::ifstream in2("data/gum-cutter.off");
	in2 >> sm2;

	const bool isValidSm1 = sm1.is_valid(true);
	std::cout << "isValidSm1 " << isValidSm1 << std::endl;
	const bool isValidSm2 = sm2.is_valid(true);
	std::cout << "isValidSm2 " << isValidSm2 << std::endl;

	typedef CGAL::Exact_predicates_exact_constructions_kernel CgalKernel;
	typedef CGAL::Point_3<CgalKernel> CgalPoint;
	typedef CGAL::Vector_3<CgalKernel> CgalVector;
	typedef CGAL::Surface_mesh<CgalPoint> CgalMesh;
	Mesh outputMesh;

	std::map<boost::graph_traits<CgalMesh>::edge_descriptor, bool> edgeConstraintMap;
	const bool result = CGAL::Polygon_mesh_processing::corefine_and_compute_intersection(sm1, sm2, outputMesh, CGAL::Polygon_mesh_processing::parameters::all_default(), CGAL::Polygon_mesh_processing::parameters::all_default(), CGAL::Polygon_mesh_processing::parameters::edge_is_constrained_map(boost::make_assoc_property_map(edgeConstraintMap)));
	std::cout << "intersection complete " << result << std::endl;

	bool isSelfIntersecting = CGAL::Polygon_mesh_processing::does_self_intersect(outputMesh);
	std::cout << "isSelfIntersecting " << isSelfIntersecting << std::endl;

	const bool isValid = outputMesh.is_valid(true);
	std::cout << "isValid " << isValid << std::endl;

	if(isValid) {
		std::ofstream outputStream("data/gum-intersection.off");
		outputStream << outputMesh;
	}

}
```

Files: [gumSurfaces.zip](https://github.com/CGAL/cgal/files/3551686/gumSurfaces.zip)

Below is the output:
```
Starting cc_test
isValidSm1 1
isValidSm2 1
intersection complete 1
isSelfIntersecting 1
Integrity of vertex of halfedge h368380 corrupted.
Halfedge of v0 is not an incoming halfedge.
#vertices: iterated: 1 vs number_of_vertices(): 64781
#halfedges: iterated: 368381 vs number_of_halfedges(): 388704
#faces: iterated: 129562 vs number_of_faces(): 129562
isValid 0

```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
Reproduced on Mac 64bit
* Compiler:
Used CMake/make as described by INSTALL.md
* Release or debug mode:
Reproduced in both debug & release.
* Specific flags used (if any):
* CGAL version:
Reproduced in both 4.12 & 4.14. 
* Boost version:
Boost is 1.70.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment] 2019-08-29 05:01
`gum.off` has some self-intersections and is not closed. After removing the self-intersections with the non-documented function `remove_self_intersections()` in `CGAL/Polygon_mesh_processing/repair.h` and closing the mesh I could compute the intersection.

Setting the option `throw_on_self_intersection()` to `true` would have told you the first issue. For the boundary issue, the function should have returned `false`. I keep the ticket open the time I check why it did not.

@MaelRL holes could not be filled automatically as they have some non-manifold vertices. I tried calling `merge_duplicated_vertices_in_boundary_cycles()` but it was not sufficient. Could you please have a more closed look?

**Comment by afabri** [comment] 2019-08-29 08:37
Note also that holes and self-intersections are far away from where corefinement happens.   Also, just corefinement and even union work well in the Polyhedron demo.

**Comment by sandboxgod** [comment] 2019-08-30 14:53
@sloriot I didn't know about the remove_self_intersections() thanks. We were removing self intersections with a different algorithm but it appears I need to update it to use the function you describe.

What function are you calling to "close the mesh"? This would be a fix I need to implement on my end as well. Thanks

**Comment by afabri** [comment] 2019-08-30 15:26
The culprit for the failing `is_valid()`  is that your mesh has non-manifold vertices. That causes a problem in the corefinement. We work on the problem, but for now call  [`duplicate_non_manifold_vertices()`](https://cgal.geometryfactory.com/CGAL/doc/master/Polygon_mesh_processing/group__PMP__repairing__grp.html#ga71b69817fe09aa9b6d366a67e1c635ce)

**Comment by sandboxgod** [comment] 2019-09-05 15:11
@afabri that does indeed resolve the issue. How do I detect the mesh has non-manifold vertices in CGAL 4.12? Just trying to figure out the checks we should do before attempting to perform an intersection.

**Comment by sloriot** [comment] 2019-09-06 07:14
Yes, you can simply call it just to be sure. However, if the non-manifold vertex is in the region where the intersection between the mesh is, the operation will not be possible.

**Comment by sandboxgod** [comment] 2019-09-09 14:41
@sloriot is there anything we could do if such a case occurred? If I understand you correctly, let's say I preemptively call duplicate_non_manifold_vertices() before every intersection. But the intersection can fail if there was a non-manifold vertex in the region. Is there any library call I could do to ensure the intersection completes?  Thanks

**Comment by sloriot** [comment] 2019-09-10 04:10
The only thing you can do is to close the mesh (if the non-manifold vertex is on the boundary) or move the vertices (if you have several umbrella of faces touching) or merge them or anything removing it.

**Comment by sandboxgod** [comment] 2019-09-10 15:21
Thanks now I am clear in this regard.

**Comment by sloriot** [comment] 2020-04-30 07:44
Closing the issue at it was not a bug

**Closed** 2020-04-30 07:44 UTC
Labels: Pkg::PMP, not a bug
