### ISSUE TITLE
How to convert CGAL::Surface_mesh to CGAL::Polyhedron_3?

### ISSUE THREAD

**Issue by Micalson** [CGAL/cgal#5431] opened 2021-02-05 01:10 UTC
Hello, I want to convert `CGAL::Surface_mesh`  to `CGAL::Polyhedron_3`  for the next work.  I checked all the docs on the official website, but I didn't find the result I wanted.  Can someone help me?  Looking forward to your reply.

Regard,

**Comment by afabri** [comment] 2021-02-05 07:12
You can use [`copy_face_graph()`](https://doc.cgal.org/latest/BGL/group__PkgBGLHelperFct.html#ga2d3eb044bfe42eab566779ce32216c11).   Just out of curiosity, what is your scenario that makes you use them both, instead of one of the two consistently?

**Comment by Micalson** [comment] 2021-02-05 07:34
Let me explaint it.
I could run the following code for surface reconstruction.
```
#define CGAL_EIGEN3_ENABLED

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/poisson_surface_reconstruction.h>
#include <CGAL/Surface_mesh.h>
#include <CGAL/IO/read_xyz_points.h>
#include <vector>
#include <fstream>
// Types
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
typedef Kernel::Vector_3 Vector;
typedef std::pair<Point, Vector> Pwn;
typedef CGAL::Surface_mesh<Point> Mesh;

int main(void)
{
	std::vector<Pwn> points;
	std::ifstream stream("data/kitten.xyz");
	if (!stream ||
		!CGAL::read_xyz_points(
			stream,
			std::back_inserter(points),
			CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>()).
			normal_map(CGAL::Second_of_pair_property_map<Pwn>())))
	{
		std::cerr << "Error: cannot read file data/kitten.xyz" << std::endl;
		return EXIT_FAILURE;
	}
	Mesh output_mesh;
	double average_spacing = CGAL::compute_average_spacing<CGAL::Sequential_tag>
		(points, 6, CGAL::parameters::point_map(CGAL::First_of_pair_property_map<Pwn>()));
	if (CGAL::poisson_surface_reconstruction_delaunay
	(points.begin(), points.end(),
		CGAL::First_of_pair_property_map<Pwn>(),
		CGAL::Second_of_pair_property_map<Pwn>(),
		output_mesh, average_spacing))
	{
		std::ofstream out("kitten_poisson-20-30-0.375.off");
		out << output_mesh;
	}
	else
		return EXIT_FAILURE;
	return EXIT_SUCCESS;
}
```
But after I changed `CGAL::Exact_predicates_inexact_constructions_kernel` to `CGAL::Simple_cartesian<float>`, I could not compile the code successfully. So I'll do it the other way. First, I get the surface(CGAL::Polyhedron_3), then I convert it.

**Comment by sgiraudot** [comment] 2021-02-08 07:26
There are two sides to your problem:
- the Kernel: Poisson reconstruction uses Delaunay Triangulations and is likely to fail without exact predicates, so you probably shouldn't use the simple cartesian kernel. However, there shouldn't be compilation errors, I just had a look and I could reproduce them, I'll look into it
- the mesh structure: most algorithms in CGAL can indifferently use `Surface_mesh` or `Polyhedron_3` because they are both models of `FaceGraph`. So it's unlikely that you would need to convert one into the other if you run algorithms from CGAL (unless, of course, you want to change a simple cartesian mesh to a Epick one). The reason @afabri is asking why you are using both is that it's very possible that you don't need to do this conversion at all.

**Comment by afabri** [comment] 2021-02-12 14:15
@Micalson can we close this issue?

**Comment by Micalson** [comment] 2021-02-28 04:04
@afabri No, the cause of the problem about poisson reconstruction compatibility with Simple Cartesian is being investigated.

**Closed** 2021-03-03 06:15 UTC
Labels: Pkg::BGL, question
