### ISSUE TITLE
Archlinux FindCGAL.cmake problem

### ISSUE THREAD

**Issue by untereiner** [CGAL/cgal#2032] opened 2017-04-06 14:13 UTC
## Issue Details

Problem on Archlinux with CMake and FindCGAL.cmake (the one provided by cgal).
The output of CMake:
``
  include could not find load file:
    /usr/lib/CGAL/lib64/CGAL/UseCGAL.cmake
``

## Source Code

I think the problem is in CGALConfig.cmake file.
On archlinux the directory lib64 is at the same level than lib and lib32. 
The variable CGAL_CONFIG_DIR is "/usr/lib/CGAL"
The replace function on line 18 will not find the string "lib64/CGAL" in ${CGAL_CONFIG_DIR} and thus lead to a wrong directory

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
Linux 64 bits (Archlinux)
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
cgal 4.9
* Boost version:
boost 1.63.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment] 2017-04-11 11:00
Could it be the same issue as issue #1632, fixed by the pull-request #1637?

**Comment by untereiner** [comment] 2017-04-12 08:25
It seems to be the same yes. 
Sorry, I didn't look into closed issues. 
Hope the milestone 4.9.1 will be published in the near future.

**Comment by lrineau** [comment] 2017-04-12 08:35
Closed: duplicate of #1632, fixed by #1637.

**Closed by lrineau** 2017-04-12 08:35 UTC
Labels: bug, CMake scripts, duplicate
