### ISSUE TITLE
convert_to_polyhedron() on NefPolyhedron producing Polyhedron_3 with only vertices and no facets

### ISSUE THREAD

**Issue by jjpepper** [CGAL/cgal#2795] opened 2018-02-06 11:08 UTC
## Issue Details

Hi there, I'm getting some unexpected behaviour with the program below.  I'm trying to produce a closed polyhedron with 5 faces of a cuboid as boundaries, and a non-closed surface mesh (terrain) on the top.  I have confirmed that visualising my terrain and the box together shows the proper intersection (see attached image).  The resulting closedNefPolyhedron has 159 vertices and 213 facets, but after converting to Polyhedron_3 the output polyhedron has 151 vertices and 0 facets.  I'm not sure what to make of this?  Note that the cuboid pictured was produced as an OFF file by simply removing the trailing `* nefPolyhedronOfTerrain` from the definition of `closedNefPolyhedron`.

## Source Code

        typedef CGAL::Extended_cartesian< CGAL::Lazy_exact_nt<CGAL::Gmpq> > K;
        typedef CGAL::Polyhedron_3<K> Polyhedron;
        typedef CGAL::Nef_polyhedron_3<K> NefPolyhedron;
        typedef Polyhedron::Vertex_iterator Vertex_iterator;
        typedef K::Plane_3  Plane3;

        const char* fname = "c:\\Temp\\terrain.off";
        Polyhedron polyhedron;
        std::ifstream input(fname);
        input >> polyhedron;
        
        Point3d min,max;
        CGAL::set_ascii_mode(std::cout);

        NefPolyhedron nefPolyhedronOfTerrain(polyhedron);

        std::cout << "NefPolyhedron.num_vertices = " << nefPolyhedronOfTerrain.number_of_vertices() << "\n"
                  << "             .num_facets = "<< nefPolyhedronOfTerrain.number_of_facets() << "\n";

        Box3d box({15,15,-20},{40,40,50});
        auto x0 = GetPlaneForFaceOfBox3(box, Box3FaceId::xMin);
        auto x1 = GetPlaneForFaceOfBox3(box, Box3FaceId::xMax);
        auto y0 = GetPlaneForFaceOfBox3(box, Box3FaceId::yMin);
        auto y1 = GetPlaneForFaceOfBox3(box, Box3FaceId::yMax);
        auto z0 = GetPlaneForFaceOfBox3(box, Box3FaceId::zMin);
        auto z1 = GetPlaneForFaceOfBox3(box, Box3FaceId::zMax);

        NefPolyhedron n1(Plane3(x0.Normal().X, x0.Normal().Y, x0.Normal().Z, x0.D()));
        NefPolyhedron n2(Plane3(x1.Normal().X, x1.Normal().Y, x1.Normal().Z, x1.D()));
        NefPolyhedron n3(Plane3(y0.Normal().X, y0.Normal().Y, y0.Normal().Z, y0.D()));
        NefPolyhedron n4(Plane3(y1.Normal().X, y1.Normal().Y, y1.Normal().Z, y1.D()));
        NefPolyhedron n5(Plane3(z0.Normal().X, z0.Normal().Y, z0.Normal().Z, z0.D()));
        NefPolyhedron n6(Plane3(z1.Normal().X, z1.Normal().Y, z1.Normal().Z, z1.D()));
        NefPolyhedron closedNefPolyhedron = n1 * n2 * n3 * n4 * n5 * n6 * nefPolyhedronOfTerrain;

        std::cout << "closedNefPolyhedron.num_vertices = " << closedNefPolyhedron.number_of_vertices() << "\n"
                  << "                   .num_facets = " << closedNefPolyhedron.number_of_facets() << "\n";

        Polyhedron output;
        closedNefPolyhedron.convert_to_polyhedron(output);

        std::cout << "output.num_vertices = " << output.size_of_vertices() << "\n"
                  << "      .num_facets = " << output.size_of_facets() << "\n";
        std::ofstream out;
        out.open("c:\\Temp\\output_terrain.off");
        out << output;
        out.close();
## Program Output
    NefPolyhedron.num_vertices = 690
             .num_facets = 1008
    closedNefPolyhedron.num_vertices = 159
                   .num_facets = 213
    output.num_vertices = 151
      .num_facets = 0
## Environment

* Operating system: Windows, 64 bit:
* Compiler: Visual Studio 2017 with /std:c++latest
* Release or debug mode: Both
* Specific flags used (if any):
* CGAL version: 4.11
* Boost version: 1.66.0
* Other libraries versions if used (Eigen, TBB, etc.): None

![terrain_and_cube](https://user-images.githubusercontent.com/10545251/35855983-a31f45b6-0b6f-11e8-8728-7765180b96af.PNG)

**Comment by jjpepper** [comment] 2018-02-12 10:59
Hey @sloriot, I have been trying to narrow this down to a simpler example, see the following code:
## Code
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/IO/Nef_polyhedron_iostream_3.h>
#include <CGAL/Nef_3/SNC_indexed_items.h>
#include <CGAL/convex_decomposition_3.h> 
#include <list>
void foo()
    {
        typedef CGAL::Extended_cartesian< CGAL::Lazy_exact_nt<CGAL::Gmpq> > K;
        typedef CGAL::Polyhedron_3<K> Polyhedron;
        typedef CGAL::Nef_polyhedron_3<K> NefPolyhedron;
        typedef K::Plane_3  Plane;
        typedef K::Point_3 Point;
        typedef NefPolyhedron::Volume_const_iterator Volume_const_iterator;

        Polyhedron terrainPolyhedron;
        terrainPolyhedron.make_triangle({-2,-1,0.1},{3,-1,0.1},{0.5,3,0.1});
        auto&& halfEdge = terrainPolyhedron.create_center_vertex(terrainPolyhedron.halfedges_begin());
        halfEdge->vertex()->point() = {0.5, 0.5, 0.75};
        CGAL_assertion(terrainPolyhedron.is_pure_triangle());
        std::cout << "terrainPolyhedron.num_vertices = " << terrainPolyhedron.size_of_vertices() << "\n"
                  << "                 .num_facets = " << terrainPolyhedron.size_of_facets() << "\n";
        
        NefPolyhedron nefPolyhedronOfTerrain(terrainPolyhedron);
        std::cout << "nefPolyhedronOfTerrain.num_vertices = " << nefPolyhedronOfTerrain.number_of_vertices() << "\n"
                  << "                      .num_facets = "<< nefPolyhedronOfTerrain.number_of_facets() << "\n";

        std::istringstream unitCubeInput(
         R"(OFF
            8 6 0

            0 0 0
            1 0 0
            0 1 0
            1 1 0
            0 0 1
            1 0 1
            0 1 1
            1 1 1
            4  0 2 3 1
            4  0 1 5 4
            4  1 3 7 5
            4  2 6 7 3
            4  0 4 6 2
            4  4 5 7 6
        )");

        Polyhedron boxPolyhedron;
        unitCubeInput >> boxPolyhedron;
        assert(boxPolyhedron.is_closed());
        NefPolyhedron closedNefPolyhedron = NefPolyhedron(boxPolyhedron) * nefPolyhedronOfTerrain;

        std::cout << "closedNefPolyhedron.num_vertices = " << closedNefPolyhedron.number_of_vertices() << "\n"
                  << "                   .num_facets = " << closedNefPolyhedron.number_of_facets() << "\n";

        CGAL::convex_decomposition_3(closedNefPolyhedron);
        #ifdef CONVERT_OUTPUT_TO_POLYHEDRON_3
            Polyhedron closedOutputPolyhedron;
            closedNefPolyhedron.convert_to_polyhedron(closedOutputPolyhedron);

            std::cout << "closedOutputPolyhedron.num_vertices = " << closedOutputPolyhedron.size_of_vertices() << "\n"
                      << "                      .num_facets = " << closedOutputPolyhedron.size_of_facets() << "\n";
        #endif 
        std::list<Polyhedron> convexParts;
        // the first volume is the outer volume, which is 
        // ignored in the decomposition
        Volume_const_iterator ci = ++closedNefPolyhedron.volumes_begin();
        for (; ci != closedNefPolyhedron.volumes_end(); ++ci) 
        {
            if (ci->mark()) 
            {
                Polyhedron part;
                closedNefPolyhedron.convert_inner_shell_to_polyhedron(ci->shells_begin(), part);
                convexParts.push_back(part);
            }
        }
        std::cout << "decomposition into " << convexParts.size() << " convex parts " << std::endl;
    }
```

## Output
The resulting output is:
```
terrainPolyhedron.num_vertices = 4
                 .num_facets = 3
nefPolyhedronOfTerrain.num_vertices = 12
                      .num_facets = 9
closedNefPolyhedron.num_vertices = 16
                   .num_facets = 9
decomposition into 0 convex parts
```
## Important Notes
* When `CONVERT_OUTPUT_TO_POLYHEDRON_3` is defined, CGAL_precondition(is_simple()) in `convert_to_polyhedron()` fails.  Hence the reason for trying to decompose into convex parts.  
* If `terrainPolyhedron` is made to be a closed tetrahedron (with the bottom face added), everything works as expected and the output geometry is as expected
** Hence the problem seems to be limited to having a non-closed Polyhedron_3 passed to the constructor of Nef_polyhedron_3.  
** I have also tried constructing the nefPolyhedronOfTerrain from a set of 3 planes and this fails in the same way.

## Picture
![simple_terrain_and_unit_cube](https://user-images.githubusercontent.com/10545251/36093560-fb754cdc-1025-11e8-9635-bcedc091d759.PNG)

**Comment by maxGimeno** [comment] 2018-10-17 12:02
It is not possible to use Convex_decomposition_3 on the intersection nore the terrain because they are not bounded (cf precondition in the doc). What is really strange is the impossibility to convert an open nef to a polyhedron when it is possible to confert an open polyhedron to a nef.

**Comment by maxGimeno** [comment] 2018-10-17 12:50
Doc says a nef must be simple (implies 2-manifold) to be convertible to a normal polyhedron. An open nef is not 2-manifold, so it won't work. It is expected behavior, so I close this issue.

**Closed by maxGimeno** 2018-10-17 12:50 UTC
Labels: Pkg::Nef_3

**Comment by maxGimeno** [comment] 2018-10-18 07:10
Me too but an open mesh has border edges, and a border edges cannot be 2-manifold. 
For what you were trying to achieve I think the easier way would be to extrude the terrain before converting it to a nef, this way you only work with closed volumes and the intersection will return what you expect. (see [extrude_mesh](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-15/output2/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga102e1ba5d709c5e53e013160792e4d08) )

**Comment by gdamiand** [comment] 2018-10-18 10:12
I think a border edge is manifold. The definition of a manifold edge is "an edge incident to only one or two faces". A disk is a 2-manifold.

**Comment by maxGimeno** [comment] 2018-10-18 11:39
The implementation of is_edge_2_manifold() in Nef, we check if the edge has two faces, not one or two.
