### ISSUE TITLE
Error with in-source compilation: `cmake .  && make && cmake . && make`

### ISSUE THREAD

**Issue by nkeskes** [CGAL/cgal#834] opened 2016-02-26 13:39 UTC
I an traing  to build cgal on ubuntu 16.4 and i am facing this type of error for all g++ > 4.8 

[  0%] Built target CGAL
[  0%] Building CXX object Installation/src/CGAL_Qt5/CMakeFiles/CGAL_Qt5.dir/all_files.cpp.o
In file included from /data_local/CGAL/cgal-master/build/Installation/src/CGAL_Qt5/all_files.cpp:2:0:
/data_local/CGAL/cgal-master/Installation/src/CGAL_Qt5/qrc_Triangulation_2.cpp:9:45: error: redefinition of ‘const unsigned char qt_resource_data []’
 static const unsigned char qt_resource_data[] = {

Any idea

Thank's
                                             ^

**Comment by sgiraudot** [comment] 2016-02-26 14:20
This is strange because the incriminated files are automatically generated and the part that causes an error in your case should not differ from one platform to another.

Can you tell us exactly what you did to try to build CGAL? (commands, etc.)
Also, what versions of CGAL and Qt5 do you use?

**Comment by freud14** [comment] 2016-03-06 14:06
I have the same problem with my cloned repo. I tried to remove CMakeCache and CMakeFiles but it does not work. But if I cloned again the repository and do a "cmake .", it compiles correctly. It must be something in the build configuration files.

**Comment by lrineau** [comment] 2016-03-06 15:16
I think there might have been an issue if you:
  - cloned, configured CGAL before the PR #385 was merged into `master` (October 14, 2015),
  - then reused the same clone and build directory *after*.
There are generated files that CMake do not track correctly: the generated moc files. @freud14, @nkeskes, if they are duplicated, that may explain the link errors  you both got. Try removing all the files that have "moc" in their name, and re-run CMake and rebuild.

Please tell us if that fixes the issue.

**Comment by freud14** [comment] 2016-03-06 17:34
You're right, it is working. However, I cloned the project from Github way after October 14, 2015.

**Comment by freud14** [comment] 2016-03-06 19:30
I've found a way to reproduce the bug. If you do a `cmake .` then a `make` and then another  `cmake .` followed by another `make`, it will trigger the bug.

**Comment by sloriot** [comment] 2016-03-14 09:07
I gave it a try last week but could not reproduce it. Could you describe precisely what you did?

**Comment by lrineau** [comment] 2016-03-14 11:05
I think our CMake scripts have a important flaw if the build of CGAL_Qt5 is done in-sources: the generated moc files are .cpp files, and our CMake scripts do "glob" on `*.cpp`...

**Comment by lrineau** [comment] 2016-03-14 11:09
I can reproduce the bug:
  - extract CGAL-4.8-beta1.tar.xz
  - `cd CGAL-4.8-beta1`
  - `cmake .` (an in-source configuration)
  - `make`
  - `cmake .`
then the generated file `CGAL-4.8-beta1/src/CGAL_Qt5/all_files.cpp` is incorrect.

**Comment by lrineau** [comment] 2016-03-14 11:10
The bug is also in CGAL-4.7.

**Closed** 2016-03-18 10:40 UTC
Labels: bug, CMake scripts
