### ISSUE TITLE
CGAL/Mesh_3/Lloyd_move.h: crash (assertion c3t3.is_in_complex(current_cell)'), random, and rare

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#3547] opened 2018-12-14 08:43 UTC
## Note 2019/03/01, Laurent Rineau

This error is rare, and occurs a lot more on Linux than on Windows. It seems to happen a lot more with TBB, 
```
cgal /srv/CGAL/www/testsuite $ zgrep -F -l 'c3t3.is_in_complex(current_cell)' CGAL-4.14-I*/Mesh_3/*gz
CGAL-4.14-I-102/Mesh_3/TestReport_Friedrich_Ubuntu-clang-64bits.gz
CGAL-4.14-I-120/Mesh_3/TestReport_gimeno_CentOS6.gz
CGAL-4.14-I-120/Mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz
CGAL-4.14-I-24/Mesh_3/TestReport_lrineau_Debian-Testing.gz
CGAL-4.14-I-35/Mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz
CGAL-4.14-I-53/Mesh_3/TestReport_lrineau_Ubuntu-Latest.gz
CGAL-4.14-I-59/Mesh_3/TestReport_lrineau_Fedora-32.gz
CGAL-4.14-Ic-100/Mesh_3/TestReport_gimeno_CentOS6.gz
CGAL-4.14-Ic-101/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz
CGAL-4.14-Ic-101/Mesh_3/TestReport_lrineau_Fedora-32.gz
CGAL-4.14-Ic-103/Mesh_3/TestReport_lrineau_ArchLinux-clang.gz
CGAL-4.14-Ic-104/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz
CGAL-4.14-Ic-110/Mesh_3/TestReport_gimeno_Fedora-rawhide.gz
CGAL-4.14-Ic-110/Mesh_3/TestReport_lrineau_ArchLinux-clang-CXX17-Release.gz
CGAL-4.14-Ic-110/Mesh_3/TestReport_lrineau_ArchLinux-clang.gz
CGAL-4.14-Ic-111/Mesh_3/TestReport_lrineau_Ubuntu-Latest-CXX11.gz
CGAL-4.14-Ic-115/Mesh_3/TestReport_lrineau_CentOS6-32.gz
CGAL-4.14-Ic-119/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6.gz
CGAL-4.14-Ic-122/Mesh_3/TestReport_gimeno_CentOS6.gz
CGAL-4.14-Ic-130/Mesh_3/TestReport_gimeno_Debian-Stable.gz
CGAL-4.14-Ic-130/Mesh_3/TestReport_lrineau_Fedora-32.gz
CGAL-4.14-Ic-136/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz
CGAL-4.14-Ic-13/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz
CGAL-4.14-Ic-14/Mesh_3/TestReport_lrineau_Fedora-32.gz
CGAL-4.14-Ic-16/Mesh_3/TestReport_lrineau_ArchLinux-clang-CXX14.gz
CGAL-4.14-Ic-17/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6.gz
CGAL-4.14-Ic-21/Mesh_3/TestReport_gimeno_Fedora-rawhide.gz
CGAL-4.14-Ic-23/Mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz
CGAL-4.14-Ic-25/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz
CGAL-4.14-Ic-25/Mesh_3/TestReport_lrineau_ArchLinux-clang-CXX14.gz
CGAL-4.14-Ic-27/Mesh_3/TestReport_lrineau_Ubuntu-Latest.gz
CGAL-4.14-Ic-32/Mesh_3/TestReport_gimeno_Fedora-rawhide.gz
CGAL-4.14-Ic-34/Mesh_3/TestReport_lrineau_Fedora.gz
CGAL-4.14-Ic-43/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz
CGAL-4.14-Ic-45/Mesh_3/TestReport_lrineau_ArchLinux.gz
CGAL-4.14-Ic-46/Mesh_3/TestReport_lrineau_Ubuntu-Latest-CXX11.gz
CGAL-4.14-Ic-49/Mesh_3/TestReport_lrineau_ArchLinux-CXX17-Release.gz
CGAL-4.14-Ic-54/Mesh_3/TestReport_lrineau_CentOS5.gz
CGAL-4.14-Ic-56/Mesh_3/TestReport_Friedrich_Ubuntu-clang-64bits.gz
CGAL-4.14-Ic-56/Mesh_3/TestReport_lrineau_ArchLinux-CXX17-Release.gz
CGAL-4.14-Ic-68/Mesh_3/TestReport_gimeno_CentOS7.gz
CGAL-4.14-Ic-68/Mesh_3/TestReport_lrineau_CentOS6-32.gz
CGAL-4.14-Ic-69/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz
CGAL-4.14-Ic-70/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz
CGAL-4.14-Ic-75/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz
CGAL-4.14-Ic-78/Mesh_3/TestReport_lrineau_Fedora-32.gz
CGAL-4.14-Ic-80/Mesh_3/TestReport_lrineau_Fedora.gz
CGAL-4.14-Ic-81/Mesh_3/TestReport_lrineau_CentOS6-32.gz
CGAL-4.14-Ic-84/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz
CGAL-4.14-Ic-87/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz
CGAL-4.14-Ic-87/Mesh_3/TestReport_lrineau_CentOS6-32.gz
CGAL-4.14-Ic-90/Mesh_3/TestReport_gimeno_CentOS7.gz
CGAL-4.14-Ic-92/Mesh_3/TestReport_lrineau_ArchLinux-clang-CXX14.gz
CGAL-4.14-Ic-96/Mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz
CGAL-4.14-Ic-99/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz
CGAL-4.14-Ic-9/Mesh_3/TestReport_Friedrich_Ubuntu-clang-64bits.gz
CGAL-4.14-Ic-9/Mesh_3/TestReport_gimeno_CentOS6.gz

```

## Issue Details

```
------------------------------------------------------------------
- ProgramOutput.test_meshing_3D_gray_image.x86-64_Darwin-13.0_Apple-clang-5.0_Release
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1544738382
Mesh generation from a 3D image:
	Seed is	1544738382
	Volume is 1237508.27855776
	Number of cells: 15083
	Number of facets: 7288
	Number of vertices: 4216
Refining again...
	Number of cells: 15084
	Number of facets: 7292
	Number of vertices: 4217
Exude...
	Number of cells: 14449
	Number of facets: 7292
	Number of vertices: 4217
	Quality before optimization: 0.647213 - Quality after optimization: 4.0742
	Volume is 1237491.34735826
Perturb...
	Number of cells: 14788
	Number of facets: 7292
	Number of vertices: 4217
	Quality before optimization: 0.647213 - Quality after optimization: 12.0033
	Volume is 1237412.39520408
Odt...
	Number of cells: 14546
	Number of facets: 7330
	Number of vertices: 4217
	Volume is 1220470.90463573
Lloyd...
CGAL error: assertion violation!
Expression : c3t3.is_in_complex(current_cell)
File       : /Users/cgaltester/cgal_test/CGAL-4.14-Ic-69/include/CGAL/Mesh_3/Lloyd_move.h
Line       : 585
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
libc++abi.dylib: terminating with uncaught exception of type CGAL::Assertion_exception: CGAL ERROR: assertion violation!
Expr: c3t3.is_in_complex(current_cell)
File: /Users/cgaltester/cgal_test/CGAL-4.14-Ic-69/include/CGAL/Mesh_3/Lloyd_move.h
Line: 585
./cgal_test_with_cmake: line 70: 73686 Abort trap: 6           ./test_meshing_3D_gray_image
```

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-69/Mesh_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: `master` (4.14)
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment] 2019-02-05 13:07
Three more of that issue, here:
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-110/Mesh_3/TestReport_lrineau_ArchLinux-clang-CXX17-Release.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-110/Mesh_3/TestReport_lrineau_ArchLinux-clang.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-110/Mesh_3/TestReport_gimeno_Fedora-rawhide.gz

**Comment by lrineau** [comment] 2019-03-01 10:40
I got one hit on Windows:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-23/Mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz
```
Lloyd...
CGAL error: assertion violation!
Expression : c3t3.is_in_complex(current_cell)
File       : C:\CGAL\test\CGAL-4.14-Ic-23\include\CGAL/Mesh_3/Lloyd_move.h
Line       : 585
Explanation: 
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html
```

**Comment by lrineau** [comment] 2019-06-20 10:13
Again, with clang on Linux:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-62/Mesh_3/TestReport_lrineau_ArchLinux-clang.gz
```
------------------------------------------------------------------
- ProgramOutput.test_meshing_3D_gray_image_deprecated.ArchLinux-clang
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1560908120
Mesh generation from a 3D image:
[...]
Lloyd...
CGAL error: assertion violation!
Expression : c3t3.is_in_complex(current_cell)
File       : /mnt/testsuite/include/CGAL/Mesh_3/Lloyd_move.h
Line       : 563
```

**Comment by sloriot** [comment] 2020-04-21 16:18
[`CGAL-4.13-I-82`](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-I-82/Mesh_3/TestReport_gimeno_CentOS7.gz) seems to be the oldest error.

**Comment by MaelRL** [comment] 2020-04-21 16:24
The assertion was added with P3M3 in 4.13 (https://github.com/CGAL/cgal/pull/2658/files#diff-e80558228a3586b5beefed98e78b0796R573)

**Comment by MaelRL** [comment] 2020-05-04 12:02
Duplicate of #4566

**Closed by MaelRL** 2020-05-04 12:02 UTC
Labels: Pkg::Mesh_3, bug
