### ISSUE TITLE
Joining valid Polygons creates PolygonSet with invalid PolygonWithHoles

### ISSUE THREAD

**Issue by Fro-Z** [CGAL/cgal#3667] opened 2019-02-07 17:24 UTC
## Issue Details

I found two valid polygons that when joined together into Polygon_set_2 form an invalid Polygon_with_holes_2.

Those two polygons are triangles with a common vertex.

The resulting Polygon_with_holes_2's outer boundary seems to have proper counter-clockwise vertex order, but fails the has_valid_orientation_polygon_with_holes() check.

This was done using Epeck kernel.

![image](https://user-images.githubusercontent.com/8879226/52430034-7c321a80-2b05-11e9-9a0f-1a4cc6ddbae9.png)

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/Polygon_set_2.h>
#include <memory>
#include <sstream>
#include <assert.h>

template <typename CGalType>
CGalType cgalTypeFromString(const std::string& str) {
    std::stringstream stream(str);
    CGalType value;
    stream >> value;

    return value;
}

int main()
{
    /**
    *  These two valid polygons when merged form a PolygonSet with invalid PolygonWithHoles
    */
    using K = CGAL::Exact_predicates_exact_constructions_kernel;
    using PolygonSet = CGAL::Polygon_set_2<K>;
    using Polygon = CGAL::Polygon_2<K>;
    using PolygonWithHoles = CGAL::Polygon_with_holes_2<K>;

    auto traits = std::make_unique<PolygonSet::Traits_2>();

    const std::string firstPolyString(
        "3 -9924612878548874890304733981971/20282409603651670423947251286016 "
        "17188006152006536578823865513759/81129638414606681695789005144064 "
        "-9519368606443823699966886983117/20282409603651670423947251286016 "
        "6637310640423212698853225948775/40564819207303340847894502572032 "
        "-8874718064193764428030739181071/20282409603651670423947251286016 "
        "1239265188467743494005293520325/10141204801825835211973625643008");

    const std::string secondPolyString(
        "3 -14112493806255234993030698361967/40564819207303340847894502572032 "
        "2857271125160752150753227128691/40564819207303340847894502572032 "
        "-9924612878548874890304733981971/20282409603651670423947251286016 "
        "17188006152006536578823865513759/81129638414606681695789005144064 "
        "-4017296560458822758487345961369/10141204801825835211973625643008 "
        "3667759669370854531428921126399/40564819207303340847894502572032");

    Polygon firstPoly(cgalTypeFromString<Polygon>(firstPolyString));
    Polygon secondPoly(cgalTypeFromString<Polygon>(secondPolyString));

    assert(CGAL::is_valid_unknown_polygon(firstPoly, *traits) &&
        firstPoly.is_counterclockwise_oriented());
    assert(CGAL::is_valid_unknown_polygon(secondPoly, *traits) &&             
        secondPoly.is_counterclockwise_oriented());

    // Create polygon set form the first polygon
    PolygonSet pSet;
    pSet.join(firstPoly);

    // Test that polygonset is made of valid polygons
    {
        std::vector<PolygonWithHoles> polys(pSet.number_of_polygons_with_holes());
        pSet.polygons_with_holes(polys.begin());
        for(PolygonWithHoles& poly : polys) {
            // This passes
            assert(CGAL::is_valid_polygon_with_holes(poly, *traits)); // This passes
        }
    }

    pSet.join(secondPoly);

    // Test that polygonset is made of valid polygons
    {
        std::vector<PolygonWithHoles> polys(pSet.number_of_polygons_with_holes());
        pSet.polygons_with_holes(polys.begin());
        for(PolygonWithHoles& poly : polys) {
            //This fails has_valid_orientation_polygon_with_holes check
            assert(CGAL::is_valid_polygon_with_holes(poly, *traits)); 
        }
    }
}
```

## Environment

* Operating system: Windows 10
* Compiler: MSVC 2017 15.9.4
* Release or debug mode: Tested in debug mode, likely happens in both
* Specific flags used (if any):
Preprocessor defines:
CGAL_USE_CORE=1
CGAL_HEADER_ONLY=1

* CGAL version: 4.13, from the installer
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by efifogel** [comment] 2019-02-09 15:38
Indeed, there is a problem.
However, the problem is only in the orientation test.
Attached is a patch to
Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_traits_adaptor.h.
Will be integrated into master soon...
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by Fro-Z** [comment] 2019-02-12 18:55
Can you post the patch through the Github website? Email attachments are ignored.

**Comment by efifogel** [comment] 2019-02-13 10:20
[Gps_traits_adaptor.patch.zip](https://github.com/CGAL/cgal/files/2859879/Gps_traits_adaptor.patch.zip)

**Comment by lrineau** [comment] 2019-02-13 11:06
[**@efifogel**](https://github.com/efifogel) commented on [Feb 13, 2019, 11:20 AM GMT+1](https://github.com/CGAL/cgal/issues/3667#issuecomment-463142806 "2019-02-13T10:20:34Z - Replied by Github Reply Comments"):
> [Gps_traits_adaptor.patch.zip](https://github.com/CGAL/cgal/files/2859879/Gps_traits_adaptor.patch.zip)

Is that a patch that is already in a pull-request or in `master`?

**Comment by efifogel** [comment] 2019-02-16 12:35
It has now: #3688
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Closed** 2019-02-28 19:52 UTC
Labels: Pkg:Boolean_set_operations_2, bug
