### ISSUE TITLE
CGAL Qt5/OpenGL demos uses OpenGL 3.3 Compatibility Profile but Mesa does not implement the Compatibility Profile

### ISSUE THREAD

**Issue by gdamiand** [CGAL/cgal#254] opened 2015-08-05 17:34 UTC
I still have problem to run the lcc demo (ubuntu 14.04, g++ 4.8.4). 

```
./Linear_cell_complex_3_demo 
QOpenGLShader::c./Linear_cell_complex_3_demo 
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
in highp vec3 normal;
in highp vec4 color;
uniform highp mat4 mvp_matrix;
uniform highp mat4 mv_matrix; 
out highp vec4 fP; 
out highp vec3 fN; 
out highp vec4 fColor; 
void main(void)
{
   fP = mv_matrix * vertex; 
   fN = mat3(mv_matrix)* normal; 
   fColor = color; 
   gl_Position = mvp_matrix * vertex;
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 fP; 
in highp vec3 fN; 
in highp vec4 fColor; 
uniform vec4 light_pos;  
uniform vec4 light_diff; 
uniform vec4 light_spec; 
uniform vec4 light_amb;  
uniform float spec_power ; 
void main(void) { 
   vec3 L = light_pos.xyz - fP.xyz; 
   vec3 V = -fP.xyz; 
   vec3 N = normalize(fN); 
   L = normalize(L); 
   V = normalize(V); 
   vec3 R = reflect(-L, N); 
   vec4 diffuse = max(dot(N,L), 0.0) * light_diff * fColor; 
   vec4 specular = pow(max(dot(R,V), 0.0), spec_power) * light_spec; 
gl_FragColor = light_amb*fColor + diffuse  ; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
uniform highp mat4 mvp_matrix;
void main(void)
{
   gl_Position = mvp_matrix * vertex;
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
uniform highp vec4 color; 
void main(void) { 
gl_FragColor = color; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( normal ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( normal ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::uniformLocation( mvp_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( mv_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_pos ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_diff ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_spec ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_amb ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( spec_power ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::uniformLocation( mvp_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
Erreur de segmentation (core dumped)
ompile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
in highp vec3 normal;
in highp vec4 color;
uniform highp mat4 mvp_matrix;
uniform highp mat4 mv_matrix; 
out highp vec4 fP; 
out highp vec3 fN; 
out highp vec4 fColor; 
void main(void)
{
   fP = mv_matrix * vertex; 
   fN = mat3(mv_matrix)* normal; 
   fColor = color; 
   gl_Position = mvp_matrix * vertex;
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 fP; 
in highp vec3 fN; 
in highp vec4 fColor; 
uniform vec4 light_pos;  
uniform vec4 light_diff; 
uniform vec4 light_spec; 
uniform vec4 light_amb;  
uniform float spec_power ; 
void main(void) { 
   vec3 L = light_pos.xyz - fP.xyz; 
   vec3 V = -fP.xyz; 
   vec3 N = normalize(fN); 
   L = normalize(L); 
   V = normalize(V); 
   vec3 R = reflect(-L, N); 
   vec4 diffuse = max(dot(N,L), 0.0) * light_diff * fColor; 
   vec4 specular = pow(max(dot(R,V), 0.0), spec_power) * light_spec; 
gl_FragColor = light_amb*fColor + diffuse  ; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
uniform highp mat4 mvp_matrix;
void main(void)
{
   gl_Position = mvp_matrix * vertex;
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
uniform highp vec4 color; 
void main(void) { 
gl_FragColor = color; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( normal ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( normal ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::uniformLocation( mvp_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( mv_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_pos ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_diff ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_spec ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( light_amb ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( spec_power ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::uniformLocation( mvp_matrix ): shader program is not linked 
QOpenGLShaderProgram::uniformLocation( color ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
Erreur de segmentation (core dumped)
```

**Comment by bo0ts** [comment] 2015-08-06 07:43
It seems the shader requires GLSL 3.3 (equivalent to OpenGL 3.3) and your card supports up to GLSL 1.5 (equivalent to OpenGL 3.1).

Can you quickly confirm the supported version by showing the output of:

    glewinfo | grep "OpenGL version"

**Comment by gdamiand** [comment] 2015-08-06 07:56
The result

OpenGL version 3.0 Mesa 10.3.0 is supported

If you are right, that means the cgal demo could not be run in several computers, right ?
I am not sure this is a good improvement...

**Comment by lrineau** [comment] 2015-08-06 09:04
cc @maxGimeno 

Maybe we will have to go back to older versions of GLSL.

**Comment by lrineau** [comment] 2015-08-06 09:10
Can anybody find somewhere which Mesa versions support which GLSL version?

Mesa 10.3 claims to support OpenGL 3.3, but it seems it does not like GLSL 330 (where it should be the GLSL  version of OpenGL 3.3).

**Comment by lrineau** [comment] 2015-08-06 09:22
Maybe here? http://mesamatrix.net/

**Comment by lrineau** [comment] 2015-08-06 09:42
Is seems that Mesa 10.3 [already supported GLSL 3.30](http://cgit.freedesktop.org/mesa/mesa/plain/docs/GL3.txt?h=10.3).

But I read [somewhere][SO] that Mesa does not support *OpenGL 3.3 compatibility profile* and that it falls back to OpenGL 3.0 in that case.

[SO]: http://stackoverflow.com/a/25951426/1728537

**Comment by lrineau** [comment] 2015-08-06 10:26
I think that will be too short of the first beta release of CGAL-4.7. I have to publish it before SIGGRAPH.

There will be a second one, shortly after.

**Comment by maxGimeno** [comment] 2015-08-06 13:23
I pushed something in the Qt5-support version that should resolve your problem. Can you try it and tell me if that works ?

**Comment by gdamiand** [comment] 2015-08-06 18:44
I cannot find your branch. Do I need a special command to find it ?

Anyway, I try to replace #version 330 by #version 140 in master, and I have a direct Segmentation fault when running the demo (without any message about shaders).

**Comment by maxGimeno** [comment] 2015-08-07 06:28
The branch was in public-dev. Okay so you have a problem with your
drivers, same as Alexander and Phillip, probably. We talked about it with
Laurent yesterday, the problem is that mesa drivers (I think) do not
support Compatibility Profile, so some libQGLViewer featers make the
program segfault (something about the color possibly). Apparently we won't
try to fix it before beta2 because of SIGGRAPH, but if you really need the
LCC demo you can call a 2.1 openGL contecxt instead of the current 3.3. To
do so go to Viewer.h and replace all the QOpenGLFunctions_3_3_Core by
QOpenGLFunctions_2_1, go to CreateOpenGLContext.h and change
format.setVersion(3,3); by format.setVersion(2,1), and finally in
Viewer.cpp replace all the #version 140 by #version 120 and in the shader
code change "out" into "varying". This should make THIS demo work, but some
of them actually need a context >=3.1...

2015-08-06 20:44 GMT+02:00 Guillaume Damiand <notifications@github.com>:

**Comment by maxGimeno** [comment] 2015-08-07 08:51
To make it easier, I join my diff for this patch

2015-08-07 8:28 GMT+02:00 Maxime Gimeno <maxime.gimeno@gmail.com>:

>  The branch was in public-dev. Okay so you have a problem with your
> drivers, same as Alexander and Phillip, probably. We talked about it with
> Laurent yesterday, the problem is that mesa drivers (I think) do not
> support Compatibility Profile, so some libQGLViewer featers make the
> program segfault (something about the color possibly). Apparently we won't
> try to fix it before beta2 because of SIGGRAPH, but if you really need the
> LCC demo you can call a 2.1 openGL contecxt instead of the current 3.3. To
> do so go to Viewer.h and replace all the QOpenGLFunctions_3_3_Core by
> QOpenGLFunctions_2_1, go to CreateOpenGLContext.h and change
> format.setVersion(3,3); by format.setVersion(2,1), and finally in
> Viewer.cpp replace all the #version 140 by #version 120 and in the shader
> code change "out" into "varying". This should make THIS demo work, but some
> of them actually need a context >=3.1...
>
>
> 2015-08-06 20:44 GMT+02:00 Guillaume Damiand <notifications@github.com>:
>
>> I cannot find your branch. Do I need a special command to find it ?
>>
>> Anyway, I try to replace #version 330 by #version 140 in master, and I
>> have a direct Segmentation fault when running the demo (without any message
>> about shaders).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CGAL/cgal/issues/254#issuecomment-128471222>.
>>
>
>

diff --git a/GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h b/GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
index 514b6e8..7e32158 100644
--- a/GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
+++ b/GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
@@ -27,7 +27,7 @@ inline QGLContext* createOpenGLContext()
 {
     QOpenGLContext *context = new QOpenGLContext();
     QSurfaceFormat format;
-    format.setVersion(3,3);
+    format.setVersion(2,1);
     format.setProfile(QSurfaceFormat::CompatibilityProfile);
     context->setFormat(format);
     return QGLContext::fromOpenGLContext(context);
diff --git a/Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp b/Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
index cf92a38..f6e8428 100644
--- a/Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
+++ b/Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
@@ -232,7 +232,7 @@ void Viewer::compile_shaders()
     //Vertex source code
     const char vertex_source[] =
     {
-        "#version 140 \n"
+        "#version 120 \n"
         "in highp vec4 vertex;\n"
         "in highp vec3 normal;\n"
         "in highp vec4 color;\n"
@@ -240,9 +240,9 @@ void Viewer::compile_shaders()
         "uniform highp mat4 mvp_matrix;\n"
         "uniform highp mat4 mv_matrix; \n"
 
-        "out highp vec4 fP; \n"
-        "out highp vec3 fN; \n"
-        "out highp vec4 fColor; \n"
+        "varying highp vec4 fP; \n"
+        "varying highp vec3 fN; \n"
+        "varying highp vec4 fColor; \n"
         "void main(void)\n"
         "{\n"
         "   fP = mv_matrix * vertex; \n"
@@ -254,7 +254,7 @@ void Viewer::compile_shaders()
     //Vertex source code
     const char fragment_source[] =
     {
-        "#version 140 \n"
+        "#version 120 \n"
         "in highp vec4 fP; \n"
         "in highp vec3 fN; \n"
         "in highp vec4 fColor; \n"
@@ -310,7 +310,7 @@ void Viewer::compile_shaders()
     //Vertex source code
     const char vertex_source_p_l[] =
     {
-        "#version 140 \n"
+        "#version 120 \n"
         "in highp vec4 vertex;\n"
         "uniform highp mat4 mvp_matrix;\n"
         "void main(void)\n"
@@ -321,7 +321,7 @@ void Viewer::compile_shaders()
     //Vertex source code
     const char fragment_source_p_l[] =
     {
-        "#version 140 \n"
+        "#version 120 \n"
         "uniform highp vec4 color; \n"
         "void main(void) { \n"
         "gl_FragColor = color; \n"
diff --git a/Linear_cell_complex/demo/Linear_cell_complex/Viewer.h b/Linear_cell_complex/demo/Linear_cell_complex/Viewer.h
index e5dc086..c03977f 100644
--- a/Linear_cell_complex/demo/Linear_cell_complex/Viewer.h
+++ b/Linear_cell_complex/demo/Linear_cell_complex/Viewer.h
@@ -25,11 +25,11 @@
 #include <QGLViewer/qglviewer.h>
 #include <QKeyEvent>
 
-#include <QOpenGLFunctions_3_3_Core>
+#include <QOpenGLFunctions_2_1>
 #include <QOpenGLVertexArrayObject>
 #include <QGLBuffer>
 #include <QOpenGLShaderProgram>
-class Viewer : public QGLViewer, QOpenGLFunctions_3_3_Core
+class Viewer : public QGLViewer, QOpenGLFunctions_2_1
 {
   Q_OBJECT

**Comment by lrineau** [comment] 2015-08-07 09:27
See also my mail *Status of Qt5/OpenGL demos in CGAL-4.7-beta1, there will be 4.7-beta2*, posted today in CGAL-develop.

**Comment by maxGimeno** [comment] 2015-08-11 06:17
I pushed a new branch in cgal/public-dev, called CGAL_Qt5_Support_for_Mesa-GF. It is supposed to fix the problem for all the demos, please test especially Triangulation_3 and Periodic_triangulation_3 and tell me if everything's OK.

**Comment by gdamiand** [comment] 2015-08-11 19:07
I did not find your branch (and this time I fetched cgal/public-dev). Are you sure you push it ?

**Comment by sloriot** [comment] 2015-08-12 06:44
It's [there](https://github.com/CGAL/cgal-public-dev/tree/CGAL_Qt5_Support_for_Mesa-GF).

**Comment by gdamiand** [comment] 2015-08-12 11:29
Demo of linear cell complex: seg fault (without any message).

Demo of T3, segfault with the following output:

QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
uniform highp mat4 mvp_matrix;
void main(void)
{
   gl_Position = mvp_matrix * vertex; 
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
uniform highp vec4 color; 
void main(void) { 
gl_FragColor = color; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
in highp vec3 normal;
in highp vec4 center;
uniform highp mat4 mvp_matrix;
uniform highp mat4 mv_matrix; 
out highp vec4 fP; 
out highp vec3 fN; 
void main(void)
{
   fP = mv_matrix * vertex; 
   fN = mat3(mv_matrix)* normal; 
   gl_Position = mvp_matrix * (vertex+vec4(center.xyz, 0.0)); 
} 
***
Compiling vertex source FAILED
QOpenGLShader::compile(Fragment): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Fragment shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 fP; 
in highp vec3 fN; 
uniform vec4 color; 
uniform highp vec4 light_pos;  
uniform highp vec4 light_diff; 
uniform highp vec4 light_spec; 
uniform highp vec4 light_amb;  
uniform float spec_power ; 
void main(void) { 
   vec3 L = light_pos.xyz - fP.xyz; 
   vec3 V = -fP.xyz; 
   vec3 N = normalize(fN); 
   L = normalize(L); 
   V = normalize(V); 
   vec3 R = reflect(-L, N); 
   vec4 diffuse = abs(dot(N,L)) * light_diff*color; 
   vec4 specular = pow(max(dot(R,V), 0.0), spec_power) * light_spec; 
gl_FragColor = color*light_amb + diffuse + specular; 
} 

 
***
Compiling fragmentsource FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::compile(Vertex): 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

*** Problematic Vertex shader source code ***
#version 330 
#define lowp
#define mediump
#define highp
in highp vec4 vertex;
in highp vec3 normal;
in highp vec4 transfo1;
in highp vec4 transfo2;
in highp vec4 transfo3;
in highp vec4 transfo4;
mat4 transfo = mat4(transfo1, transfo2, transfo3, transfo4); 
uniform highp mat4 mvp_matrix;
uniform highp mat4 mv_matrix; 
out highp vec4 fP; 
out highp vec3 fN; 
void main(void)
{
   fP = mv_matrix * vertex; 
   vec4 TN = transfo*vec4(normal,1.0); 
   fN = mat3(mv_matrix)* TN.xyz; 
   gl_Position =  mvp_matrix * transfo* vertex; 
} 
***
Compiling vertex source FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
linking Program FAILED
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
QOpenGLShader::link: "error: linking with uncompiled shadererror: linking with uncompiled shader" 
QOpenGLShaderProgram::attributeLocation( center ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( normal ): shader program is not linked 
QOpenGLShaderProgram::attributeLocation( vertex ): shader program is not linked 
Erreur de segmentation (core dumped)

**Comment by maxGimeno** [comment] 2015-08-12 11:38
According to your error messages, you don't have the right version. Are you
sure you compiles the demos from the branch "CGAL_Qt5_Support_for_Mesa-GF"
? It looks like "CGAL_Qt5_Support_GF".

2015-08-12 13:29 GMT+02:00 Guillaume Damiand <notifications@github.com>:

**Comment by gdamiand** [comment] 2015-08-12 15:44
You are right, I compiled the wrong branch.

Results: ok for T3 demo.

For LCC demo, I can run it now, but nothing is draw: for example create a cube, then the scene is empty but the cube is here as we can see by looking at the number of cells.

I have the following warning:

Warning, attribute "x" initialized to Not a Number in "position"
Warning, attribute "y" initialized to Not a Number in "position"
Warning, attribute "z" initialized to Not a Number in "position"


Does this demo is ok in your computer ??

**Comment by maxGimeno** [comment] 2015-08-13 06:34
Actually it works only sometimes on my machine... I'm investigating, but
your warnings get me worried, as the only thing in the code that seems to
be called "position" is a QVector4D containing hard coded floats.

2015-08-12 17:44 GMT+02:00 Guillaume Damiand <notifications@github.com>:

**Comment by maxGimeno** [comment] 2015-08-13 06:57
The bounding box was set before being computed. I think your warnings were
due to this somehow, as sometimes the bbox had NaN coordinates. You can try
again, it should work fine now.

2015-08-13 8:33 GMT+02:00 Maxime Gimeno <maxime.gimeno@gmail.com>:

**Comment by gdamiand** [comment] 2015-08-13 07:42
It works now, thanks.

A (last ?) problem: faces are transparency. Is it possible to make them fully opaque ?

**Comment by maxGimeno** [comment] 2015-08-13 09:58
The facets were never transparent on my computer, so I cannot comfirm what
I did solved the problem, but you can still try and tell me if it's ok with
my last push.

2015-08-13 9:42 GMT+02:00 Guillaume Damiand <notifications@github.com>:

**Comment by gdamiand** [comment] 2015-08-13 11:27
Still not ok

![capture du 2015-08-13 13 25 10](https://cloud.githubusercontent.com/assets/944526/9248766/f95ceafa-41be-11e5-8ca7-26f7531caa2a.png)

**Comment by maxGimeno** [comment] 2015-08-13 12:11
Okay, this is a depth-test problem. I pushed a fix, this time it should be ok !

**Comment by gdamiand** [comment] 2015-08-13 15:30
It's ok, thanks.

**Comment by lrineau** [comment] 2015-08-13 15:43
Thanks to both of you, Guillaume and Maxime, for having that issue solved.

Maxime, will the same be done for all CGAL 3D demos?

**Comment by maxGimeno** [comment] 2015-08-13 18:09
Theoritically, it is already done, but I can't be sure all works until
everything is tested by someone with these issues, as i can't test it
myself.

2015-08-13 17:43 GMT+02:00 Laurent Rineau <notifications@github.com>:

**Comment by lrineau** [comment] 2015-08-13 18:14
Simon, @sgiraudot, can you help test the rest with the Nouveau driver?

**Comment by sgiraudot** [comment] 2015-08-14 08:16
So far I did not have any trouble (the shader problem and depth problem were already solved for me in the CGAL-Qt5_support-GF branch.
I had the segfault issue when using a more recent version of Qt5 (5.4.2) so I downgraded it to 5.3.2 and it worked. I'll upgrade again to 5.4.2 to see if it now works without segfaulting.

**Comment by maxGimeno** [comment] 2015-08-14 12:54
Everything works fine on Simon's computer except LCC demo, for a weird and unknown reason, and Periodic_triangulation_3 because their is a problem with a SQLite driver or something and it won't compile.

**Comment by sgiraudot** [comment] 2015-08-14 13:13
For the Periodic_3_triangulation_3_demo, I managed to make it work by removing the test "TARGET Qt5::QSQLiteDriverPlugin" in the CMakeList. I have the libqt5sql5-sqlite package installed so I do not know why my cmake doesn't find it...

Anyway, the Periodic_3_triangulation_3_demo compiles and runs fine for me. So the only remaining problem is the segfault on the LCC demo which I am apparently the only one to have...

**Comment by bo0ts** [comment] 2015-08-17 15:03
> I have the libqt5sql5-sqlite package installed so I do not know why my cmake doesn't find it...

There are a bunch of bugs related to debian packaging and the Qt5 cmake files and dependencies. Try to check if you have the file `/usr/lib/i386-linux-gnu/cmake/Qt5Sql/Qt5SqlConfig.cmake` and maybe if you are affected by this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=729602

**Comment by lrineau** [comment] 2015-08-19 13:53
I will revert the commit CGAL/cgal-public-dev@156b267d85dd2f8a5d92c944716138a501c7cb44. In my opinion it is really wrong to depend on that specific QSql plugin. That is an undocumented implementation detail of the `qcollectiongenerator`, and  the Debian package should deal with it. It seems that `libqt5sql5-sqlite` is only "Recommended" by the package `qttools5-dev-tools`, while it should be `Required`.

There is a bug ["qttools5-dev-tools: libqt5sql5-sqlite should be a hard dependency"](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747716) in the Debian tracker, but it was rejected by the package maintainer:
> No, it has not been "mistakenly" marked as recommend: assistant is not
the only tool on qttools5-dev-tools, and it is the only one requiring
libqt5sql5-sqlite.
[...]
> In this case Recommends is what is typically used.  
Debian (and Ubuntu) install Recommends by default, so the only reason you 
wouldn't have Recommends installed too is if your system is in a non-standard 
configuration.  If so, that's the problem, not the package.

It seems the default installation of Qt5 on Debian/Ubuntu should have that plugin `qsqlite`.

**Closed** 2015-08-27 14:47 UTC
Labels: bug, Qt5
