### ISSUE TITLE
Several new pedantic warnings

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#4341] opened 2019-11-05 15:54 UTC
## Issue Details

<pre>
/home/vincent/workspace/CGAL/CGAL-5.0-beta2/include/CGAL/FPU.h: In function ‘__m128d CGAL::swap_m128d(__m128d)’:
/home/vincent/workspace/CGAL/CGAL-5.0-beta2/include/CGAL/FPU.h:279:47: warning: ISO C++ forbids compound-literals [-Wpedantic]
   return __builtin_shuffle(x, (__m128i){ 1, 0 });
                                               ^
</pre>
<pre>
/home/vincent/workspace/CGAL/CGAL-5.0-beta2/include/CGAL/Interval_nt.h:52:27: warning: ISO C++ forbids braced-groups within expressions [-Wpedantic]
 # define CGAL_CST_TRUE(X) ({ bool _ugly_ = (X); __builtin_constant_p(_ugly_) && _ugly_; })
                           ^
</pre>
<pre>
/home/vincent/workspace/CGAL/CGAL-5.0-beta2/include/CGAL/boost_mp.h:441:76: warning: extra ‘;’ [-Wpedantic]
 namespace internal { namespace boost_mp { BOOST_MPL_HAS_XXX_TRAIT_DEF(type); } }
                                                                            ^
</pre>
<pre>
/home/vincent/workspace/CGAL/CGAL-5.0-beta2/include/CGAL/NewKernel_d/Lazy_cartesian.h:136:71: warning: extra ‘;’ [-Wpedantic]
     Lazy_rep_XXX(Creator{},ac,ec,std::forward_as_tuple(ll...),ll...){};
</pre>

Removing `;` is easy. For the others, maybe adding `__extension__` would help. Anway, it is just pedantic, not very important.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): linux
* Compiler: gcc
* Specific flags used (if any): -Wpedantic
* CGAL version: 5.0-beta2

**Comment by lrineau** [comment] 2019-11-06 09:43
I assign this issue to you, @mglisse, because you seem the best person able to produce a pull-request quickly.

**Comment by sloriot** [comment] 2022-05-09 16:10
I cannot reproduce any of those warnings. Do you?

**Comment by sloriot** [comment] 2022-05-09 16:41
I could finally reproduce them.

**Closed** 2022-05-13 13:55 UTC
Labels: warnings, Pkg::Kernel_d, Pkg::Number_types, Has Pull Request
