### ISSUE TITLE
Linear_cell_complex:   ICE of GNU 12.0.1

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#6269] opened 2022-01-24 13:13 UTC
## Issue Details

All testsuites using the Linear_cell_complex fail, for example [this  one](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-4/Linear_cell_complex/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz).

```
CGAL/Linear_cell_complex_base.h:279:40: internal compiler error: in cp_parser_template_id, at cp/parser.cc:18367
  279 |     { return this->template attribute<0>(adart); }
```

## Environment

* Compiler: GNU 12.0.1
* maybe due to option `-std=c++1z`

**Comment by sloriot** [comment] 2022-01-24 13:15
More precisely
-- USING GCC_VERSION = '12.0.1 20220123 (experimental)'

**Comment by sloriot** [comment] 2022-01-24 13:17
While it semms fine with: '12.0.0 20220116 (experimental)'

**Comment by gdamiand** [comment] 2022-01-24 15:05
It looks like a compiler bug ? (since it compiles with 12.0.0 20220116 but not with 12.0.1 20220123)

**Comment by sloriot** [comment] 2022-01-24 15:08
It is, Andreas forgot to mention that it is an ICE.

**Comment by lrineau** [comment] 2022-01-24 15:59
Yes. For information, ICE stands for *internal compiler error*. ICEs are usually caused by strange or incorrect C++ code. But sometimes, that is just a plain bug, where the compiler crashes on a valid C++ code.

Anyway, ICEs are usually reported, because even if the code is invalid, the compiler should report an error message, instead of crashing.

**Comment by mglisse** [comment] 2022-01-26 00:21
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104235

**Comment by afabri** [comment] 2022-01-26 07:23
Thank you Marc. I am glad that the CGAL Project can serve as regression test for the GNU Project ==:>--

**Comment by lrineau** [comment] 2022-02-02 10:08
The issue was fixed upstream:
  - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104235 is marked as fixed,
  - by the commit https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=00d8321124123daf41f7c51526355a5a610cdeb8
  - and the testsuite is now OK: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-9/Linear_cell_complex/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz

**Comment by sloriot** [comment] 2022-02-02 10:19
It is stil here:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-9/BGL/TestReport_lrineau_Fedora-rawhide.gz
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-11/BGL/TestReport_lrineau_Fedora-rawhide.gz

**Comment by lrineau** [comment] 2022-02-02 10:24
@mglisse Indeed the error seems completely the same. Probably the code reduction in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104235 was a big too reduced.

But then I do not understand why those two results differ:
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-4/Linear_cell_complex/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-9/Linear_cell_complex/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz

It seems the new version of gcc did fix something.

**Comment by lrineau** [comment] 2022-02-02 10:34
Conclusion, as reported in https://github.com/CGAL/cgal/pull/6295#issuecomment-1027795486, that bug is already fixed in gcc, and we can see that in the platforms "Ubuntu-latest-GCC6" of our testsuite. And it will be fixed in Fedora-rawhide  as well next week, with the next version of our Docker containers.

**Closed by lrineau** 2022-02-02 10:34 UTC
Labels: not a bug, Pkg::Linear_cell_complex
