### ISSUE TITLE
to_interval_test.cpp without GMP or LEDA

### ISSUE THREAD

**Issue by mglisse** [CGAL/cgal#4318] opened 2019-10-26 19:21 UTC
## Issue Details

This test fails because CGAL/float.h and CGAL/int.h are not included. When GMP is present, it includes number_type_basic.h, which in turn includes those 2 files. I don't know (didn't think about it) if we should add the include(s) to the test or the library.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64
* Compiler: gcc-9
* Release or debug mode: debug
* Specific flags used (if any): -DCGAL_NO_GMP
* CGAL version: master

**Comment by lrineau** [comment] 2019-10-28 07:51
So far the API (including which headers should be included by user-code), is unclear to me.

**Comment by sloriot** [comment] 2024-08-13 09:02
The issue is fixed in CGAL-6.0-beta. I changed the milestone as I don't think it needs to be backported.

**Closed by sloriot** 2024-08-13 09:02 UTC
Labels: Bug, Pkg::Number_types
