### ISSUE TITLE
Win x64 specific: ImageIO or CGAL interface does not read .inr image correctly

### ISSUE THREAD

**Issue by keydawg** [CGAL/cgal#259] opened 2015-08-06 16:19 UTC
The type of code I've been using on CGAL 4.0 (worked perfectly fine) does not return the correct answer any more. To simplify a bit this is what I was able to rectify the problem down to. I think because of this my next steps of generating the mesh does not work as well:
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Mesh_triangulation_3.h>
#include <CGAL/Mesh_complex_3_in_triangulation_3.h>
#include <CGAL/Mesh_criteria_3.h>

#include <CGAL/Labeled_image_mesh_domain_3.h>

#include <CGAL/make_mesh_3.h>
#include <CGAL/Image_3.h>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef CGAL::Labeled_image_mesh_domain_3<CGAL::Image_3,K> Mesh_domain;

using namespace std;

int main()
{
       CGAL::Image_3 image;
       image.read("input.inr"); // does not work with either .inr or .hdr and .img
       cout << image.vx () << "; " << image.vy () << "; " << image.vz () << "\n"; // This is correct
       cout << image.xdim () << "; " << image.ydim () << "; " << image.zdim () << "\n"; // THIS IS NOT!
       return 0;
}
```
Compiling and running on Windows. CGAL 4.6.1

Thanks!

**Comment by sloriot** [comment] 2016-07-07 12:32
Sorry for the very late reply. Do you still have the file?

**Comment by sgiraudot** [comment] 2016-08-09 16:06
@keydawg As @sloriot asked, can you provide the file?

If not, I will close the issue.

**Comment by sgiraudot** [comment] 2016-10-28 05:53
Without the file, we cannot reproduce the issue. I am closing it, please open another one if you find this bug again and can provide an example file.

**Closed by sgiraudot** 2016-10-28 05:53 UTC
Labels: bug, waiting for answer
