### ISSUE TITLE
Broken link in references

### ISSUE THREAD

**Issue by imiordanov** [CGAL/cgal#1908] opened 2017-02-16 13:18 UTC
## Issue Details

The link for reference [4] in the Bibliographic References for the Number Types seems to be broken. 
Verify here: http://doc.cgal.org/latest/Number_types/citelist.html

The correct link should be this one: http://www.algorithmic-solutions.info/leda_manual/manual.html

## Environment

Documentation

**Comment by lrineau** [comment] 2017-03-07 14:10
Thanks for reporting. The issue is now fixed in our `master` branch (see the PR #1910).

**Closed by lrineau** 2017-03-07 14:10 UTC
Labels: doc bug
