### ISSUE TITLE
CMake installed package is no longer relocatable

### ISSUE THREAD

**Issue by Klusting** [CGAL/cgal#4433] opened 2019-12-24 04:49 UTC
## Issue Details

When the package generated by `cmake install` is moved to another place, `find_package(CGAL REQUIRED)` would fail with `Found package configuration file but it set CGAL_FOUND to FALSE so package "CGAL" is considered to be NOT FOUND.`

It turns out that `CGAL_ROOT` is set to a hard-coded path at configure step in `CGALConfig-installation-dirs.cmake`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10 64 bit
* Compiler: Visual Studio Community 2019
* Release or debug mode: release
* Specific flags used (if any): 
* CGAL version: 5.0
* Boost version: 1.70.0
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.7

**Comment by lrineau** [comment] 2020-01-07 12:03
You are right. It is since PR https://github.com/CGAL/cgal/pull/4285.

Do you a solution? I did that PR after the publication of CGAL-5.0-beta2 has shown issues on Debian. How can the file `CGALConfig.cmake` retrieve all the parts of CGAL?

**Comment by sloriot** [comment] 2020-01-07 12:13
Is it really an issue? If you provided an installation prefix why would you move it afterwards?

**Comment by lrineau** [comment] 2020-04-15 20:53
I still do not have spend enough time to search for a solution. Does anybody have one?

**Comment by sloriot** [comment] 2020-04-16 07:57
I probably did not understand the issue and you did not answer to my previous question so I cannot really help :(

**Comment by lrineau** [comment] 2020-04-16 08:37
I thought it was a question to the OP @Klusting.

A relocatable CMake package is [defined in the CMake manual](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-relocatable-packages). That is mnice-to-have property of CMake package, and if CGAL was relocatable previously, then it is a regression.

Relocatable package are not only nice-to-have, but that also avoid errors for users and maintainers. The issues Maxime is having with the Boost package version1.72 is that the CMake installation is not correctly relocatable.

**Comment by lrineau** [comment] 2020-07-28 11:31
This issue is at least fixed in CGAL-5.1-beta2. It will be also fixed in 4.14.4 once it is released.

**Closed by lrineau** 2020-07-28 11:31 UTC
Labels: CMake scripts, Has Pull Request, bug

**Comment by a-gn** [comment] 2022-08-02 07:47
> This issue is at least fixed in CGAL-5.1-beta2. It will be also fixed in 4.14.4 once it is released.

Hi, was there ever a 4.14.4 release with relocatable install? Our code isn't compatible with 5.x and we need to relocate the CGAL install for our CI/CD pipeline.

**Comment by PotatoEt** [comment] 2024-09-10 08:32
try to use  `cmake -DCGAL_DIR="/usr/lib/x86-64-linux-gnu/cmake/CGAL" ..`
