### ISSUE TITLE
bug with linear_least_squares_fitting_3() ?

### ISSUE THREAD

**Issue by hugoledoux** [CGAL/cgal#2676] opened 2017-12-11 14:30 UTC
## Issue Details

The function linear_least_squares_fitting_3() does not behave as it should, I believe. See a small example:
https://gist.github.com/hugoledoux/08bde5bf82a5aef7398b5a8d53b2c61b

I first define 5 points in 3D, then fit a plane through the first 3, and finally calculate distance from each point to the plane. All distances <1cm and thus we can say the plane is planar.

After that I fit a plane with least-square with the same points, and calculate the distances: ~1.5m for a few, while the plane is planar!

More worryingly, if I define only 3 points (last example in my CPP), and use least-square then the distances are also 1.5m... Observe that not all 3 points give this result, I tried with simple examples and it works fine (eg distances are 0m, as it should be). Someone using my program based on CGAL for several of these tests (https://github.com/tudelft3d/val3dity) said this happens "when there are super long surfaces". A precision issue?

## Source Code

https://gist.github.com/hugoledoux/08bde5bf82a5aef7398b5a8d53b2c61b

## Environment
 
macOS 10.13.1 

with v4.11 installed with brew
$ brew info cgal
cgal: stable 4.11 (bottled)
Computational Geometry Algorithm Library

**Comment by sgiraudot** [comment] 2017-12-11 15:17
I can't seem to reproduce your bug. Using CGAL 4.11, I get:

```
collinear= 0
plane= -107.932 -413.802 565.784 294927
dist= 6.15546e-14
dist= 2.05182e-14
dist= 4.10364e-14
dist= 0.00504542
dist= 0.00845212
lq-plane= -0.152458 -0.584439 0.796987 416.993
dist= 0.00314225
dist= 0.00313344
dist= 0.000944076
dist= 0.00413228
dist= 0.00319702
lq-plane-3-pts= -0.152185 -0.583462 0.797754 415.849
dist= 6.32177e-06
dist= 6.49187e-06
dist= 1.70105e-07
dist= 0.00504567
dist= 0.00843927
==========
```

PCA is based on computation of eigenvalues which use imprecise double float numbers, which explains why the 3 point planes is not as precise in the last case than in the first (in the first, as you define the plane directly with the 3 points, there is no eigenvalue computation, they are used directly to create the equation of the plane).

For the other values, unless there is something I did not understand from your explanations, I don't see what is the problem.

**Comment by hugoledoux** [comment] 2017-12-11 15:27
huh, this is interesting. Your results are indeed as they should. 

I get the following:
```
$ ./test
collinear= 0
plane= -107.932 -413.802 565.784 294927
dist= 6.15546e-14
dist= 2.05182e-14
dist= 4.10364e-14
dist= 0.00504542
dist= 0.00845212
lq-plane= 0.00427973 -0.00114317 0.99999 -210.582
dist= 1.48895
dist= 1.48096
dist= 0.983124
dist= 0.977366
dist= 1.95249
lq-plane-3-pts= 0.0108836 -0.00301311 0.999936 -210.96
dist= 1.48419
dist= 1.48505
dist= 0.000862636
dist= 0.0155402
dist= 2.94467
==========
```

and I tested on other machines:
- 2 other of my colleagues using also 4.11 from Homebrew; 
- I just tried on a Ubuntu 16.04 machine with CGAL 4.7
and all same wrong results.

What did you use? 

My CMake? I used `cgal_create_cmake_script`

**Comment by sgiraudot** [comment] 2017-12-11 15:37
Ok, I think I figured out why my results are different: I'm using CGAL with the [Eigen library](http://eigen.tuxfamily.org/index.php?title=Main_Page), which provides much more precise results (see [the doc of the function](https://doc.cgal.org/latest/Principal_component_analysis/group__PkgPrincipalComponentAnalysisDLLSF3.html#gadcf556c115c6bac30a54bf7fdd0d32e3)).

Eigen is open source and quite easy to add (header only), so I would advise you to use it if possible.

**Comment by hugoledoux** [comment] 2017-12-11 16:06
yes, that works! Although I still find this somewhat of a bug, or at least the doc should be updated to warn others? I mean, it's not a precision issue here (is it?), I get 1.5m away, while it should be like a few millimeters.

I fiddle to find how to activate this, so for others and future reference:
1. `brew reinstall cgal --with-eigen`
2. in `CMakeLists.txt`

```
project( cgal_ )
cmake_minimum_required(VERSION 2.8.10)
set(CMAKE_CXX_STANDARD 14)
find_package(CGAL QUIET COMPONENTS Core )
if ( CGAL_FOUND )
  include( ${CGAL_USE_FILE} )

  find_package(Eigen3)
  include( ${EIGEN3_USE_FILE} )  

  include( CGAL_CreateSingleSourceCGALProgram )
  create_single_source_cgal_program( "test1.cpp" )
else()
      message(STATUS "This program requires the CGAL library, and will not be compiled.")
 endif()
```

the Eigen commands should come *after* the include(CGAL) otherwise it's ignored.

**Comment by sgiraudot** [comment] 2017-12-21 13:31
I made some additional tests. So it is indeed a precision issue: in your case, the precision loss is indeed quite high (if you display the plane, it's not a completely wrong random plane, but it's clearly very imprecise). I found that there was a hard-coded `static const FT EPSILON = (FT)0.00001;` in the fallback solver that controls the precision of the computation. Decreasing it allows to get the correct precise result (but it takes longer).

For information, this fallback mode is a very old code (inherited from Fortran if I'm not mistaken) that used to be the only diagonalization code we had in CGAL before we started using Eigen. There has already been debates about whether or not we should keep it or just rely on Eigen: the reason we keep it can be useful for people who, for some reason, can't/won't use Eigen, but as you saw, it's not really good…

Anyway, I think this bugs shows that we should probably be more careful with it. At least not use it as default…

I'm closing the issue as I think your bug is solved and I'll start a discussion with the developers to see how to handle this in future releases. Thanks for the report!

**Closed by sgiraudot** 2017-12-21 13:31 UTC
Labels: bug

**Comment by hugoledoux** [comment] 2017-12-21 14:43
Cheers for the update.

My code is indeed fixed, installing/compiling Eigen ain't that difficult (although under Ubuntu apt-get gives you CGAL w/o Eigen, and one needs to recompile it, which I find annoying), but indeed I'd propose you enforce Eigen, and if not a big warning in the doc.
