### ISSUE TITLE
New warning in CMake-3.10 (ArchLinux)

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#2293] opened 2017-07-24 15:06 UTC
## Issue Details

Cmake-3.10 introduces a new policy [`CMP0071`][*]

  [*]: https://cmake.org/cmake/help/git-master/policy/CMP0071.html

In the following files we use `AUTOMOC`:
```
AABB_tree/demo/AABB_tree/CMakeLists.txt
Alpha_shapes_3/demo/Alpha_shapes_3/CMakeLists.txt
Linear_cell_complex/demo/Linear_cell_complex/CMakeLists.txt
Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/CMakeLists.txt
Polyhedron/demo/Polyhedron/CMakeLists.txt
Surface_mesher/demo/Surface_mesher/CMakeLists.txt
Three/demo/Three/Example_plugin/CMakeLists.txt
Triangulation_3/demo/Triangulation_3/CMakeLists.txt
```
Those files will require
```cmake
if(POLICY CMP0071)
  cmake_policy(SET CMP0071 NEW)
endif()
```

to disable the warning.

The warnings can be seen at https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-I-74.shtml in the `ArchLinux` columns, in the corresponding `_Demo` lines.

**Comment by MaelRL** [comment] 2017-08-02 10:20
Duplicate of #2318.

**Closed by MaelRL** 2017-08-02 10:20 UTC
Labels: CMake scripts, warnings
