### ISSUE TITLE
Doxygen fails to expand a type

### ISSUE THREAD

**Issue by efifogel** [CGAL/cgal#5154] opened 2020-11-11 10:01 UTC
## Issue Details

I have a class, say A, that inherits from B::C.
Doxygen generates documentation that says that A inherits from C.
For some reason doxygen drop the "B::" part.

In the Arrangement_on_surface_2 class template we define the nested class Face, which derives from Dcel::Face. The generated manual says that "Face inherits from Face", which is ridiculous.
See, e.g., [https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__2_1_1Face.html](https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__2_1_1Face.html)

![image](https://user-images.githubusercontent.com/6952632/98803185-0adf7400-241d-11eb-8606-e8a361598cfb.png)

I'm using the Doxygen version that is adopted for CGAL, revision 1.8.14.

## Source Code

```
template <typename GeometryTraits, TopologyTraits>
class Arrangement_on_surface_2 {
public:
  typedef typename TopologyTraits::Dcel    Dcel;
  class Face : public typename Dcel::Face { ...  };
};
```

## Environment

* Operating system: Linux 64 bits
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: Latest
* Boost version: 
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by albert-github** [comment] 2020-11-11 10:13
- is this problem in the CGAL documentation, if so where? (please specify filename and html file name)
- is this problem also present in the overnight master build or when not in in the CGAL documentation what happens when you use the current release of doxygen (1.8.20) or doxygen master?

**Comment by efifogel** [comment] 2020-11-11 10:20
- This bug produces wrong documentation for CGAL. 
It seems that I've dropped the link in the original submission. Anyhow, here it is:
[https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__2_1_1Face.html](https://doc.cgal.org/latest/Arrangement_on_surface_2/classCGAL_1_1Arrangement__2_1_1Face.html)

- I don't know whether it also present in other releases of doxygen, but Sebastien has been able to reproduce. (Perhaps he is using a version different than mine.)

**Comment by albert-github** [comment] 2020-11-11 10:28
@efifogel the link you mailed is for the 1.8.13 version of doxygen. Probably @sloriot did have a look at the overnight build as well, and I see the problem there in https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.2-Ic-48/master/Arrangement_on_surface_2/classCGAL_1_1Arrangement__2_1_1Face.html as well.

( @efifogel  maybe edit the original issue and add the your link there as well and a small image of what you see that is wrong).

**Comment by efifogel** [comment] 2020-11-11 10:39
I've edited the original text. (I think the problem is rather obvious...)

**Comment by albert-github** [comment] 2020-11-11 10:47
@efifogel for the writer a problem might be obvious, at the moment, but later on it might even be a bit unclear for the writer (happens to me sometimes and at that moment I think what did I intend), also for a person reading the issue it might not directly be clear. Furthermore when the source code or the doxygen version would change it might be not that clear anymore either. Therefor the more, relevant, information the better.
(Disclaimer: I know these remarks are beyond the scope of the issue and are just some general remarks).

**Comment by efifogel** [comment] 2020-11-11 10:55
ok, no problem. I've added an image.

**Comment by sloriot** [comment] 2020-11-12 08:08
I've tried with doxygen master and could reproduce the issue. I think doxygen is trying to expend the inherited type and somehow gets confused at some point. I tried with a nested class Dcel having itself a Face type and the output was correct. Even after fixing the internal Dcel typedef shadowing the template parameter, the issue remains. I tried to produce a self-contained example but I was not able to configure doxygen to have the "inherits", I could only have the graph...

**Comment by albert-github** [comment] 2020-11-12 09:04
@sloriot In the default version I tried I set (and further a complete default Doxyfile):
```
CLASS_DIAGRAMS         = NO
```

I think the problem lies indeed in the fact that there was nowhere a `Dcell::Face` to be found. Most likely it would be nicer when doxygen would output the full qualified name and not just `Face`.

**Comment by sloriot** [comment] 2020-11-12 09:59
Thanks. See  https://github.com/doxygen/doxygen/issues/8172

**Comment by Deepak-suresh14** [comment] 2020-12-10 15:34
I am new to doxygen can you help me out

**Comment by Apatidar0901** [comment] 2023-01-27 18:00
Hello everyone, 
I would like to work on it.
Please assign it to me.

**Comment by albert-github** [comment] 2023-01-27 19:04
I just did a quick check with the current master (1.9.7 (aed5276eb131252a6d4eaf4b00ee145127541f1f) of doxygen and it looks like the problem is solved for the small as given with the doxygen issue (https://github.com/doxygen/doxygen/issues/8172).
(looks like a side effect of some other changes).

@sloriot , @efifogel can you confirm that the problem is solved?

**Comment by sloriot** [comment] 2023-01-30 07:45
Fixed: See https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.6-I-167/master/Arrangement_on_surface_2/classCGAL_1_1Arrangement__on__surface__2_1_1Face.html

**Closed by sloriot** 2023-01-30 07:45 UTC
Labels: doc, doc bug
