### ISSUE TITLE
Uninitialized member in No_intersection_surface_sweep_2

### ISSUE THREAD

**Issue by dpapavas** [CGAL/cgal#5797] opened 2021-06-22 18:49 UTC
Valgrind complains that [this conditional statment](https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/Surface_sweep_2/include/CGAL/Surface_sweep_2/Surface_sweep_2_impl.h#L436) can be reached with `m_currentEvent` still uninitialized.

I'm not familiar with the inner workings of the code, but from a quick glance, it seems that `m_currentEvent` is only set [here](https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/Surface_sweep_2/include/CGAL/Surface_sweep_2/No_intersection_surface_sweep_2_impl.h#L145), but, besides the fact that the loop may not execute at all, it seems that the uninitialized jump can also take place before this loop is reached at all (i.e. it's not just a matter of the case of `m_queue` being empty).

Anyway, I've tried the quick test of adding `m_currentEvent(NULL)` to the member initializer list of the constructors of `No_intersection_surface_sweep_2` and the errors go away (with the program still running fine), but I have no idea whether this is the correct fix.  If it is, and you want me to make a PR, of if you need a test case, let me know.

**Comment by lrineau** [comment] 2021-06-30 08:02
Hi Dmitris, can you please provide more details so that we can easily reproduce? Please share your C++ code and data set (if any) to reproduce.

I am not fond of valgrind, but that bug may also be detected by MemorySanitizer.

**Comment by sloriot** [comment] 2021-07-01 06:14
I confirm that `m_currentEvent(NULL)` is a valid fix. I could reproduce the usage of the non-initialized value. Fixed in #5821.

Thanks for the report!

**Comment by dpapavas** [comment] 2021-07-01 16:24
I was just about to put together a minimal example to reproduce the problem.  Thanks for the swift fix!

**Comment by dpapavas** [comment] 2021-08-30 19:45
I stumbled across this issue again and noticed that the fix  doesn't seem to be merged into the latest source tree.  The issue itself is still open, while the relevant PR (#5821) seems to be closed, but not merged.  It's no big deal for me; just thought I'd mention it, in case it has slipped though the cracks.

**Comment by lrineau** [comment] 2021-08-31 06:32
You are right. I understand what happened: the PR was closed forcibly when I closed the branch `5.1.x-branch`. ... That is my fault: for those pull-requests based on 5.1.x, I remembered to change the milestone, but not the base branch of it. There might be other pull-requests with the same situation. I will have a look.

**Comment by lrineau** [comment] 2021-08-31 06:49
> You are right. I understand what happened: the PR was closed forcibly when I closed the branch `5.1.x-branch`. ... That is my fault: for those pull-requests based on 5.1.x, I remembered to change the milestone, but not the base branch of it. There might be other pull-requests with the same situation. I will have a look.

There are three of them. Here is the right query: https://github.com/CGAL/cgal/pulls?q=is%3Apr+is%3Aclosed+is%3Aunmerged+base%3A5.1.x-branch+sort%3Aupdated-desc+closed%3A2021-07-06

I take a screenshot, because that list will change once I operate on them:
> ![Screenshot_20210831_084714](https://user-images.githubusercontent.com/5746675/131455476-589fbbd0-04f2-403d-ad8e-b977207363a3.png)

**Comment by lrineau** [comment] 2021-08-31 06:55
> > You are right. I understand what happened: the PR was closed forcibly when I closed the branch `5.1.x-branch`. ... That is my fault: for those pull-requests based on 5.1.x, I remembered to change the milestone, but not the base branch of it. There might be other pull-requests with the same situation. I will have a look.
> 
> There are three of them. Here is the right query: [CGAL/cgal/pulls (is:closed is:unmerged base:5.1.x-branch sort:updated-desc closed:2021-07-06)](https://github.com/CGAL/cgal/pulls?q=is%3Apr+is%3Aclosed+is%3Aunmerged+base%3A5.1.x-branch+sort%3Aupdated-desc+closed%3A2021-07-06)

That is "fixed" now: all three pull-requests have been reopened, and re-assigned to the branch `5.2.x-branch`.

**Closed** 2021-09-10 15:41 UTC
Labels: bug, Has Pull Request, Pkg::Surface_sweep_2
