### ISSUE TITLE
postcondition violation in ch_akl_toussaint_impl.h line 337: is_ccw_strongly_convex_2( res.output_so_far_begin(), res.output_so_far_end(), ch_traits)

### ISSUE THREAD

**Issue by quirxi** [CGAL/cgal#2631] opened 2017-11-25 14:03 UTC
_Please use the following template to help us solving your issue._

## Issue Details

Whenever i try to preview/render a certain scad script in openscad (OpenSCAD version 2015.03-2 ) the application crashes with follwowing output on the console:
```
$ openscad hull_minkowski-test.scad 
CGAL error: postcondition violation!
Expression : is_ccw_strongly_convex_2( res.output_so_far_begin(), res.output_so_far_end(), ch_traits)
File       : /usr/include/CGAL/Convex_hull_2/ch_akl_toussaint_impl.h
Line       : 337
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
Abgebrochen
```
## Environment

* Operating system: Debian Stretch 9.2 (64 bit)
* Release or debug mode: /usr/lib/x86_64-linux-gnu/libCGAL.so.12.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=42a3c9ffaa53d13d483a7585604ee3ced1ba0242, stripped
* CGAL version: libcgal12   4.9-1+b2
* Boost version: 1.62.0.1

## Piece of code that triggers bug in openscad file:

```
hull()
{
    rotate([0,90,0]) circle(50);
    translate([-50,0,0]) rotate([0,90,0]) square(50, true);
}
```

**Comment by sloriot** [comment] 2017-11-27 08:00
If you are applying a rotation to a convex hull with a kernel with inexact construction, the output is not guarantee to be a valid convex hull anymore. @kintel, does this answer make sense?

**Comment by kintel** [comment] 2017-11-27 14:20
@sloriot Note: There is no rotation applied after the convex hull was built. The issue seems to be that while the convex hull itself is stable with this kernel, the postcondition check isn't.

This is a duplicate of #1703.

**Comment by sloriot** [comment] 2017-11-27 14:38
Ah I see, this is a pb due to the usage of inexact predicates. Thanks @kintel.

**Closed by sloriot** 2017-11-27 14:38 UTC
