### ISSUE TITLE
random_polygon_2 goes into infinite loop for some point input sequences

### ISSUE THREAD

**Issue by bobergj** [CGAL/cgal#2585] opened 2017-11-08 12:44 UTC
## Issue Details

CGAL::random_polygon_2  goes into an infinite loop for some point input sequences.
It occurs both with an exact kernel (Exact_predicates_exact_constructions_kernel), and with Simple_cartesian.

The infinite loop occurs in random_polygon_2.h in the call to:
```
make_simple_polygon(vertices.begin(), vertices.end(), traits);
```

### Sample input sequences triggering the bug:

Point_2D X Y:
```
0 1
2 2
2 1
3 1
```

```
0 1 
2 0
1 1
2 1
```

```
1 3 
1 0
1 1 
1 2
```

I believe it happens because there are coplanar points in the input sequence.

random_polygon_2 throwing an exception or failing with an empty output sequence would be acceptable, or at least preferable to the infinite loop.
It's desirable to be able to generate polygons with coplanar points though..

## Source Code

Gist with minimal sample code (-std=c++11):
https://gist.github.com/bobergj/7d13865080e923b7017f4761358828ce

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOS Sierra 10.12.6, 64 bits
* Compiler: Apple LLVM version 9.0.0 (clang-900.0.38)
* Release or debug mode: Both
* Specific flags used (if any):
* CGAL version: 4.11 built from source. 
* Boost version: 1.59.0_3 (macports)
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MaelRL** [comment] 2017-11-08 13:25
Possible duplicate of https://github.com/CGAL/cgal/issues/1445.

**Closed** 2021-04-17 09:00 UTC
Labels: Has Pull Request, Pkg::Generators, bug
