### ISSUE TITLE
warning: 'align'  attribute directive ignored

### ISSUE THREAD

**Issue by chaffra** [CGAL/cgal#382] opened 2015-10-01 22:10 UTC
Hi,

When building on MinGW 64 bit I am getting the following warning. Can this be an issue on MinGW? I configured with `cmake -G"MSYS Makefiles" -DBUILD_SHARED_LIBS:BOOL=OFF ..`
```
cgal/Number_types/include/CGAL/double.h:135:5: warning: 'align'
 attribute directive ignored [-Wattributes]
   } absMask = {0x7fffffffffffffff, 0x7fffffffffffffff};
     ^
```

**Comment by lrineau** [comment] 2015-10-16 10:37
That is unfortunate. Can you try to modify the code in `<CGAL/ss2.h>`?
```C++
#if defined ( _WIN32 )
#define CGAL_ALIGN_16  __declspec(align(16))
#elif defined( __GNUC__ ) || defined(__MINGW64__)
#define  CGAL_ALIGN_16 __attribute__((aligned(16))) 
#endif
```
MinGW is not tested or supported by the CGAL project. That is why we cannot know exactly what the code should be.

**Comment by etrinh** [comment] 2015-11-17 10:42
The issue is still there as Mingw also define _WIN32.

Maybe better to select by compiler as _declspec(align seems specific to Visual Studio
So something like this works:
#if defined ( _MSC_VER )
#define CGAL_ALIGN_16  __declspec(align(16))
#elif defined( __GNUC__ )
#define  CGAL_ALIGN_16 __attribute__((aligned(16))) 
#endif

**Comment by sgiraudot** [comment] 2016-08-10 09:08
I am currently reviewing all CGAL issues and I'd like to know if we can fix this one.

@etrinh Can you confirm that your fix still works with Mingw? We'll still have to check if this doesn't modify the behavior on other platforms, and if it doesn't we should include it into CGAL.

**Comment by lrineau** [comment] 2016-08-10 10:12
The patch looks good. If a PR is tested and the CGAL testsuite does not show errors, I would integrate it.

In the longer term, we should have a MinGW column in our testsuite.

**Comment by sgiraudot** [comment] 2016-08-10 10:25
Okay, I will take care of this.

**Comment by afabri** [comment] 2016-08-10 20:24
Does mingw have boost gmp mpfr out of the box?
If not I think we have not enough users on mingw to justify such a testsuite

**Comment by sgiraudot** [comment] 2016-08-11 12:44
I don't know about that, but anyway this fix doesn't cost us anything.

It has passed the testsuite and is merged in CGAL, I'm closing this issue.

**Closed by sgiraudot** 2016-08-11 12:44 UTC
Labels: warnings

**Comment by lrineau** [comment] 2016-08-11 13:22
On Windows, MinGW uses the same C libraries as Visual Studio. Now that we no longer use Boost compiled libraries, the GMP and MPFR shipped with the Windows installer are sufficient. Those shipped libraries were actually compiled with the MinGW compiler.



Le 10 août 2016 22:24, à 22:24, Andreas Fabri <notifications@github.com> a écrit:
