### ISSUE TITLE
bug in Two_vertices_parameterizer_3.h

### ISSUE THREAD

**Issue by jiabinliang** [CGAL/cgal#2563] opened 2017-10-27 08:11 UTC
## Issue Details
runtime error
given a mesh with only one triangle 
-27.9902 8.96537 -36.5647
-27.9902 8.96613 -36.5647
-27.9901 8.96704 -36.5647
parameterize it with Square_border_arc_length_parameterizer_3 and LSCM_parameterizer
-> crash, using null pointer

bug is in:
Two_vertices_parameterizer_3.h:135-137
in 131-149 we suppose to find the bounding box of the mesh.
so  xmax should be initialize as -inf(std::numeric_limit<double>lowest),
but cgal is using numeric_limite<double>::min
which is the minimal positive value of double, epsilon. close to 0
so at the end xmax =0, (it like we extend bbox with 0,0,0)
then cgal chose Z then X as axis
as we all have the same Z, so all vertex will paramterized as u=0

then in line:230,232, again, using min instead of lowest
umax is epsilon now
we never enter if in line:255(u=0<epsilon)
vxmax is empty. crash in line 262

 

* Operating system (Windows/Mac/Linux, 32/64 bits):win64
* Compiler:MSVC
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version:4.10, also in 4.11
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by lrineau** [comment] 2017-10-27 08:47
@palliez: That is a bug in Surface_mesh_parameterization, and the reporter @jiabinliang has already found out the bug and the patch.

Note that [`std::numeric_limits<T>::lowest`] is C++11.
I suggest to use [`- std::numeric_limits<T>::infinity`] (negation of infinity) instead.

[`std::numeric_limits<T>::lowest`]: http://en.cppreference.com/w/cpp/types/numeric_limits/lowest
[`- std::numeric_limits<T>::infinity`]: http://en.cppreference.com/w/cpp/types/numeric_limits/infinity

**Comment by afabri** [comment] 2017-10-27 08:54
@MaelRL can you please fix this

**Comment by MaelRL** [comment] 2017-10-27 08:57
Can reproduce and changing the bound does fix it.

I haven't opened a PR yet because there are other places that seem to have the same issue, like:
* https://github.com/CGAL/cgal/blob/master/Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h#L628
* https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example.cpp#L18

and a bunch more.

Also, the structure of the SMP package changed with v4.11 and the different wrong uses of `::min()` did not arrive with the same version. So, single PR or split into different PRs ?

**Comment by lrineau** [comment] 2017-10-27 09:22
You can start with a PR for 4.10, and another one for 4.11, where you merge the branch of the PR for 4.10.

**Comment by MaelRL** [comment] 2017-11-03 13:41
Fixed by #2564 and #2565.

@jiabinliang Thanks for the report and for debugging the issue.

**Closed by MaelRL** 2017-11-03 13:41 UTC
Labels: bug, Pkg::Surface_mesh_parametrization
