### ISSUE TITLE
How to determine if a vertex or facet is output?

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#5842] opened 2021-07-08 14:11 UTC
Dear Developers
I have a question, which I will explain below with an example. 
When I use the function "clip()" to clip the mesh, I can get half of the mesh. How to determine which vertices and facets are output and which are not in the mesh in CGAL.  Are the vertices or facets marked, and if so, how do I get those marks.

**Comment by sloriot** [comment] 2021-07-08 14:35
somehow duplicate of https://github.com/CGAL/cgal/issues/5835 for the vertex part. https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html  can be used for the face part.

**Closed** 2021-07-21 10:38 UTC
Labels: Pkg::PMP, question
