### ISSUE TITLE
Algebraic curve y^a = 0 insertion crash

### ISSUE THREAD

**Issue by zhoutianyu16tue** [CGAL/cgal#2224] opened 2017-07-03 09:20 UTC
## Issue Details
When trying to insert an y^a = 0 (a >= 2) algebraic curve into a 2D arrangement, the program will
crash. This is an issue found during the development of 2D arrangement demo.

## Source Code

    #include <CGAL/basic.h>
    #include <iostream>
    #if (!CGAL_USE_CORE) && (!CGAL_USE_LEDA) && (!(CGAL_USE_GMP && CGAL_USE_MPFI))
    int main ()
    {
      std::cout << "Sorry, this example needs CORE, LEDA, or GMP+MPFI ..." 
            << std::endl; 
      return 0;
    }
    #else
    #include <CGAL/Arrangement_2.h>
    #include <CGAL/Arr_algebraic_segment_traits_32/2.h>
    #if CGAL_USE& CGAL_USE_MPFI
    #include <CGAL/Gmpz.h>
    typedef CGAL::Gmpz Integer  #elif CGAL_USE_  #include <CGAL/CORE_BigInt.h>
    typedef CORE::BigInt Integer;
    #else
    #include <CGAL/leda_integer.h>
    typedef LEDA::integer Integer;
    #endif
    typedef CGAL::Arr_algebraic_segment_traits_2<Integer> Arr_traits_2;
    typedef CGAL::Arrangement_2<Arr_traits_2> Arrangement_2;
    typedef Arr_traits_2::Curve_2 Curve_2;
    typedef Arr_traits_2::Polynomial_2 Polynomial_2;
    int main() {
        // For nice printouts
        CGAL::set_pretty_mode(std::cout);
        Arr_traits_2 arr_traits;
     
        // Functor to create a curve from a Polynomial_2
        Arr_traits_2::Construct_curve_2 construct_curve
            = arr_traits.construct_curve_2_object();
        Polynomial_2 x = CGAL::shift(Polynomial_2(1),1,0);
        Polynomial_2 y = CGAL::shift(Polynomial_2(1),1,1);
      
        Arrangement_2 arr(&arr_traits);

        Polynomial_2 f8 = CGAL::ipower(y, 2);

        Curve_2 cv8 = construct_curve(f8);
        std::cout << "Adding curve " << cv8.polynomial_2() << " to the arrangement" << std::endl;
        CGAL::insert(arr,cv8);

        // Print the arrangement size.
        std::cout << "The arrangement size:" << std::endl
                  << "   V = " << arr.number_of_vertices()
                  << ",  E = " << arr.number_of_edges() 
                  << ",  F = " << arr.number_of_faces() << std::endl;
        
        return 0;
    }
    #endif

## Environment

* Operating system (Mac , 64 bits):
* Compiler: clang
* Release or debug mode:
* Specific flags used (if any):
* CGAL version: 4.9
* Boost version: 1.63.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by efifogel** [comment] 2017-07-10 10:50
Hi Eric,

It seems that there is a bug when inserting an algebraic curve into an
arrangement.
The code fails on simple polynomials, e.g.,
x^2 = 0, or
y^2 = 0

It doesn't fail, though, when inserting
x = 0, or
y = 0

Would you like to take a look or perhaps ask M. Kerber?

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment] 2017-11-15 18:37
@sloriot @efifogel Any update?

**Comment by lrineau** [comment] 2018-01-19 15:59
This issue has not been updated since last summer.

@ericberberich @efifogel?

**Comment by sloriot** [comment] 2020-04-22 11:50
@akobel were you involved in that package?

**Comment by akobel** [comment] 2020-04-23 10:10
@sloriot Kind of.

Two possible interpretations: either it's not a bug (Curve_analysis_2 requires square-free input, see Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_analysis_2.h:301), but just lacks a sane error handling. The input here is clearly not square-free.
(I hope I caught the OP's problem; the example from the bug report doesn't compile as-is.)

Or it's a bug, since Algebraic_curve_kernel_2::Construct_curve_2 doesn't make the input square-free. The aforementioned documentation suggests that this is intended to be the default. The PR adds this step. If you'd rather like to abort and provide sane error messages, remove the call to make_square_free_2 and make the is_square_free_2 a precondition rather than a branch condition.

I can imagine that it breaks implicit user assumptions down the road, because the polynomial considered in the curve analysis is now different from what it used to be. That's also why I propose not to call make_square_free_2 unconditionally; it might always touch the input, and it shouldn't harm performance noticeably. There really shouldn't be any checks for equality of this internal polynomial to the original input, but you never know.

Please test thoroughly, I only gave it a shot with the GMP/MPFI-based non-RS kernel on the tests for Ak_d.

**Comment by sloriot** [comment] 2020-04-24 07:26
@akobel thank you very much for the analysis :) I'll consider your patch as a fix for this issue.

**Closed** 2020-04-29 11:59 UTC
Labels: Has Pull Request, Pkg::Algebraic_kernel_d, bug
