### ISSUE TITLE
Invalid optimal convex decomposition with EPECK

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#5074] opened 2020-10-13 11:37 UTC
The following testcase produces an invalid optimal convex decomposition with EPECK but EPICK is fine.

I notice that the approx works for both kernels but produce different output (maybe the input polygon is different?)

[testcase.zip](https://github.com/CGAL/cgal/files/5370966/testcase.zip)

Reported on cgal-discuss (need to be logged-in): [archive](https://sympa.inria.fr/sympa/arc/cgal-discuss/2020-10/msg00002.html)

Actually, changing the input reading using the following code is working:

```
  int n;
  ss >> n;
  for (int i=0; i<n; ++i)
  {
    double x,y;
    ss >> x >> y;
    polygon.push_back( Point_2(x,y) );
  }
```

So the bug is only with the polygon built using exact input read as string.

It might be a duplicate of https://github.com/CGAL/cgal/issues/2575.

**Comment by MaelRL** [comment] 2020-12-05 17:41
This is indeed a duplicate of #2575, with:
```
-92.52752000000001 48.348349999999996 hides -92.527420000000006 48.348389999999995 from -92.527620000000013 48.348309999999998
```
and the same broken visibility data structure.

The brute force fix (temporary till the visibility is re-implemented using the pkg Visiblity_2) in branch https://github.com/CGAL/cgal-public-dev/tree/Partition_2-Fix_postcondition_failure-GF fixes the issue.

**Closed by MaelRL** 2020-12-05 17:41 UTC
Labels: Pkg::Partition_2, bug, duplicate
