### ISSUE TITLE
Online Documentation: sidebar is mislinked in Mesh_3 Reference Manual

### ISSUE THREAD

**Issue by goran-w** [CGAL/cgal#3562] opened 2018-12-20 08:39 UTC
## Issue Details

When clicking a section in the documentation (latest) sidebar, the correct section is loaded but then the sidebar jumps to a different section, making us lose context since the sidebar no longer shows the section we're reading. This is possibly a problem in other documentation chapters as well. 

Going back to CGAL documentation version 4.11.3, this issue is no longer present. The issue starts appearing in doc version 4.12.1 and is also present in 4.13, "latest" and "master".

Steps to reproduce:
* Navigate to: https://doc.cgal.org/latest/Mesh_3/group__PkgMesh__3.html
* Click the `Reference Manual - Mesh Classes` section in the sidebar. (The correct section text is loaded on the right, but the sidebar jumps to `Reference Manual - Main Concepts - MeshComplexWithFeatures_3InTriangulation_3`.)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Tested in Chrome, Edge, Firefox on Windows 10
* CGAL version: documentation versions master, latest, 4.13, 4.12.1

**Comment by goran-w** [comment] 2018-12-20 08:58
The same issue is present in the Reference Manual for 3D Surface Mesh Generation : 
https://doc.cgal.org/latest/Surface_mesher/group__PkgSurfaceMesher3.html

Thus, the problem seems to be a general one. However, the User Manual sections do not seem to be affected. So far, I've seen this issue in subsections of "Reference Manual" and "Class and Concept List".

For some names under "Class and Concept List", when clicking the name it is highlighted and the corresponding name under Reference Manual is highlighted simultaneously - making the sidebar display two selections at once. For other names, when clicking the name the "Class and Concept List" is collapsed and a section in the "Reference Manual" is expanded and selected.

**Comment by lrineau** [comment] 2018-12-20 10:23
The problem is indeed very general. It is because a former CGAL developer has created code to modify the Javascript array `NAVTREE` (in `Manual/hacks.js`), but then the Javascript function `navTo` does not work correctly.

I have tried to fix it, one day, but I am a complete beginner in Javascript, and was not able to debug the issue correctly.

**Comment by goran-w** [comment] 2018-12-20 10:31
I see. What about the distinct change in behavior between 4.11.3 and 4.12.1 - would it be possible to revert that part of the sidebar code?

Also, the page loading works fine, so would it be possible to just load the page but not modify selection in sidebar?

Finally, as the User Manual sections work fine, would it be possible to remove any extra "hacks" made for  the Reference Manual etc?

**Comment by lrineau** [comment] 2018-12-20 10:45
[**@goran-w**](https://github.com/goran-w) commented on [Dec 20, 2018, 11:31 AM GMT+1](https://github.com/CGAL/cgal/issues/3562#issuecomment-448949942 "2018-12-20T10:31:29Z - Replied by Github Reply Comments"):
> I see. What about the distinct change in behavior between 4.11.3 and 4.12.1 - would it be possible to revert that part of the sidebar code?

... Actually that can give us a lead on how to fix the issue. Something has probably changed between Doxygen 1.8.4 (used for the documentation of CGAL-4.11) and 1.8.13 (used for the documentation since CGAL-4.12).

> Also, the page loading works fine, so would it be possible to just load the page but not modify selection in sidebar?

No, because a click loads a completely different page. The Javascript code has to reselect the entry. Otherwise, the selection would be empty, and the sidebar content would be folded. Well.. actually, that is probably better than the current behavior, that seems to unfold and select a range entry in the navigation tree.

> Finally, as the User Manual sections work fine, would it be possible to remove any extra "hacks" made for  the Reference Manual etc?

No, because in that case the navigation tree would be missing important entries.

@sloriot, do you know any modification of Doxygen as regards to the navtree?

@maxGimeno, do you think that you can learn enough of Javascript to try and find the issue, and a fix?

**Comment by goran-w** [comment] 2018-12-20 11:49
OK, here's a slight hint, taken from the sidebar behavior for the Mesh_3 Reference Manual:

* When clicking the `Mesh Classes` header, the `Main Concepts - MeshComplexWithFeatures_3InTriangulation_3` header is selected instead.

* When unfolding the `Mesh Classes` header and clicking the N'th child entry, the N'th child entry of `Main Concepts - MeshComplexWithFeatures_3InTriangulation_3` is selected instead.

**Comment by goran-w** [comment] 2018-12-20 11:59
Oh, and also : 

* `Mesh Classes` is the 3rd entry below `Reference Manual` - that is why it causes selection of `MeshComplexWithFeatures_3InTriangulation_3` which is the 3rd entry below `Main Concepts`. 

* The `Main Concepts` header is the 1st entry below `Reference Manual` and causes selection of the 1st entry below itself.

Thus, it seems to be always selecting by numeric index, but one level too deep in the tree?

**Comment by goran-w** [comment] 2018-12-20 12:19
However, `Class and Concept List` seems to use a different mapping - for leaf entries it selects the corresponding leaf entry from the `Reference Manual` instead. Here we also sometimes get both of these leafs selected simultaneously. 

For non-leaf (header) entries under `Class and Concept List` the logic is unclear, but it selects some unrelated entry under `Reference Manual` instead.

**Comment by sloriot** [comment] 2018-12-20 15:33
@lrineau I think I never looked at that part, sorry.

**Comment by sloriot** [comment] 2019-02-13 10:37
Note that I've updated the file hacks.js for the doc of CGAL 4.13 and CGAL 4.12.1.

**Comment by lrineau** [comment] 2019-02-13 14:47
Fixed by #3675.

**Closed by lrineau** 2019-02-13 14:47 UTC
Labels: Has Pull Request, doc bug
