### ISSUE TITLE
Random polygon generation issue

### ISSUE THREAD

**Issue by sloriot** [CGAL/cgal#1445] opened 2016-09-12 06:53 UTC
The following examples shows an infinite loop while trying to generate a random polygon

```
/*  
There must be a bug to fix in the sweepline code if this package.
The following data set hangs with the vertices in this particular order.
As the first thing the random_polygon_2 functions does
is a random_shuffle, we have put it in an #ifndef  for this testcase
 */

#define CGAL_DONT_SHUFFLE_IN_RANDOM_POLYGON_2 1

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/random_polygon_2.h>
#include <CGAL/algorithm.h>



#include <fstream>
#include <list>

typedef CGAL::Exact_predicates_inexact_constructions_kernel K;
typedef K::Point_2                                          Point_2;
typedef std::list<Point_2>                                  Container;
typedef CGAL::Polygon_2<K, Container>                       Polygon_2;


int main( )
{
   Polygon_2            polygon;
   std::list<Point_2>   point_set;

   std::string input = "-5 -7 46 59 55 -50 27 -93 46 -62 55 17 -71 0 -27 -41 -86 -73 7 -85 -71 93 41 -47 78 0 -13 52 -73 -25 -17 -11 56 -61 71 -69 -44 59 -9 5 -64 -96 -66 -45 39 54 -93 -22 5 -21 -32 32 -26 77 -99 -2 62 -73 -35 7 -88 60 39 56 2 3 -5 -50 3 68 82 16 -64 -38 -2 -16";


   std::stringstream input_stream(input);

   std::istream_iterator< Point_2 > in(input_stream);
   CGAL::copy_n_unique(in, 38,
                       std::back_inserter(point_set));

   std::ostream_iterator< Point_2 >  out( std::cout, "\n " );

   CGAL::random_polygon_2(point_set.size(), std::back_inserter(polygon),
                          point_set.begin());

   std::cout << "done" << std::endl;
   return 0;
}
```

**Comment by HoffmannMichael** [comment] 2016-09-12 07:54
Is it because -73 appears twice?
(Or at least what is the point of having it twice?)

**Comment by sloriot** [comment] 2016-09-12 08:40
I do not see any duplicated point.
This is an old bug report by a user.

**Comment by HoffmannMichael** [comment] 2016-09-12 09:16
you're right, this copy_n_unique had me confused.
Should it be removed from the example program? I don't see the point of having this undocumented function exposed. In particular as that is the first thing (yet again) called in  random_polygon_2.

**Comment by sloriot** [comment] 2016-09-12 09:20
Actually it is required to reproduce a particular sequence of _random_ points

**Comment by afabri** [comment] 2016-09-20 13:36
I can reduce the point set to:

 -5 -7 -86 -73 7 -85 -9 5 -64 -96 39 56  -64 -38 -2 -16

**Comment by maxGimeno** [comment] 2018-10-19 10:00
That is a sequence that produces a Polygon that the algorithm cannot simplify. Basically, breaking a loop creates another, everytime, until the two "conflicts" returned by check_simple_polygon are two following edges. From there the algorithm won't change anything in any further loop because it will reverse only 2 points, and then put them back as before. 
It is easily detected by an assertion, but I think the easier fix to random_polygon would be to re-randomize the points if that occurs, and retry. The problem is that we have an option there that disables the randomization of the points in random_polygon. If this is on, we are stuck with a sequence that cannot be resolved and cannot generate another. 
So should we just add an assertion to prevent the infinite_loop ? Or maybe also add a fix only if the randomization of the points is ON ?

**Comment by maxGimeno** [comment] 2018-10-24 08:50
ping @CGAL/geometryfactory

**Comment by sloriot** [comment] 2018-10-24 08:54
What does _The problem is that we have an option there that disables the randomization of the points in random_polygon_ means? I don't see anything on the doc page.

**Comment by sloriot** [comment] 2018-10-24 10:19
It is a `#ifndef` and by default points are shuffled AFAIS. Anyway I don't see what this has to do with the way to fix the bug. Points are generated internally by the function so if a sequence is invalid I don't see why you could not change it. I'm surprised that this isn't a bug in `check_simple_polygon()` that is returning a wrong sequence.

**Comment by ylieder** [comment] 2020-02-04 21:40
This issue occurs mostly (but not always, if I see it correctly) on point sets with at least three collinear points (as also in the example above).

When generating a large set of random polygons, this issue occurs very often.

**Comment by gijsde1ste** [comment] 2020-05-24 09:56
Hi, is there any quick fix for this available yet?

I'm trying to generate a huge polygon (200+ million vertices), due to quadratic? complexity of the generation algorithm I'm trying a different approach. Generating many small (200-500 vertex) polygons in a grid like structure and then merging those together into one big polygon (linear time complexity). Code works fine but when I increase the size of the grid I come across this bug every single time.

Is there anyway to detect this infinite loop and somehow prevent/break it? I don't mind if the polygon needs to be regenerated from scratch again.

**Comment by ylieder** [comment] 2020-05-24 11:00
You could try to generate only non-collinear points in your subsets, but of course this is not an appropriate fix/work around in general.

Regarding the time complexity, the CGAL user manual says: 
> The implementation is based on the method of eliminating self-intersections in a polygon by using so-called "2-opt" moves. Such a move eliminates an intersection between two edges by reversing the order of the vertices between the edges. No more than O(n^3) such moves are required to simplify a polygon defined on n points [3]. Intersecting edges are detected using a simple sweep through the vertices and then one intersection is chosen at random to eliminate after each sweep.
> **The worse-case running time is therefore O(n^4 log n)**.

https://doc.cgal.org/latest/Generator/group__PkgGeneratorsRef.html#gaa8cb58e4cc9ab9e225808799b1a61174

**Comment by gijsde1ste** [comment] 2020-05-25 12:00
For anyone who comes across this thread and needs a quick fix, obviously the above answer of ylieder is reasonable. However I found that implementing such a check, whether the generated points are non-collinear, to be non trivial and more importantly would add a constant time to every polygon that is generated.

A very dirty fix that works great for me is to add a timeout on the while loop. If it takes longer than x seconds just break the loop and check in your own program whether the result is a simple polygon, else regenerate.

Needs edits in three files:
file: CGAL/Random_polygon_2_sweep.h
line 35:
`#include <time.h>`
line 556:
```time_t start = time(0);

do {
    if (difftime(time(0), start) > 1){ // change 1 into how many seconds you want the timeout
        break;
    }
```

file: CGAL/random_polygon_2.h
line 65:
`//CGAL_assertion(is_simple_2(vertices.begin(), vertices.end()));`
This check is overkill? polygon is already checked when fixing the orientation before

file CGAL/Polygon_2/Polygon_2_algorithms_impl.h
line 403:
`//CGAL_polygon_precondition(is_simple_2(first, last, traits));`

**Closed** 2021-04-17 09:00 UTC
Labels: Has Pull Request, Pkg::Generators, bug
