### ISSUE TITLE
the mesh could be drawn but throws at CGAL_assertion(n >= 3) when use write_polygon_mesh to save the mesh

### ISSUE THREAD

**Issue by citystrawman** [CGAL/cgal#8452] opened 2024-09-02 15:50 UTC
_Please use the following template to help us solving your issue._

## Issue Details

Before saving I used ` CGAL::Euler::join_vertex()` to join several vertices in the mesh, and then I use `CGAL::draw()`, and the mesh looks fine:
![image](https://github.com/user-attachments/assets/d6b78ebb-e30e-4818-a108-f50d0eb29379)
however, when I tried to save it using `CGAL::IO::write_polygon_mesh` it throws erros:
```
CGAL error: assertion violation!
Expression : n >= 3
File       : D:\Programs\vcpkg\installed\x64-windows\include\CGAL/boost/graph/IO/Generic_facegraph_printer.h
Line       : 173
Explanation:
```
![image](https://github.com/user-attachments/assets/e75acc14-e691-4421-9504-385a68fdd7c9)

May I know is it possible to solve this problem? 

## Source Code

```
// join vertex for mesh...
mesh.collect_garbage();
CGAL::draw(mesh);
CGAL::IO::write_polygon_mesh("model_join_vertex.off", mesh, CGAL::parameters::stream_precision(17));
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment] 2024-09-02 16:04
You should call is_valid_polygon_mesh() right after every (Euler) operation you are doing. One operation seems to have gone wrong

**Comment by citystrawman** [comment] 2024-09-02 16:15
> You should call `is_valid_polygon_mesh(pm)` right after every (Euler) operation you are doing. One operation seems to have gone wrong

Thank you. I use `assert(is_valid_polygon_mesh(pm))` after every join_vertex, and when the program ran, it pops out errors as follows: 
![image](https://github.com/user-attachments/assets/d88681cf-d3ba-4ded-be3e-f67d013e0cd3)
and the calling stack:
![image](https://github.com/user-attachments/assets/7bda8b4c-e39d-4ac7-826b-767703d27407)
gives no info about the details. 
 I am not clear what is the real problem. Is there a way to find a detailed problem?

**Comment by citystrawman** [comment] 2024-09-02 17:02
> You should call `is_valid_polygon_mesh(pm)` right after every (Euler) operation you are doing. One operation seems to have gone wrong

Here's the info by using is_valid_polygon_mesh(pm, true):
```
Halfedge Graph Structure is valid
Face Graph Structure is valid
incident facet is not at least a triangle.
Polygon Mesh Structure is NOT VALID.
```
why it says `incident facet is not at least a triangle.` ?  what I did was just join two vertices (such as join the red and blue vertice as follows)

![image](https://github.com/user-attachments/assets/148421d4-17a2-4520-9228-addd89b604ea)

**Comment by sloriot** [comment] 2024-09-03 07:09
Most likely you called join_vertex() or something like that and the edge that disappear was incident to a triangle, then you endup with a face which is not at least a triangle

**Comment by citystrawman** [comment] 2024-09-03 14:49
> Most likely you called join_vertex() or something like that and the edge that disappear was incident to a triangle, then you endup with a face which is not at least a triangle

Thanks. I am trying to fix that.

**Comment by sloriot** [comment] 2024-09-03 15:59
I'm closing the issue as the problem is most likely in your code.

**Closed by sloriot** 2024-09-03 15:59 UTC
