### ISSUE TITLE
Why does this 'CGAL::Polygon_mesh_processing::triangulate_hole_polyline' function return null data?

### ISSUE THREAD

**Issue by mirro187** [CGAL/cgal#3928] opened 2019-05-14 01:18 UTC
## Issue Details
When I run sometimes the CGAL::Polygon_mesh_processing::triangulate_hole_polyline function return null data.

## Source Code

```
#define CGAL_EIGEN3_ENABLED
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/triangulate_hole.h>
#include <CGAL/utility.h>
#include <vector>
#include <iterator>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;
int main()
{
	std::vector<Point> polyline;
	polyline.push_back(Point(-7.8726686201989651, 188.07689549960196, 0.00000000000));
	polyline.push_back(Point(-13.439474903047085, 189.12690296955407, 0.00000000000));
	polyline.push_back(Point(-13.932104835286736, 188.92983485572040, 0.00000000000));
	polyline.push_back(Point(-14.923283766955137, 189.12653931789100, 0.00000000000));
	polyline.push_back(Point(5.3099240260198712, 211.64381128177047, 0.000000000000));
	polyline.push_back(Point(5.2071536798030138, 211.73706355132163, 0.000000000000));
	polyline.push_back(Point(5.5753986379131675, 212.16910720989108, 0.000000000000));
	polyline.push_back(Point(5.8483026241883636, 212.23957733809948, 0.000000000000));
	polyline.push_back(Point(6.3638061108067632, 212.81301873549819, 0.000000000000));
	polyline.push_back(Point(6.3126446232199669, 212.89562169276178, 0.000000000000));
	polyline.push_back(Point(6.5302440738305449, 213.14098469913006, 0.000000000000));
	polyline.push_back(Point(0.96329743973910809, 214.31413905695081, 0.00000000000));
	polyline.push_back(Point(-0.53098367433995008, 212.67198625579476, 0.0000000000));
	polyline.push_back(Point(-0.62854729034006596, 212.70347442850471, 0.0000000000));
	polyline.push_back(Point(-0.47638443484902382, 212.88073633611202, 0.0000000000));
	polyline.push_back(Point(-0.74832537211477757, 212.95725093968213, 0.0000000000));
	polyline.push_back(Point(6.8098482228815556, 221.42979247309268, 0.000000000000));
	polyline.push_back(Point(-8.3303045658394694, 224.29356182552874, 0.0000000000000));
	polyline.push_back(Point(-11.235364770516753, 220.98003060370684, 0.0000000000000));
	polyline.push_back(Point(-45.802515009418130, 227.42578614689410, 0.0000000000000));
	polyline.push_back(Point(-32.858473339118063, 241.73789385147393, 0.0000000000000));
	polyline.push_back(Point(-30.921305101364851, 244.22616925835609, 0.0000000000000));
	polyline.push_back(Point(-29.450535735115409, 246.71253443323076, 0.0000000000000));
	polyline.push_back(Point(-28.487285695970058, 249.12753260508180, 0.0000000000000));
	polyline.push_back(Point(-28.058372768573463, 251.40371056087315, 0.0000000000000));
	polyline.push_back(Point(-28.176080557517707, 253.47721524536610, 0.0000000000000));
	polyline.push_back(Point(-28.837001789361238, 255.29018744453788, 0.0000000000000));
	polyline.push_back(Point(-30.022544508799911, 256.79203805886209, 0.0000000000000));
	polyline.push_back(Point(-31.699781307950616, 257.94051919132471, 0.0000000000000));
	polyline.push_back(Point(-33.821477374061942, 258.70377297140658, 0.0000000000000));
	polyline.push_back(Point(-40.219430571421981, 259.95615514740348, 0.0000000000000));
	polyline.push_back(Point(-48.608016339130700, 250.58659960515797, 0.0000000000000));
	polyline.push_back(Point(-42.551907652057707, 249.45478717982769, 0.0000000000000));
	polyline.push_back(Point(-41.806492163799703, 249.13851151242852, 0.0000000000000));
	polyline.push_back(Point(-41.230558714829385, 248.68174238875508, 0.0000000000000));
	polyline.push_back(Point(-40.840422896668315, 248.09755160845816, 0.0000000000000));
	polyline.push_back(Point(-40.647360310889781, 247.40227208659053, 0.0000000000000));
	polyline.push_back(Point(-40.656593500636518, 246.61573995277286, 0.0000000000000));
	polyline.push_back(Point(-40.867955083027482, 245.76004694774747, 0.0000000000000));
	polyline.push_back(Point(-41.275560508482158, 244.85937192291021, 0.0000000000000));
	polyline.push_back(Point(-41.867718636989594, 243.93942688219249, 0.0000000000000));
	polyline.push_back(Point(-42.627834623679519, 243.02582274749875, 0.0000000000000));
	polyline.push_back(Point(-49.424864826723933, 235.30430717580020, 0.0000000000000));
	polyline.push_back(Point(-50.679901784285903, 235.45609739236534, 0.0000000000000));
	polyline.push_back(Point(-55.473742543719709, 230.11415691114962, 0.0000000000000));
	polyline.push_back(Point(-62.429032732732594, 231.40670392662287, 0.0000000000000));
	polyline.push_back(Point(-62.729252677410841, 231.06580935418606, 0.0000000000000));
	polyline.push_back(Point(-64.138989416882396, 231.25811447203159, 0.0000000000000));
	polyline.push_back(Point(-63.669142334721982, 231.73205821774900, 0.0000000000000));
	polyline.push_back(Point(-64.876862261444330, 232.03768499940634, 0.0000000000000));
	polyline.push_back(Point(-58.258877643384039, 239.30004357174039, 0.0000000000000));
	polyline.push_back(Point(-64.662268810905516, 240.76306129992008, 0.0000000000000));
	polyline.push_back(Point(-66.590860781259835, 238.59397043660283, 0.0000000000000));
	polyline.push_back(Point(-74.119770314544439, 239.85934629477561, 0.0000000000000));
	polyline.push_back(Point(-45.127765072509646, 272.26375959999859, 0.0000000000000));
	polyline.push_back(Point(-44.532489580102265, 272.19631910137832, 0.0000000000000));
	polyline.push_back(Point(-43.163848125375807, 273.73105507157743, 0.0000000000000));
	polyline.push_back(Point(-43.748819914646447, 273.80503061972558, 0.0000000000000));
	polyline.push_back(Point(-41.522696767933667, 276.24946438148618, 0.0000000000000));
	polyline.push_back(Point(-38.947568316943944, 278.58699198625982, 0.0000000000000));
	polyline.push_back(Point(-37.117187477648258, 279.99861537665129, 0.0000000000000));
	polyline.push_back(Point(-35.136172658763826, 281.25962918996811, 0.0000000000000));
	polyline.push_back(Point(-33.062296262942255, 282.33300724625587, 0.0000000000000));
	polyline.push_back(Point(-30.955653280951083, 283.18774426542222, 0.0000000000000));
	polyline.push_back(Point(-28.877199221402407, 283.79912379942834, 0.0000000000000));
	polyline.push_back(Point(-26.887498284690082, 284.14934645406902, 0.0000000000000));
	polyline.push_back(Point(-25.044010099954903, 284.22842559218407, 0.0000000000000));
	polyline.push_back(Point(-23.266232514753938, 284.14033645391464, 0.0000000000000));
	polyline.push_back(Point(-23.182057663798332, 284.24274416267872, 0.0000000000000));
	polyline.push_back(Point(2.6709610354155302, 279.16868435591459, 0.00000000000000));
	polyline.push_back(Point(11.285289118997753, 289.05093807727098, 0.00000000000000));
	polyline.push_back(Point(72.032728911377490, 278.33659391850233, 0.00000000000000));
	polyline.push_back(Point(-7.8726686201989651, 188.07689549960196, 0.0000000000000));
	// repeating first point (i.e. polyline.push_back(Point(1.,0.,0.)) ) is optional
	// any type, having Type(int, int, int) constructor available, can be used to hold output triangles
	typedef CGAL::Triple<int, int, int> Triangle_int;
	std::vector<Triangle_int> patch;
	patch.reserve(polyline.size() - 2); // there will be exactly n-2 triangles in the patch
	CGAL::Polygon_mesh_processing::triangulate_hole_polyline(
		polyline,
		std::back_inserter(patch));
	//
	for (std::size_t i = 0; i < patch.size(); ++i)
	{
		std::cout << "Triangle " << i << ": "
			<< patch[i].first << " " << patch[i].second << " " << patch[i].third
			<< std::endl;
	}
	return 0;
}
```

## Environment
* CGAL version:4.14
* Boost version:1.67.0

**Comment by mirro187** [comment] 2019-05-14 04:48
Is it because the polygon is too wide?

**Comment by janetournois** [comment] 2019-05-14 09:40
Hi @mirro187, thank you for your report.
I can reproduce this issue, and I could fix it by setting the parameter `use_delaunay_triangulation` to false, like that :
```
CGAL::Polygon_mesh_processing::triangulate_hole_polyline(
    polyline,
    std::back_inserter(patch),
    CGAL::Polygon_mesh_processing::parameters::use_delaunay_triangulation(false));
```
This parameter should speed-up the algorithm, not lead it to fail. I will try to figure out what goes wrong, but for the moment you can use this fix.

**Comment by janetournois** [comment] 2019-05-14 10:35
The PR #3932 should fix your issue.

**Comment by lrineau** [comment] 2019-05-14 11:13
This PR will be fixed once PR #3932 is merged.

**Comment by mirro187** [comment] 2019-05-14 12:30
> Hi @mirro187, thank you for your report.
> I can reproduce this issue, and I could fix it by setting the parameter `use_delaunay_triangulation` to false, like that :
> 
> ```
> CGAL::Polygon_mesh_processing::triangulate_hole_polyline(
>     polyline,
>     std::back_inserter(patch),
>     CGAL::Polygon_mesh_processing::parameters::use_delaunay_triangulation(false));
> ```
> 
> This parameter should speed-up the algorithm, not lead it to fail. I will try to figure out what goes wrong, but for the moment you can use this fix.

Thank you so much for your reply ！

but, I use the CGAL::Polygon_mesh_processing::parameters::use_delaunay_triangulation function appear endless loop。

please, test the following code.

`
#define CGAL_EIGEN3_ENABLED
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Polygon_mesh_processing/triangulate_hole.h>
#include <CGAL/utility.h>
#include <vector>
#include <iterator>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef Kernel::Point_3 Point;

int main()
{
	std::vector<Point> polyline;
	polyline.push_back(Point(-57.463434330187738, 66.845298694446683, 0.00000000));
	polyline.push_back(Point(-58.290295247919858, 66.558445027098060, 0.00000000));
	polyline.push_back(Point(-58.450687980279326, 66.800886945798993, 0.00000000));
	polyline.push_back(Point(-57.222236481495202, 67.557413440197706, 0.00000000));
	polyline.push_back(Point(-56.698472592979670, 66.745201425626874, 0.00000000));
	polyline.push_back(Point(-56.079453883692622, 67.092201203107834, 0.00000000));
	polyline.push_back(Point(-55.845531119965017, 66.681763332337141, 0.00000000));
	polyline.push_back(Point(-56.467042839154601, 66.382614653557539, 0.00000000));
	polyline.push_back(Point(-48.081567570567131, 52.792593987658620, 0.00000000));
	polyline.push_back(Point(-47.843345465138555, 52.865998383611441, 0.00000000));
	polyline.push_back(Point(-47.447404194623232, 52.180862467736006, 0.00000000));
	polyline.push_back(Point(-47.664633712731302, 52.060349695384502, 0.00000000));
	polyline.push_back(Point(-43.306049294769764, 44.970666315406561, 0.00000000));
	polyline.push_back(Point(-43.291011277586222, 44.944247592240572, 0.00000000));
	polyline.push_back(Point(-43.275578027591109, 44.917943669483066, 0.00000000));
	polyline.push_back(Point(-43.259682225063443, 44.892037205398083, 0.00000000));
	polyline.push_back(Point(-43.243391027674079, 44.866245632991195, 0.00000000));
	polyline.push_back(Point(-43.226808865554631, 44.840749043971300, 0.00000000));
	polyline.push_back(Point(-43.209831472486258, 44.815367262810469, 0.00000000));
	polyline.push_back(Point(-43.192391530610621, 44.790382929146290, 0.00000000));
	polyline.push_back(Point(-43.174608241766691, 44.765603637322783, 0.00000000));
	polyline.push_back(Point(-43.156481935642660, 44.741029188036919, 0.00000000));
	polyline.push_back(Point(-43.137840704061091, 44.716762246564031, 0.00000000));
	polyline.push_back(Point(-43.118856444954872, 44.692700143903494, 0.00000000));
	polyline.push_back(Point(-43.099581237882376, 44.668933037668467, 0.00000000));
	polyline.push_back(Point(-43.079739034175873, 44.645383285358548, 0.00000000));
	polyline.push_back(Point(-43.059777301736176, 44.622026154771447, 0.00000000));
	polyline.push_back(Point(-43.039300960488617, 44.598976338282228, 0.00000000));
	polyline.push_back(Point(-43.018533500842750, 44.576221605762839, 0.00000000));
	polyline.push_back(Point(-42.997199214994907, 44.553684135898948, 0.00000000));
	polyline.push_back(Point(-42.975573964416981, 44.531441653147340, 0.00000000));
	polyline.push_back(Point(-42.953657427802682, 44.509494353085756, 0.00000000));
	polyline.push_back(Point(-42.931345820426941, 44.487661750987172, 0.00000000));
	polyline.push_back(Point(-42.908571503125131, 44.466226704418659, 0.00000000));
	polyline.push_back(Point(-42.885454007424414, 44.444996600970626, 0.00000000));
	polyline.push_back(Point(-42.862045546062291, 44.424061477184296, 0.00000000));
	polyline.push_back(Point(-42.838293910957873, 44.403331307694316, 0.00000000));
	polyline.push_back(Point(-42.814027504064143, 44.382908536121249, 0.00000000));
	polyline.push_back(Point(-42.789641557261348, 44.362678378820419, 0.00000000));
	polyline.push_back(Point(-42.764621485024691, 44.342948161065578, 0.00000000));
	polyline.push_back(Point(-42.739377597346902, 44.323230355978012, 0.00000000));
	polyline.push_back(Point(-42.713894801214337, 44.303897680714726, 0.00000000));
	polyline.push_back(Point(-42.687845346517861, 44.284782176837325, 0.00000000));
	polyline.push_back(Point(-42.661556662991643, 44.266052002087235, 0.00000000));
	polyline.push_back(Point(-42.634872907772660, 44.247436525300145, 0.00000000));
	polyline.push_back(Point(-42.607778486795723, 44.229308743029833, 0.00000000));
	polyline.push_back(Point(-42.580512483604252, 44.211283432319760, 0.00000000));
	polyline.push_back(Point(-42.552731874398887, 44.193565433844924, 0.00000000));
	polyline.push_back(Point(-34.131167367100716, 38.271305093541741, 0.00000000));
	polyline.push_back(Point(-26.355136001482606, 44.347124492749572, 0.00000000));
	polyline.push_back(Point(0.00000000000000000, 0.00000000000000000, 0.0000000));
	polyline.push_back(Point(-23.041808269917965, -13.595356948673725, 0.0000000));
	polyline.push_back(Point(-23.013480014167726, -13.643542917445302, 0.0000000));
	polyline.push_back(Point(-22.251249444670975, -14.992691429331899, 0.0000000));
	polyline.push_back(Point(-21.887940696440637, -16.557641647756100, 0.0000000));
	polyline.push_back(Point(-21.932044289074838, -18.301758846268058, 0.0000000));
	polyline.push_back(Point(-22.382557491771877, -20.184072667732835, 0.0000000));
	polyline.push_back(Point(-23.228924882598221, -22.160575075075030, 0.0000000));
	polyline.push_back(Point(-24.028866440989077, -23.638233292847872, 0.0000000));
	polyline.push_back(Point(-25.077408852986991, -25.129052752628922, 0.0000000));
	polyline.push_back(Point(-26.353152544237673, -26.602189810946584, 0.0000000));
	polyline.push_back(Point(-27.829635499045253, -28.027172232046723, 0.0000000));
	polyline.push_back(Point(-29.884814810939133, -29.875573959201574, 0.0000000));
	polyline.push_back(Point(-32.139296574518085, -31.610465640202165, 0.0000000));
	polyline.push_back(Point(-34.549475803039968, -33.198290573433042, 0.0000000));
	polyline.push_back(Point(-45.835052357986569, -40.019043529406190, 0.0000000));
	polyline.push_back(Point(-49.203604334965348, -41.870767811313272, 0.0000000));
	polyline.push_back(Point(-52.655038812197745, -43.379670610651374, 0.0000000));
	polyline.push_back(Point(-54.961811820976436, -44.195305310189724, 0.0000000));
	polyline.push_back(Point(-57.219375124201179, -44.774362305179238, 0.0000000));
	polyline.push_back(Point(-59.378947411663830, -45.104198578745127, 0.0000000));
	polyline.push_back(Point(-61.880769130773842, -45.221856795251369, 0.0000000));
	polyline.push_back(Point(-64.128584922291338, -44.987670004367828, 0.0000000));
	polyline.push_back(Point(-66.062926258891821, -44.407466227188706, 0.0000000));
	polyline.push_back(Point(-67.632810169830918, -43.496747720986605, 0.0000000));
	polyline.push_back(Point(-68.797088677063584, -42.279556928202510, 0.0000000));
	polyline.push_back(Point(-71.614020320586860, -37.743060361593962, 0.0000000));
	polyline.push_back(Point(-63.113379538059235, -32.608924219384789, 0.0000000));
	polyline.push_back(Point(-62.146759885363281, -32.028039544820786, 0.0000000));
	polyline.push_back(Point(-62.191433134488761, -31.735265476629138, 0.0000000));
	polyline.push_back(Point(-61.107210840098560, -31.056388035416603, 0.0000000));
	polyline.push_back(Point(-60.965197852812707, -31.292366180568933, 0.0000000));
	polyline.push_back(Point(-49.850436505861580, -24.581367146223783, 0.0000000));
	polyline.push_back(Point(-47.256577365100384, -28.927146688103676, 0.0000000));
	polyline.push_back(Point(-45.196182376705110, -27.687140163034201, 0.0000000));
	polyline.push_back(Point(-47.915760236792266, -23.105592142790556, 0.0000000));
	polyline.push_back(Point(-46.737495049834251, -22.382192859426141, 0.0000000));
	polyline.push_back(Point(-46.602674460969865, -22.602947706356645, 0.0000000));
	polyline.push_back(Point(-35.040948742069304, -15.634004909545183, 0.0000000));
	polyline.push_back(Point(-35.000838016159832, -15.350125109776855, 0.0000000));
	polyline.push_back(Point(-34.900661535561085, -15.227987147867680, 0.0000000));
	polyline.push_back(Point(-33.841125537641346, -14.563125135377049, 0.0000000));
	polyline.push_back(Point(-25.635888336226344, -9.8624224085360765, 0.0000000));
	polyline.push_back(Point(-24.818001288920641, -9.3764205612242222, 0.0000000));
	polyline.push_back(Point(-20.573461577296257, -6.8003217298537493, 0.0000000));
	polyline.push_back(Point(-20.671630989760160, -6.5866541173309088, 0.0000000));
	polyline.push_back(Point(-19.591410514898598, -5.9384150672703981, 0.0000000));
	polyline.push_back(Point(-18.988070067018270, -5.8896842245012522, 0.0000000));
	polyline.push_back(Point(-15.628814556635916, -3.8758425321429968, 0.0000000));
	polyline.push_back(Point(-15.755380189977586, -3.6689488105475903, 0.0000000));
	polyline.push_back(Point(-15.303031905554235, -3.3966329284012318, 0.0000000));
	polyline.push_back(Point(-16.755263504572213, -0.97866984643042088, 0.000000));
	polyline.push_back(Point(-17.210138882510364, -1.1312607321888208, 0.0000000));
	polyline.push_back(Point(-17.566916269250214, -0.62164438888430595, 0.000000));
	polyline.push_back(Point(-17.168194264173508, -0.38232286646962166, 0.000000));
	polyline.push_back(Point(-21.272433283738792, 6.5934832617640495, 0.00000000));
	polyline.push_back(Point(-21.744798433966935, 6.3106681294739246, 0.00000000));
	polyline.push_back(Point(-22.087415176443756, 6.8972336091101170, 0.00000000));
	polyline.push_back(Point(-21.707922983914614, 7.2692182846367359, 0.00000000));
	polyline.push_back(Point(-25.569464989937842, 13.721666963770986, 0.00000000));
	polyline.push_back(Point(-32.133090733550489, 9.8370232321321964, 0.00000000));
	polyline.push_back(Point(-32.407978045754135, 10.281332986429334, 0.00000000));
	polyline.push_back(Point(-39.663230833597481, 5.8678831662982702, 0.00000000));
	polyline.push_back(Point(-39.768987931311131, 6.0484047457575798, 0.00000000));
	polyline.push_back(Point(-42.342163453809917, 4.5067789312452078, 0.00000000));
	polyline.push_back(Point(-42.229166577570140, 4.2945747207850218, 0.00000000));
	polyline.push_back(Point(-43.135322734713554, 3.7651937119662762, 0.00000000));
	polyline.push_back(Point(-42.874215152114630, 3.2744669616222382, 0.00000000));
	polyline.push_back(Point(-44.830407202243805, 2.1096578594297171, 0.00000000));
	polyline.push_back(Point(-45.519195698201656, 3.2470735814422369, 0.00000000));
	polyline.push_back(Point(-51.312135552056134, -0.17660601623356342, 0.000000));
	polyline.push_back(Point(-50.130163686349988, -2.1681813206523657, 0.0000000));
	polyline.push_back(Point(-49.398777046240866, -3.4007867891341448, 0.0000000));
	polyline.push_back(Point(-43.715512662194669, 0.011343659833073616, 0.000000));
	polyline.push_back(Point(-43.361754422076046, -0.56735237501561642, 0.000000));
	polyline.push_back(Point(-63.530755801126361, -12.758377026766539, 0.0000000));
	polyline.push_back(Point(-63.644889262504876, -12.573764948174357, 0.0000000));
	polyline.push_back(Point(-63.527669520117342, -12.474303752183914, 0.0000000));
	polyline.push_back(Point(-64.256901918910444, -11.367222076281905, 0.0000000));
	polyline.push_back(Point(-71.968920437619090, -15.999258048832417, 0.0000000));
	polyline.push_back(Point(-73.053839039988816, -14.285419436171651, 0.0000000));
	polyline.push_back(Point(-75.150489180348814, -15.563447449356318, 0.0000000));
	polyline.push_back(Point(-75.369312822818756, -15.136697938665748, 0.0000000));
	polyline.push_back(Point(-73.327080869115889, -13.915050303563476, 0.0000000));
	polyline.push_back(Point(-77.505473776720464, -6.7210736963897943, 0.0000000));
	polyline.push_back(Point(-79.628433868288994, -8.0294837597757578, 0.0000000));
	polyline.push_back(Point(-79.840362848713994, -7.6609332952648401, 0.0000000));
	polyline.push_back(Point(-77.766454811207950, -6.4018195495009422, 0.0000000));
	polyline.push_back(Point(-77.973879063501954, -6.0254872906953096, 0.0000000));
	polyline.push_back(Point(-75.785685976035893, -4.7045496869832277, 0.0000000));
	polyline.push_back(Point(-75.389815368689597, -5.3593177888542414, 0.0000000));
	polyline.push_back(Point(-69.332518134266138, -1.7383619155734777, 0.0000000));
	polyline.push_back(Point(-71.223623847588897, 1.3992965761572123, 0.00000000));
	polyline.push_back(Point(-68.500930770300329, 3.0445206314325333, 0.00000000));
	polyline.push_back(Point(-70.183965017087758, 5.7497315574437380, 0.00000000));
	polyline.push_back(Point(-70.111529120244086, 5.9366483632475138, 0.00000000));
	polyline.push_back(Point(-70.686736485920846, 6.9128685388714075, 0.00000000));
	polyline.push_back(Point(-70.828032845631242, 6.8290947582572699, 0.00000000));
	polyline.push_back(Point(-71.047007307410240, 7.2090742401778698, 0.00000000));
	polyline.push_back(Point(-69.928757004439831, 7.8802700098603964, 0.00000000));
	polyline.push_back(Point(-74.654573792591691, 15.858551299199462, 0.00000000));
	polyline.push_back(Point(-75.959683185443282, 15.072977151721716, 0.00000000));
	polyline.push_back(Point(-76.059621098451316, 14.965167216956615, 0.00000000));
	polyline.push_back(Point(-82.947819441556931, 10.842911144718528, 0.00000000));
	polyline.push_back(Point(-84.602382722310722, 9.8010045588016510, 0.00000000));
	polyline.push_back(Point(-84.282139690592885, 9.0801100470125675, 0.00000000));
	polyline.push_back(Point(-86.342431331984699, 7.8053645901381969, 0.00000000));
	polyline.push_back(Point(-86.636620100587606, 8.2420151028782129, 0.00000000));
	polyline.push_back(Point(-99.749222628772259, 0.36590262129902840, 0.0000000));
	polyline.push_back(Point(-99.638522492721677, 0.19197474792599678, 0.0000000));
	polyline.push_back(Point(-100.73141367267817, -0.48759692162275314, 0.000000));
	polyline.push_back(Point(-100.87559942901134, -0.29487244039773941, 0.000000));
	polyline.push_back(Point(-104.92511947918683, -2.7529500294476748, 0.0000000));
	polyline.push_back(Point(-105.17129043117166, -2.4077641759067774, 0.0000000));
	polyline.push_back(Point(-87.229412494227290, 8.4513666629791260, 0.00000000));
	polyline.push_back(Point(-87.007334756664932, 8.9348292164504528, 0.00000000));
	polyline.push_back(Point(-85.529160792008042, 9.8630339708179235, 0.00000000));
	polyline.push_back(Point(-85.464197114109993, 10.128772774711251, 0.00000000));
	polyline.push_back(Point(-76.117499300278723, 15.756062099710107, 0.00000000));
	polyline.push_back(Point(-75.834978112019598, 15.736872121691704, 0.00000000));
	polyline.push_back(Point(-75.249276528134942, 16.102767840027809, 0.00000000));
	polyline.push_back(Point(-76.693427325226367, 18.558419950306416, 0.00000000));
	polyline.push_back(Point(-74.018717494793236, 20.170142706483603, 0.00000000));
	polyline.push_back(Point(-75.073710847645998, 21.899499921128154, 0.00000000));
	polyline.push_back(Point(-78.639713102020323, 19.864374946802855, 0.00000000));
	polyline.push_back(Point(-78.931514551863074, 20.278566561639309, 0.00000000));
	polyline.push_back(Point(-78.489600357599556, 20.586962603032589, 0.00000000));
	polyline.push_back(Point(-77.997569556348026, 20.700041960924864, 0.00000000));
	polyline.push_back(Point(-75.674586424604058, 22.084140855818987, 0.00000000));
	polyline.push_back(Point(-75.887496138922870, 22.532352527603507, 0.00000000));
	polyline.push_back(Point(-69.614583252929151, 26.239284774288535, 0.00000000));
	polyline.push_back(Point(-69.443193326704204, 26.627981849014759, 0.00000000));
	polyline.push_back(Point(-69.928753802552819, 27.317915298044682, 0.00000000));
	polyline.push_back(Point(-70.251474473625422, 27.232964867725968, 0.00000000));
	polyline.push_back(Point(-71.600357536226511, 29.415386687964201, 0.00000000));
	polyline.push_back(Point(-74.337383197620511, 33.843933632597327, 0.00000000));
	polyline.push_back(Point(-71.958437824621797, 35.264605367556214, 0.00000000));
	polyline.push_back(Point(-70.742094676941633, 33.160035099834204, 0.00000000));
	polyline.push_back(Point(-62.287048722617328, 38.209263689815998, 0.00000000));
	polyline.push_back(Point(-63.503376390784979, 40.313844598829746, 0.00000000));
	polyline.push_back(Point(-47.171721874736249, 50.066865479573607, 0.00000000));
	polyline.push_back(Point(-57.463434330187738, 66.845298694446683, 0.00000000));

	// repeating first point (i.e. polyline.push_back(Point(1.,0.,0.)) ) is optional
	// any type, having Type(int, int, int) constructor available, can be used to hold output triangles
	typedef CGAL::Triple<int, int, int> Triangle_int;
	std::vector<Triangle_int> patch;
	patch.reserve(polyline.size() - 2); // there will be exactly n-2 triangles in the patch
	CGAL::Polygon_mesh_processing::triangulate_hole_polyline(
		polyline,
		std::back_inserter(patch),
		CGAL::Polygon_mesh_processing::parameters::use_delaunay_triangulation(false));
	//
	for (std::size_t i = 0; i < patch.size(); ++i)
	{
		std::cout << "Triangle " << i << ": "
			<< patch[i].first << " " << patch[i].second << " " << patch[i].third
			<< std::endl;
	}
	return 0;
}
`

**Comment by afabri** [comment] 2019-05-24 11:37
@janetournois did you have a look?

**Comment by janetournois** [comment] 2019-05-24 12:16
Sorry, I thought it was fixed by the PR.
I will have a look at this new data!

**Comment by janetournois** [comment] 2019-05-24 12:53
It works for me, with CGAL-4.14 and with the master branch.

**Closed** 2019-06-17 11:58 UTC
Labels: Has Pull Request, Pkg::PMP, bug

**Comment by lrineau** [comment] 2019-06-17 12:04
This issue is said to be fixed by the PR #3932. But PR #3932 is for `master` only, and this issue is about CGAL-4.13.x. Was is expected?

**Comment by mirro187** [comment] 2019-06-19 03:26
> It works for me, with CGAL-4.14 and with the master branch.

Hello, pretty girl.   Is the problem solved?

**Comment by sloriot** [comment] 2019-06-19 05:25
@mirro187 please avoid this kind of comment and keep it professional. Thanks.
