### ISSUE TITLE
CGAL 5.2 Where is the Setup file?

### ISSUE THREAD

**Issue by petrasvestartas** [CGAL/cgal#5449] opened 2021-02-10 22:01 UTC
Hi,

I have previous version of CGAL 5.1.2.
What should I do to install the 5.2 version?
Before I used setup.exe file, but it is not here:
https://github.com/CGAL/cgal/releases

**Comment by lrineau** [comment] 2021-02-10 22:12
Duplicate of #5365

**Closed by lrineau** 2021-02-10 22:12 UTC
