### ISSUE TITLE
header-only installation fails: "cannot find build/include/CGAL"  (re: compiler_config.h)

### ISSUE THREAD

**Issue by RizzerOnGitHub** [CGAL/cgal#3100] opened 2018-05-19 05:07 UTC
There seems to be a change in the header-only configuration which breaks header-only installations of 4.12.  I'm comparing against 4.9.

I'm testing from the CGAL source dir with
`mkdir build; cd build`
`cmake -DCGAL_HEADER_ONLY=ON -DCMAKE_INSTALL_PREFIX:PATH=${PWD}/cgal-installdir ..`
`make install`

With 4.12, this installs header files into build/cgal-installdir/include/CGAL, but then gives an error:
`-- Up-to-date: /home/user/CGAL-4.12/build/cgal-installdir/include/CGAL/Linear_algebraCd.h`
`-- Up-to-date: /home/user/CGAL-4.12/build/cgal-installdir/include/CGAL/Triangulation_hierarchy_vertex_base_3.h`
`-- Up-to-date: /home/user/CGAL-4.12/build/cgal-installdir/include/CGAL/LEDA_basic.h`
`CMake Error at cmake_install.cmake:56 (file):`
`  file INSTALL cannot find
  "/home/user/CGAL-4.12/build/include/CGAL".`

`make: *** [Makefile:97: install] Error 1`

This error does not occur with 4.9 source.  The difference is that in 4.9, include/CGAL/compiler_config.h is created in the build dir, and installed by cmake_install.cmake (line 56).  

In 4.12, build/include/CGAL (and compiler_config.h) is not created, but cmake_install.cmake still contains the instruction to install the directory. Hence the error is generated, "cannot find".

It looks like after 4.9 was released you made a design decision to not create compiler_config.h for header-only builds, but haven't updated cmake_install.cmake to match that.

I'm testing on Linux 64 bit (Debian unstable) with cmake 3.11.1

**Comment by RizzerOnGitHub** [comment] 2018-05-19 05:19
The problem comes from l.893 in CMakeLists.txt,
`install(DIRECTORY ${CMAKE_BINARY_DIR}/include/CGAL     DESTINATION ${CGAL_INSTALL_INC_DIR} PATTERN ".svn" EXCLUDE)`

It looks like you don't want this line for header-only builds.

**Comment by lrineau** [comment] 2018-05-22 12:42
I can confirm the bug. The reason why we did not detect it is that, with the Git layout, a file `include/CGAL/version.h` is created in the build directory.

**Comment by lrineau** [comment] 2018-05-22 12:48
That should be fixed with the PR #3107. I hope to merge that soon in the branch targeting CGAL-4.12.1.

**Closed** 2018-05-25 08:46 UTC
Labels: CMake scripts, bug
