### ISSUE TITLE
CGAL 4.8 compilation failure "error: 'CGAL_assertion' was not declared in this scope"

### ISSUE THREAD

**Issue by etrinh** [CGAL/cgal#1024] opened 2016-04-20 09:50 UTC
Hi,

I have a compilation error while compiling CGAL 4.8 on Ubuntu 16.04,.
I figured out, that in my situation, cmake built the all_files.cpp with "CGAL/io.cpp" on the top of the list.
[all_files.zip](https://github.com/CGAL/cgal/files/227635/all_files.zip)

But in CGAL/IO/io.h:378, there is a usage of CGAL_assertion, but the "CGAL/assertions.h" seems never included, is it missing?

Thanks,
Best Regards,
Eric

**Comment by lrineau** [comment] 2016-04-20 09:57
I can confirm the bug. The fix is indeed the addition of:
```C++
#include <CGAL/assertions.h>
```
in `CGAL-4.8/include/CGAL/IO/io.h`.

**Comment by lrineau** [comment] 2016-04-20 10:03
The bug is tricky, and had not triggered any compilation error in the CGAL test suite, because that depends on the order of files on the filesystem, that impacts the result of the CMake command `file(GLOB..)`.

**Comment by lrineau** [comment] 2016-04-22 08:54
Fixed by #1025. Thanks.

**Closed by lrineau** 2016-04-22 08:54 UTC
Labels: bug
