### ISSUE TITLE
Shape_detection_3: Seemingly arbitrary stop criterion might abort too early

### ISSUE THREAD

**Issue by ochilan** [CGAL/cgal#2119] opened 2017-05-12 14:41 UTC
## Issue Details

In the `detect` function of `Efficient_RANSAC`, there is a forced exit criterion:
```
if (failed_candidates >= 10000)
  force_exit = true;
```
Is there a specific reason for this choice? Running the algorithm on more complex point clouds sometimes seems to overlook quite a lot of primitives that are otherwise detected when increasing this value. Should it be chosen proportionally to the total number of points or something the like?

## Environment

* Operating system: Arch Linux 64-bit
* Compiler: gcc
* Release or debug mode: Both
* CGAL version: 4.9.1
* Boost version: 1.63.0

**Comment by sgiraudot** [comment] 2017-05-16 11:58
A CGAL developer is currently doing a code review for the `Efficient_RANSAC` class as we noticed that it sometimes did not give satisfying result. Thank you for pointing this issue, this could be one of the reasons of these unsatisfying results.

I'll update this issue when the code review is done.

**Comment by lrineau** [comment] 2017-07-17 12:21
Simon, what is the status of this issue, now?

**Comment by sgiraudot** [comment] 2017-08-03 13:57
@danston from your experiments with the `Efficient_RANSAC` code, did it look like this hard-coded exit criterion had any effect on the output?

Would you have any intuition on how we could tune this parameter automatically? (Maybe, as OP suggested, proportionally to the number of points?)

**Comment by danston** [comment] 2017-08-03 14:07
Hi @sgiraudot I honestly did not see this parameter, so it might be a reason for some of my results to not converge. I will do a few experiments and let you know asap.

**Comment by danston** [comment] 2017-08-04 10:32
Ok, I did a few tests. Actually, with my data sets (since they are quite simple) I never hit this maximum value, but I agree, this hard-coded value is weird and for large data sets it can become a problem. The simplest idea, which comes to my mind, is to let users to change this parameter (like maximum number of iterations). If the solvers hits this maximum value, we can output the warning and let solver run for some extra time based, for example, on the number of remaining points (if it is bigger than some specified value in percents, we continue). I also like the idea of making this value proportional to the number of all points, but we have to test what is better and if Ransac still works well after this modification.

**Comment by sgiraudot** [comment] 2017-08-17 10:10
@ochilan what is the size of the data you used? Number of points and number of shapes? Are you sure you hit this arbitrary limit? RANSAC can miss shapes for many reasons, I just want to make sure this is the one.

I just ran some tests using quite large data sets (few million points, few thousands of shapes) and the limit was never hit. In average, `failed_candidates` seems to go up to around 45. The maximum I reached was around `9000`, which I agree is not far from the limit, but seems pretty rare. But maybe you used massive data sets (billions of points) and you hit the limit very quickly, and if that is the case, we need to handle it properly.

**Comment by sgiraudot** [comment] 2017-10-20 12:19
I can't reproduce the bug and in the absence of test data, I'm closing the issue. Do not hesitate to reopen it if you can provide some data to reproduce it.

**Comment by lrineau** [comment] 2017-11-09 18:56
Reopen. Will be fixed by #2590.

**Comment by lrineau** [comment] 2017-11-15 16:06
Fixed by #2590.

**Closed by lrineau** 2017-11-15 16:06 UTC
Labels: bug, Pkg::Point_set_shape_detection_3
