### ISSUE TITLE
Unable to wrap convex_hull_3 functions

### ISSUE THREAD

**Issue by Pranava29** [CGAL/cgal#2635] opened 2017-11-27 21:21 UTC
## Issue Details

Im trying to write wrappers to expose [convex_hull_3 method](https://doc.cgal.org/latest/Convex_hull_3/group__PkgConvexHull3Functions.html#gadc8318947c2133e56b2e56171b2ecd7d) in java. I wrote the code (as shown below) but i'm unable to generate the method in java after wrapping with swig.

I followed the instructions given [here](https://github.com/CGAL/cgal-swig-bindings/wiki) to generate the bindings.

The package for ```Convex_hull_3``` gets generated fine and it contains the file ```Convex_hull_3.java```, but the file doesn't have the method i want to wrap.

Please help

## Source Code
**```CGAL_Convex_hull_3.i```**
```%module (package="CGAL") CGAL_Convex_hull_3

%include "SWIG_CGAL/common.i"
Decl_void_type()
SWIG_CGAL_add_java_loadLibrary(CGAL_Convex_hull_3)

%import  "SWIG_CGAL/Common/Macros.h"
%import  "SWIG_CGAL/Kernel/CGAL_Kernel.i"
%include "SWIG_CGAL/Kernel/typedefs.h"
%include "SWIG_CGAL/Common/Iterator.h"

%{
  #include <SWIG_CGAL/Kernel/typedefs.h>
  #include  <SWIG_CGAL/Polyhedron_3/all_includes.h>
  #include <SWIG_CGAL/Common/Wrapper_iterator_helper.h>
  #include <SWIG_CGAL/User_packages/Convex_hull_3/convex_hull_3.h>
%}


%pragma(java) jniclassimports=%{
import CGAL.Kernel.Point_3;
import java.util.Iterator;
import CGAL.Polyhedron_3.Polyhedron_3;
%}

%pragma(java) moduleimports  =%{
import CGAL.Kernel.Point_3;
import java.util.Iterator;
import CGAL.Polyhedron_3.Polyhedron_3;
%}


#ifdef SWIG_CGAL_HAS_Convex_hull_3_USER_PACKAGE
%include "SWIG_CGAL/User_packages/Convex_hull_3/extensions.i"
#endif
```

**```CMakeLists.txt```**
```
SET (LIBSTOLINKWITH CGAL_Kernel_cpp)

ADD_SWIG_CGAL_JAVA_MODULE  (Convex_hull_3 ${LIBSTOLINKWITH})
```

**```convex_hull_3.h```**
```
#ifndef SWIG_CGAL_CONVEX_HULL_3_H
#define SWIG_CGAL_CONVEX_HULL_3_H

#include <CGAL/convex_hull_3.h>

template <class Kernel, class PointIterator, class Polyhedron_3>
void convex_hull_3(PointIterator point_begin, PointIterator point_end,
                              Polyhedron_3& out){
    CGAL::convex_hull_3( point_begin, point_end, out );
}

#endif //SWIG_CGAL_CONVEX_HULL_3
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): macOs Sierra 10.12.6
* CGAL version:4.11

**Comment by sloriot** [comment] 2017-11-28 07:38
Duplicate of https://github.com/CGAL/cgal-swig-bindings/issues/92

**Closed by sloriot** 2017-11-28 07:38 UTC
