### ISSUE TITLE
DT3 parallel performance loss

### ISSUE THREAD

**Issue by MaelRL** [CGAL/cgal#4388] opened 2019-12-02 09:23 UTC
## Issue Details

The commit https://github.com/CGAL/cgal/pull/3242/commits/2836828d612e6077f9d480ee9347f2b81d3fed18 results in my benches in a ~30% performance degradation of the parallel block. ba21ecb66a7f87449382bc36fe5db98c03f60c66 is the closest good commit.

## Source Code

```c++
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Delaunay_triangulation_3.h>
#include <CGAL/bounding_box.h>

#include <iostream>
#include <fstream>

typedef CGAL::Exact_predicates_inexact_constructions_kernel  K;
typedef K::Point_3                                           Point_3;

typedef CGAL::Triangulation_data_structure_3<
		  CGAL::Triangulation_vertex_base_3<K>,
	      CGAL::Triangulation_cell_base_3<K>,
		  CGAL::Parallel_tag>                                Tds;
typedef CGAL::Delaunay_triangulation_3<K, Tds>               PDT;

int main(int argc, char* argv[])
{
  CGAL::get_default_random() = CGAL::Random(0);
  std::cout << "seed:  " << CGAL::get_default_random().get_seed() << std::endl;

  std::vector<Point_3> points;
  Point_3 p;

  std::ifstream in(argv[1]);
  while(in >> p)
    points.push_back(p);

  std::cout << "Parallel" << std::endl;
  CGAL::Bbox_3 bb = CGAL::bounding_box(points.begin(), points.end()).bbox();
  PDT::Lock_data_structure locking_ds(bb, 50);

  PDT pdt(points.begin(), points.end(), &locking_ds);

  return 0;
}
```
with a `CGAL::Real_timer` in the header `Delaunay_triangulation_3.h` around the `tbb::parallel_for` code (lines ~380 and ~410). (The timer thus does include the spatial sort.)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Fedora 30 64, with `cpupower frequency-set --governor performance` and hyper-threading disabled
* Compiler: clang++-8
* Release or debug mode: Release
* Specific flags used (if any): None
* CGAL version: 4.13

**Comment by lrineau** [comment] 2019-12-03 09:19
The culprit is PR #3242, merged since 4.13. 

I can reproduce the slowdown, and I will change the implementation to remove that global atomic counter.

**Closed** 2019-12-17 08:21 UTC
Labels: Parallel_tag, Pkg::Triangulation_3, rm only: release blocker
