### ISSUE TITLE
compute_vertex_normals bug

### ISSUE THREAD

**Issue by simonasdmd** [CGAL/cgal#4298] opened 2019-10-17 01:32 UTC
_Please use the following template to help us solving your issue._

## Issue Details
How do you do. After I build the latest CGAL4.14, I call the simplification and calculation normal function.

I found that the call simplification function was normal. But when compute normals calls compute vertex normals. The compiler reported an error. There is an error prompt "unable to resolve external symbols". But compilation and build are normal. I want to know what caused it.

![image](https://user-images.githubusercontent.com/42527845/66970624-b30ef600-f0c0-11e9-8265-29ad2efa5422.png)

ps: My vs2017 include directory
![image](https://user-images.githubusercontent.com/42527845/66970697-eea9c000-f0c0-11e9-9062-fb3f0115f5d4.png)
My vs2017 additional library catalog
![image](https://user-images.githubusercontent.com/42527845/66970736-084b0780-f0c1-11e9-88bd-82fb8ed16ad4.png)

## Source Code

[main.txt](https://github.com/CGAL/cgal/files/3737021/main.txt)
Change "TXT" to "CPP"

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):win10 x64
* Compiler: vs2017
* Release or debug mode: Release 
* Specific flags used (if any):
* CGAL version: CGAL4.14
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): no

**Comment by janetournois** [comment] 2019-10-17 08:25
Hi,
so the error happens during compilation, right?
It looks like your target is not linked with GMP.
Can you please send your CMakeLists file, or try again with one example CMakeLists.txt from the package?

**Comment by simonasdmd** [comment] 2019-10-17 09:32
![image](https://user-images.githubusercontent.com/42527845/66996825-f6d71f00-f103-11e9-8473-7d8d3aa00a10.png)
hi，
This is the directory where I compiled CGAL. Which file is it, please?
@janetournois

**Comment by janetournois** [comment] 2019-10-17 10:53
You can use a CMakeLists file similar to [this one](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt)
for your cpp file.
Then, use CMake and compilation should be fixed.

**Comment by lrineau** [comment] 2019-10-17 11:07
This bug is exactly the same bug as https://github.com/CGAL/cgal/issues/4239, that you filled three weeks ago. The bug in not in CGAL, but in *your usage* of it.

If you compile a CGAL program with a solution that was not generated by CMake, then you have to make sure the GMP and MPFR libraries are included in the link. What you call the "library catalog" in the above screenshot is just a list of directories. The libraries themselves are listed in another tab of the project settings. @janetournois, can you tell us which one it is?

**Comment by lrineau** [comment] 2019-10-17 11:08
I close the issue, because that is not a bug of CGAL, as far as we know. But we can continue the discussion if you need help.

**Closed** 2019-10-17 11:09 UTC
Labels: not a bug

**Comment by janetournois** [comment] 2019-10-17 11:13
Sure!
The list of `*.lib` files (similar to `CGAL-4.6.1\auxiliary\gmp\lib\libgmp-10.lib` and `C:\dev\CGAL\CGAL-4.6.1\auxiliary\gmp\lib\libmpfr-4.lib`) should be available in "Project properties -> Linker -> input -> Additional dependencies."

**Comment by simonasdmd** [comment] 2019-10-18 03:16
@janetournois 
Thank you. I've solved the problem now. But I have a small problem. I want to compile the use cases that come with CGAL. I see this file in the directory. I want to compile it. I didn't find the corresponding project file generated after CMD executed "make..". Want to ask why.
I am a beginner. A lot of things are unknown. I want simple help. Thank you again.
![image](https://user-images.githubusercontent.com/42527845/67063205-77dff600-f198-11e9-9c02-ae3d53a8fb0f.png)

**Comment by janetournois** [comment] 2019-10-18 07:46
As mentioned in the CGAL manual (see [first section here](https://doc.cgal.org/latest/Manual/installation.html), you should use CMake, and run commands similar to those :
```
cd examples/Triangulation_2 # go to an example directory
cmake -DCGAL_DIR=$HOME/CGAL-4.14.1 . # configure the examples
make # build the examples 
```

**Comment by simonasdmd** [comment] 2019-10-18 07:55
![image](https://user-images.githubusercontent.com/42527845/67076286-6cec8c00-f1bf-11e9-9000-37bfe407095e.png)
![image](https://user-images.githubusercontent.com/42527845/67076293-7675f400-f1bf-11e9-9528-7a9e1ad1cd83.png)
@janetournois 
I have tried to configure "DCGAL_DIR" correctly. But then there was an error executing make. What else should I do?
![image](https://user-images.githubusercontent.com/42527845/67076427-b50bae80-f1bf-11e9-8f1a-97e90a54a95b.png)
