### ISSUE TITLE
Clip Visitor API

### ISSUE THREAD

**Issue by KeepFaithMe** [CGAL/cgal#4638] opened 2020-04-09 15:52 UTC
_Please use the following template to help us solving your issue._

## Issue Details

Dear developer:
      I have a problem that has been bothering me for a long time.When I used  the function named 'clip' to clip my mesh,there are many new faces generated.So I want to ask whether I can use the parameter 'visitor' to locate  which original face the newly generated face belongs to.As the picture shows:
![sketch map](https://user-images.githubusercontent.com/32037166/78913488-aab9d580-7abb-11ea-98c1-ed38b795a7b7.png)
   I mean when the face ABC has been cliped,the face ABD,ADE,DEC generated,I just want to konw ,through the parameter visitor,whether I can get the face_descriptor about the original face ABC, and at the same time,whether I can get the face_descriptor ABD,ADE,DEC.
I konw I have asked this question,and you answer me,but I'm still not sure if this will get me the information I want.So please give me some advice,It is very important to me.
Looking forward to you reply!
Good Luck!

## Source Code

_If your issue arises by using CGAL in your own source code, please provide a minimalist example that we can compile easily to reproduce the bug. If your issue arises from using a CGAL program (demo, example, etc.), please let us know which one. Helping you solving an issue is much easier and efficient if we can reproduce it._

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by sloriot** [comment] 2020-04-10 08:30
Duplicate of https://github.com/CGAL/cgal/issues/4601 ?

**Comment by KeepFaithMe** [comment] 2020-04-10 10:09
I am not sure when I use the parameter 'visitor',can I get the face_descriptor of the original face ABC in the input mesh and get the face_descriptor of the new face ABD,ADE,DEC in the output mesh?.Because when I use the parameter 'visitor',the result I got It's not I want. So I ask you again.Please forgive my ignorance.
Thank you again.

**Comment by sloriot** [comment] 2020-07-20 06:31
You will get `ABC` in [`before_subface_creations(face_descriptor f_split, Triangle_mesh &tm)`](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html#a2afc4ebcac7124365807b9aa04a7a3dd) and after the split the `f_split`descriptor will be one amongst `ABD`, `ADE`, `DEC`, the two remaining ones will be reported in [`after_subface_created (face_descriptor f_new, Triangle_mesh &tm)`](https://doc.cgal.org/latest/Polygon_mesh_processing/classPMPCorefinementVisitor.html#a51a2222bdcadf27fecfd8c3862300d0b).

**Closed by sloriot** 2020-07-20 06:31 UTC
Labels: Pkg::PMP, question
