### ISSUE TITLE
Example StraightSkeleton delivers wrong results

### ISSUE THREAD

**Issue by MatthiasThDs** [CGAL/cgal#4799] opened 2020-06-19 15:09 UTC
Hi, I installed Cgal 5.1-beta1 via Installer and downloaded the Examples 5.02 from here https://github.com/CGAL/cgal/releases/download/releases/CGAL-5.0.2/CGAL-5.0.2-examples.zip
Sadly the Example Straight_skeleton_2/Show_offset_polygon.cpp is not working correctly. It runs but gives wrong results for your included sample file "sample_2.dat". I tested the file because I also get wrong results with my own input data. Here is how the result looks like:

![image](https://user-images.githubusercontent.com/50454126/85147464-35067e80-b24f-11ea-9200-7e9bc548eff6.png)

The other included sample-files work.

## Environment
Running with: Show_offset_polygon.exe sample_2.dat
I was checking the result in Adobe Photoshop

* Operating system (Windows 64 bits):
* Compiler: Visual Studio 2019 16.0.3 
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 5.1beta
* Boost version: 1.73.0
* Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MatthiasThDs** [comment] 2020-06-19 15:16
Can i switch to another version where this works? Should i try the master? or the 4.1 releases? Its a bit urgent to be honest.

**Comment by sloriot** [comment] 2020-08-06 09:07
The issue is that the file was invalid. It was fixed in d02461350131beb017e93e9bb32cc179ed8eeea4 that is only in the 5.1 branch. So if you use the file from a 5.0 branch with 5.1 it will not work.

**Closed by sloriot** 2020-08-06 09:07 UTC
Labels: Pkg::Straight_skeleton_2
