### ISSUE TITLE
Bug in "Split selected polyhedra"

### ISSUE THREAD

**Issue by palliez** [CGAL/cgal#6479] opened 2022-04-06 15:58 UTC
## Issue Details

in the polyhedron demo - I load a mesh (ply binary format) with many connected components - I would say few hundreds. 
alas the model is confidential (frigate) - I can only show a video privately. 

I then select the menu "Split selected polyhedra"

I get a crash.

the menu "color per component" works.

## Environment

* Operating system : Windows 10 64 bits
* Compiler: I use the precompiled version of the demo 5.3-I-162

**Comment by palliez** [comment] 2022-04-12 11:26
PS: the following code does work, hence it seems like this is an issue with rendering, VBOs buffers, etc

#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/connected_components.h>
#include <CGAL/Polygon_mesh_processing/IO/polygon_mesh_io.h>

#include <CGAL/Timer.h>
#include <CGAL/bounding_box.h>




// kernel
using Kernel = CGAL::Exact_predicates_inexact_constructions_kernel;
using FT = Kernel::FT;
using Point_3 = Kernel::Point_3;
using Plane_3 = Kernel::Plane_3;
using Vector_3 = Kernel::Vector_3;
using Segment_3 = Kernel::Segment_3;
using Triangle_3 = Kernel::Triangle_3;
using Iso_cuboid_3 = Kernel::Iso_cuboid_3;


// surface mesh
using Surface_mesh = CGAL::Surface_mesh<Point_3>;



// usage
void usage()
{
    std::cout << "Split mesh into components\n"
        "Usage: split -i input_mesh" <<
        "Reads OFF/STL/OBJ/PLY/TS/VTP files only. \n";
}


int main(int argc, char** argv)
{
    const int argc_check = argc - 1;
    char* mesh_file_name_ptr = nullptr;

    // parse parameters
    for (int i = 1; i < argc; ++i)
    {
        if (!strcmp("-h", argv[i]))
        {
            usage();
            return EXIT_FAILURE;
        }
        else if (!strcmp("-i", argv[i]) && i < argc_check) 
            mesh_file_name_ptr = argv[++i];
    }


    // read input mesh
    Surface_mesh input_mesh;
    std::string mesh_file_name(mesh_file_name_ptr);
    std::cout << "read mesh...";
    if (!CGAL::Polygon_mesh_processing::IO::read_polygon_mesh(mesh_file_name, input_mesh) ||
        is_empty(input_mesh) ||
        !is_triangle_mesh(input_mesh))
    {
        std::cerr << "Invalid mesh input" << std::endl;
        return EXIT_FAILURE;
    }
    std::cout << "done (" << input_mesh.number_of_faces() << " facets)" << std::endl;

    // split connected components
    std::list<Surface_mesh> components;
    std::cout << "split into components...";
    CGAL::Polygon_mesh_processing::split_connected_components(input_mesh, components);
    std::cout << "done (" << components.size() << " components)" << std::endl;

    // save components
    int index = 0;
    std::list<Surface_mesh>::iterator it;
    for (it = components.begin(); it != components.end(); it++, index++)
    {
        Surface_mesh& mesh = *it;

        // generate file name
        std::string name("component-");
        name.append(std::to_string(index)).append(".ply");

        // save component to file
        std::cout << "save to file " << name << "...";
        if (!CGAL::IO::write_polygon_mesh(name, mesh, CGAL::parameters::stream_precision(17)))
        {
            std::cout << "unable to write output mesh" << std::endl;
            return EXIT_FAILURE;
        }
        std::cout << "done" << std::endl;
    }

    return EXIT_SUCCESS;
}

**Comment by sloriot** [comment] 2022-04-12 15:10
I believe the issue comes from the fact that the model contains more than 10000 connected components. We know that split  is not as fast as it should be in such cases. Note also that there is a slow down due to a regression in `compute_vertex_normal` too.

**Comment by afabri** [comment] 2022-04-12 15:14
Is the split in many surface meshes not fast, or the management of so many items in the demo?  In the demo I am also wondering what you want to do with so many items.  Keep the largest one?  Keep all larger than a certain size?

**Comment by afabri** [comment] 2022-04-12 20:48
No wonder that it is slow as the meshes get written into a `std::vector` of meshes that is we copy them when we double the size of the vector, and then this vector of meshes gets sorted that is we swap n log n times meshes.  Too late to fix that today, but certainly tomorrow.

**Comment by lrineau** [comment] 2022-04-27 19:36
Fixed by #6489.

**Closed by lrineau** 2022-04-27 19:36 UTC
Labels: bug, CGAL 3D demo, Has Pull Request
