### ISSUE TITLE
Replace the use of boost::mutex by something else

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal#273] opened 2015-08-14 03:06 UTC
Together with #271, the goal is to remove Boost.Thread as a dependency of CGAL, and thus use Boost as headers-only.

For that, we must replace the two/three usages of `boost::mutex` (from Boost.Thread) by something else

In C++11 and later, there is `std::mutex`. On Windows, we can use it from MSVC 2012 (VC11). But we still support VC10.

What about non-C++11 platforms?

**Comment by bo0ts** [comment] 2015-08-17 14:51
We use a mutex in `Kd_tree` and `AABB_tree` and I think both of those usages are caused by design bugs in the data structures.

There is no good reason to maintain a built/not built state within the data structure. The input data should always be defined in the constructor and the constructor should build the data structure. A `rebuild` method (like `AABB_tree::rebuild` and `Kd_tree::insert`) is also unnecessary: you can always reinitialize an object via the copy constructor.

This idiom also adds unnecessary bloat to the objects (a bool, a mutex, a heap allocation) and complexity to the interface.

We should investigate if we can iterate the interfaces without too much impact on users (or provide a derived class with backwards compatibility). For `Kd_tree` this should be possible without too much work, but much harder for `AABB_tree`.

**Comment by afabri** [comment] 2015-09-04 07:22
It is always great to have ambitions, but  I still want to harvest a low hanging fruit,  as getting boost.thread is a hassle for VC++ users.   
I even limit the effort to only switch to std::  for VC++.
I started on the branch  cgal-dev/CGLAL-thread_local_storage-GF

**Comment by afabri** [comment] 2015-09-04 07:36
@cjamin   I saw that we also use tbb:mutex etc
Is that better than boost/std?
Can we use this in case tbb is enabled, even were we do not parallelize code ourselves?

**Comment by cjamin** [comment] 2015-09-04 08:36
I don't think it's really better or worse, but when parallelizing a code using TBB, I like to use TBB everywhere instead of mixing TBB and boost. TBB being specialized at this task, it seems a more natural choice than boost anyway. And it offers more flavors: https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Mutex_Flavors.htm

TBB doesn't offer timed mutex, though (see why here: https://software.intel.com/en-us/blogs/2008/09/17/pondering-timed-mutex (2008)).

And yes, we can use TBB instead of boost wherever we want if it's available.

**Comment by lrineau** [comment] 2015-09-04 09:57
Note that this bug is about  our uses of `boost::mutex`.

The bug about thread-local storage (our use of Boost.Thread for TLS) is #271.

**Comment by sloriot** [comment] 2015-11-23 23:50
See #493

**Comment by sloriot** [comment] 2016-02-02 08:45
@afabri Can we close this issue?

**Comment by afabri** [comment] 2016-02-02 09:53
We can close it.

**Closed** 2016-02-02 12:21 UTC
Labels: C++11, enhancement
