### ISSUE TITLE
Installation problem: -- libCGAL_Qt5 is missing the dependencies:  Qt5Svg Qt5 cannot be configured.

### ISSUE THREAD

**Issue by neuronphysics** [CGAL/cgal#1781] opened 2016-12-23 12:46 UTC
I am trying to install the latest version of cgal in a pc that I don't have root permission. When I run 
`cmake .`
I am getting the following error  

```
libCGAL_ImageIO is configured
-- Sources for CGAL component library 'CGAL_Qt5' detected
Configuring libCGAL_Qt5
-- libCGAL_Qt5 is missing the dependencies:  Qt5Svg Qt5 cannot be configured.
-- Sources for CGAL component libraries 'CGAL_Core;CGAL_ImageIO;CGAL_Qt5' detected

```
and inside CMakeCache.txt these things are missing 

```
//Path to a file.
OPENGL_xmesa_INCLUDE_DIR:PATH=OPENGL_xmesa_INCLUDE_DIR-NOTFOUND
//The directory containing a CMake configuration file for Qt5Svg.
Qt5Svg_DIR:PATH=Qt5Svg_DIR-NOTFOUND
//Path to a file.
X11_Xaccessrules_INCLUDE_PATH:PATH=X11_Xaccessrules_INCLUDE_PATH-NOTFOUND
//Path to a file.
X11_Xkbfile_INCLUDE_PATH:PATH=X11_Xkbfile_INCLUDE_PATH-NOTFOUND
//Path to a library.
X11_Xkbfile_LIB:FILEPATH=X11_Xkbfile_LIB-NOTFOUND
//Path to a library.
X11_Xxf86misc_LIB:FILEPATH=X11_Xxf86misc_LIB-NOTFOUND
//Path to a file.
X11_xf86misc_INCLUDE_PATH:PATH=X11_xf86misc_INCLUDE_PATH-NOTFOUND

```
I will appreciate if I would get some suggestions about how to fix the bugs during installation!

**Comment by sloriot** [comment] 2016-12-23 15:44
You can try the header only version (look for HEADER_ONLY in `CMakeCache.txt`) but this will simply delay the pb of missing dependencies you have to when you'll try to compile a demo.

**Comment by sloriot** [comment] 2016-12-23 15:45
Or you can also do not compile `CGAL_Qt5`, which is what should be done by the `CMakeLists.txt` if some dependencies are missing

**Comment by lrineau** [comment] 2016-12-23 15:50
Anyway, Qt5 missing is not an error: the message just says that CGAL_Qt5 will not be available. Without a full installation of Qt5, anyway you cannot use it.

**Comment by neuronphysics** [comment] 2016-12-23 15:51
My `CMakeLists.txt` looks like this:
```
# Top level CMakeLists.txt for CGAL-branchbuild
message( "== CMake setup ==" )
project(CGAL CXX C)

# Minimal version of CMake:
cmake_minimum_required(VERSION 2.8.11)

# option for branch build

option( CGAL_BRANCH_BUILD "Create CGAL from branch" ON)
mark_as_advanced( CGAL_BRANCH_BUILD )

include(${CMAKE_SOURCE_DIR}/Installation/cmake/modules/CGAL_SCM.cmake)

# add option for duplicate file detection
option( CGAL_REPORT_DUPLICATE_FILES "Switch on to start (naive) detection of duplicate source- and headerfiles in packages" OFF)

message( "== CMake setup (DONE) ==\n" )
# and finally start actual build
add_subdirectory( Installation )
add_subdirectory( Documentation/doc)
```
How can I compile it without `CGAL_Qt5`?

**Comment by lrineau** [comment] 2016-12-23 15:52
Just do nothing and go on with the compilation. CGAL libraries but CGAL_Qt5 will be compiled.

**Comment by neuronphysics** [comment] 2016-12-23 15:53
If I would like to install it without administrative privileges, what command line do I need to run?

**Comment by sloriot** [comment] 2016-12-23 16:00
No need to install it. Simply set CGAL_DIR to the path where `make` was called.

**Comment by sloriot** [comment] 2016-12-23 16:01
Roughly this is what it is explained here:
http://doc.cgal.org/latest/Manual/installation.html#title0

**Comment by neuronphysics** [comment] 2016-12-23 16:11
so is it right to use the following command lines??
```
cmake -DCGAL_DIR=/vol/data1/.local/ .
make
make DESTDIR=/vol/data1/.local/ install
```

**Comment by neuronphysics** [comment] 2016-12-23 16:58
In addition, I actually would like to use python wrapper for cgal library and when I try to build it I get the following error messages:
```
python setup.py build --build-base=/vol/data2/anaconda/                                  
running build
running build_py
creating /vol/data2/anaconda/lib.linux-x86_64-2.7
creating /vol/data2/anaconda/lib.linux-x86_64-2.7/CGAL
copying cgal_package/CGAL/__init__.py -> /vol/data2/anaconda/lib.linux-x86_64-2.7/CGAL
copying cgal_package/CGAL/pythonstartup.py -> /vol/data2anaconda/lib.linux-x86_64-2.7/CGAL
running build_ext
building 'CGAL/Alpha_shapes_2' extension
creating /vol/data2/anaconda/temp.linux-x86_64-2.7
creating /vol/data2/anaconda/temp.linux-x86_64-2.7/bindings
creating /vol/data2/anaconda/temp.linux-x86_64-2.7/bindings/Alpha_shapes_2
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/vol/data1/.local/include:-I/vol/data1/.local/include: -fPIC -DCGAL_DONT_USE_LAZY_KERNEL -I../.. -I/vol/data1/zahra/cgal-python-0.9.4-beta1 -I/usr/include/python2.7 -c bindings/Alpha_shapes_2/Alpha_shapes_2_module.cpp -o /vol/data2/anaconda/temp.linux-x86_64-2.7/bindings/Alpha_shapes_2/Alpha_shapes_2_module.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
bindings/Alpha_shapes_2/Alpha_shapes_2_module.cpp:21:24: fatal error: CGAL/basic.h: No such file or directory
 #include <CGAL/basic.h>
                        ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
I reckon the problem occurs because of the dependencies that I have ignored in the first step.

**Comment by sloriot** [comment] 2016-12-23 18:27
Please read the section I mentioned, there is no need to install CGAL. Once you have extracted the source and successfully called `cmake` and `make`, the current directory is a valid installation of CGAL.
I don't know which bindings you are talking about. The one I know, https://github.com/cgal/cgal-swig-bindings, requires a `CGAL_DIR` environment variable to be set to the path where CGAL was compiled. I close this issue since it is not a bug report. Such a question should have been posted on cgal-discuss. Please read http://www.cgal.org/mailing_list.html

**Closed by sloriot** 2016-12-23 18:27 UTC
