### ISSUE TITLE
Error C3861: "is_valid" identifier not found when using CGAL as a header-only library in Visual Studio C++ project

### ISSUE THREAD

**Issue by DawidLokiec** [CGAL/cgal#7572] opened 2023-07-05 05:30 UTC
I'm encountering an error in my Visual Studio C++ project when using CGAL library. The error message I'm getting is:

**Error C3861 "is_valid": identifier not found. Lib C:\**\CGAL-5.5.2\include\CGAL\long_double.h 149**

Here are the steps I followed to include CGAL in my existing project:

 1. I downloaded the CGAL-5.5.2 zip file from the official GitHub repository at https://github.com/CGAL/cgal/releases/tag/v5.5.2.
 2. I extracted the contents of the zip file and replaced the "auxiliary" folder with the one from the "GMP and MPFR libraries, for Windows 64bits.zip" file, as mentioned in the documentation.
 3. In Visual Studio, I added "CGAL-5.5.2\auxiliary\gmp\include" and "CGAL-5.5.2\include" as additional include directories.
 4. I also added "CGAL-5.5.2\auxiliary\gmp\lib" as an additional library directory.
 5. Finally I added libgmp-10.lib and libmpfr-4.lib as additional linking dependencies.

As a result I included CGAL as a header-only library in my existing Visual Studio C++ project **without** executing `cmake`, because the documentation says:
>Since version 5.0, CGAL is a header-only library, meaning that it is no longer needed to build CGAL libraries before it can be used.

However, when I try to build my project, I'm getting the following error:
**Error C3861 "is_valid": identifier not found. Lib C:\**\CGAL-5.5.2\include\CGAL\long_double.h 149**

I have discovered that manually setting the `CGAL_CFG_IEEE_754_BUG` preprocessor macro resolves the issue, but I am hesitant to configure such settings manually. My concern arises from the fact that this configuration is not mentioned anywhere in the documentation, and I am unsure if it could potentially lead to other "hard-to-diagnose" issues in the future. It was during my search for the definition of "is_valid" that I came across the `CGAL_CFG_IEEE_754_BUG` macro.

I would greatly appreciate any advice or suggestions on how to resolve this error and successfully use CGAL as a header-only library in my Visual Studio C++ project without the need for manual configuration.

I am looking for a reliable and documented approach to ensure the correct usage of CGAL in my Visual Studio C++ project.

Thank you for your assistance!

**Comment by sloriot** [comment] 2023-07-05 07:04
This flags is set when using cmake and compiling the test `cmake/modules/config/testfiles/CGAL_CFG_IEEE_754_BUG.cpp`. What you can do is compile one example using cmake and collect those _CFG_ macros that are set and for example define then in a header file `CGAL_cmake_config_flags.h` to make it clear where this comes from.

**Comment by lrineau** [comment] 2023-07-05 10:44
`<CGAL/long_double.h>` should include `<CGAL/utils.h>`, that defines `CGAL::is_valid`. I wonder why our tests do not catch that issue.

**Comment by DawidLokiec** [comment] 2023-07-05 11:01
> `<CGAL/long_double.h>` should include `<CGAL/utils.h>`, that defines `CGAL::is_valid`. I wonder why our tests do not catch that issue.

From my practical experience: "You probably set the flag in the test environment"?

**Comment by afabri** [comment] 2023-07-20 10:36
@DawidLokiec  I can just make a PR where I add the `#include` as suggested by Laurent, but I would be glad if you could give me a minimal example so that I can first reproduce your findings.

**Comment by lrineau** [comment] 2023-07-20 11:01
> `<CGAL/long_double.h>` should include `<CGAL/utils.h>`, that defines `CGAL::is_valid`. I wonder why our tests do not catch that issue.

`<CGAL/long_double.h>` is tested by our CI. See last run on `master`: https://github.com/CGAL/cgal/actions/runs/5609091595/jobs/10262330817#step:4:5762

I wonder how @DawidLokiec was able to get the error
```
 Error C3861 "is_valid": identifier not found. Lib C:**\CGAL-5.5.2\include\CGAL\long_double.h 149
```

**Comment by afabri** [comment] 2023-07-21 08:55
`<CGAL/utils.h>   IS included.   When I [search](https://github.com/search?q=repo%3ACGAL%2Fcgal+CGAL_CFG_IEEE_754_BUG&type=code&p=2) for `CGAL_CFG_IEEE_754_BUG`  I don't see any `#define` but only occurences in `CMakeCache`.

**Comment by lrineau** [comment] 2023-07-21 08:56
`CGAL_CFG_IEEE_754_BUG` is currently useless with all the compilers we support.

**Comment by afabri** [comment] 2023-07-21 09:02
You are right, there is also an `Is_valid`  struct in the `#else` case.   However fact is that<CGAL/utils.h> IS included.

**Comment by DawidLokiec** [comment] 2023-07-21 09:09
@afabri @lrineau I only get the error when I add CGAL to my project as header-only **without** (!) having CMake configured. If I configure CMake beforehand, I can't reproduce the error. maybe that helps you.

**Comment by lrineau** [comment] 2023-07-21 09:18
@DawidLokiec Unless you manage to produce a minimal example reproducing the issue, we cannot help, because it does seem to be specific to your setup.

I am close this issue as "not a bug".

**Closed by lrineau** 2023-07-21 09:18 UTC
Labels: bug, not a bug, Pkg::Number_types

**Comment by afabri** [comment] 2023-07-21 09:31
What CGAL header do you include in your program?  I just created an empty VC++ project added include paths to CGAL, boost, and gmp.  The following code compiles:
```
#include <CGAL/long_double.h>
#include <cassert>

int main()
{
  long double ld = 0;
  assert(CGAL::is_valid(ld));
  return 0;
}
```

**Comment by afabri** [comment] 2023-07-24 15:48
@DawidLokiec  PING !!!
