### ISSUE TITLE
Polyhedron demo plugins expecting points with normals

### ISSUE THREAD

**Issue by afabri** [CGAL/cgal#1520] opened 2016-09-29 13:47 UTC
... should check that the normals are not zero

I loaded a file of points with normals, run WLOP, run Poisson.  As WLOP sets the normals to NULL_VECTOR, Poisson hangs forever.

**Comment by sloriot** [comment] 2016-09-29 13:54
Note that the class `Scene_points_with_normal_items` has a member function `has_normals()`.
I guess the pb was reintroduced when @sgiraudot merged the 3 reconstruction methods into a single plugin. IIRC, before poisson plugin was using this function in the `applicable()` function.

**Comment by sgiraudot** [comment] 2016-09-30 05:18
> I guess the pb was reintroduced when @sgiraudot merged the 3 reconstruction methods into a single plugin. IIRC, before poisson plugin was using this function in the applicable() function.

If the points don't have normals, they are computed before Poisson is called, so there's no regression introduced.

Andreas was talking about the case when the point set has normals (so `has_normals()` return `true`) but they are 0. It seems to me that the bug here is in WLOP: if it sets all normals to 0, it would make more sense to turn `has_normals()` to false.

**Comment by sgiraudot** [comment] 2016-09-30 07:09
Okay, it turns out there are 2 bugs:
* WLOP should put `has_normals()` to false
* Poisson plugin should not only estimate normals but also orient them

I'm working on a fix right now.

**Comment by lrineau** [comment] 2016-10-05 13:06
Fixed by #1525.

**Closed** 2016-10-05 13:06 UTC
Labels: bug, CGAL 3D demo, Pkg::Point_set_processing_3
