### ISSUE TITLE
Segment_voronoi_2 demo: program crashed on two polygon data  

### ISSUE THREAD

**Issue by ycctsinghua** [CGAL/cgal#414] opened 2015-10-10 04:00 UTC
We ran some big polygon data based on demo Segment_voronoi_2. But two of them crashed. The data can be downloaded from http://cg.cs.tsinghua.edu.cn/people/~Yongjin/polydata.zip.

**Comment by afabri** [comment] 2015-10-13 13:52
Hello,
I downloaded your data sets, and I constructed successfully a Segment Delaunay graph with the program I've put here: https://gist.github.com/afabri/b50fa1740f3341bafa7d

I also noticed that your data has intersecting segments.

**Comment by ycctsinghua** [comment] 2015-10-13 15:31
Hi, afabri. Thanks for your answer. We tested our polygon data based on demo "Segment_voronoi_2", which can be found in the installation path "./CGAL-4.X/demo/Segment_Delaunay_graph_2". And it indeed crashed. After reading your program, I think the problem may be the construction of the dual of Delaunay graph or the displaying part related to Qt4. Anyway, thanks for your reply and we will check it in our future work.

**Comment by afabri** [comment] 2015-10-13 17:13
I confirm that the demo produces a segfault. I will investigate.

**Comment by sloriot** [comment] 2016-03-02 19:26
@afabri Any update on this issue?

**Comment by afabri** [comment] 2016-03-02 19:29
no

**Comment by afabri** [comment] 2016-03-03 10:36
I extracted the typedefs from the demo, and some points from the data set, and condensed it into [this](https://gist.github.com/afabri/043987203bbc6cf508cc) minimal example that crashes with master with ERROR: division by zero.

**Comment by sloriot** [comment] 2016-03-03 13:45
This is an old bug, I could reproduce the error as least CGAL 3.7

**Comment by lrineau** [comment] 2016-03-03 14:57
4.7 or 3.7?

**Comment by sloriot** [comment] 2016-03-03 15:02
3.7

**Comment by sloriot** [comment] 2016-03-03 16:47
Actually I suspect a bug in CORE::Expr or something related.

**Comment by sloriot** [comment] 2016-03-04 05:40
When compiled with  `leda::real`, the example worked for me.

**Comment by sloriot** [comment] 2016-03-04 08:00
Here is a minimal [example](https://gist.github.com/sloriot/dd7e28f54b1c10ae9d44) that is not using the segment Voronoi package.
In this example, the four expression printed should return the same value (false) which is not true for one of them with `CORE::Expr`

**Comment by afabri** [comment] 2016-03-04 15:41
An even more minimalist [example](https://gist.github.com/afabri/043987203bbc6cf508cc) drills the problem down to a bug in the fork of the Core library shipped with CGAl, that deals with exact numbers with square roots.

**Comment by lrineau** [comment] 2016-03-14 14:50
Is not there a way to "fix" that bug by using `Lazy_exact_nt<CORE::Expr>` instead of `CORE::Expr`?

**Comment by lrineau** [comment] 2016-03-15 10:44
It seems nobody tries to fix that bug before CGAL-4.8 is released. I change its milestone...

**Comment by sgiraudot** [comment] 2016-10-28 06:10
Is anybody able/available to take care of this issue?

**Comment by lrineau** [comment] 2017-02-23 17:40
@sloriot said this bug is now fixed since #1923.

**Closed by lrineau** 2017-02-23 17:40 UTC
Labels: bug, Pkg::CGAL_Core, stalled
