### ISSUE TITLE
CGAL_INSTALL variables seem to not support absolute paths

### ISSUE THREAD

**Issue by haslersn** [CGAL/cgal#4915] opened 2020-08-07 16:30 UTC
On NixOS `CGAL_INCLUDE_DIRS`, `CGAL_MODULES_DIR` and `CGAL_LIBRARIES_DIR` is wrong and leads to an error like the following.

```
CMake Error at /nix/store/wrzd7ayy6fzk05m5qslgmxm9vihc07vq-cgal-4.14.2/lib/cmake/CGAL/CGALConfig.cmake:87 (include):
  include could not find load file:

    /nix/store/wrzd7ayy6fzk05m5qslgmxm9vihc07vq-cgal-4.14.2//nix/store/wrzd7ayy6fzk05m5qslgmxm9vihc07vq-cgal-4.14.2/lib/cmake/CGAL/CGAL_SetupBoost.cmake
```

Of course one can argue that this is a nixpkgs issue and not a cgal issue. However, I believe that something is inherently wrong with the code [here](https://github.com/CGAL/cgal/blob/d3b9d89596ab78bc72e883d1afa423452e55c80f/Installation/cmake/modules/CGALConfig_install.cmake.in#L48) that sets those variables. For me it looks like this code does not support having absolute paths in `CGAL_INSTALL_INC_DIR`, `CGAL_INSTALL_CMAKE_DIR` and `CGAL_INSTALL_LIB_DIR`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): NixOS 20.03
* Compiler: N/A
* Release or debug mode: Release
* Specific flags used (if any): _none_
* CGAL version: `4.14.2`
* Boost version: `1.69.0`
* Other libraries versions if used (Eigen, TBB, etc.): _unrelated_

**Comment by sloriot** [comment] 2020-08-11 05:03
I suspect this ticket is a duplicate of #4433. Could you somehow try with  CGAL-5.1-beta2 to see if the issue is fixed?

**Comment by MaelRL** [comment] 2020-09-22 10:39
Bump @haslersn

**Comment by haslersn** [comment] 2020-09-28 11:38
I currently can't easily reproduce this, because my distribution fixed the issue with this patch: https://github.com/NixOS/nixpkgs/pull/94875/files

**Comment by lrineau** [comment] 2020-09-29 08:06
Actually, `CGAL_INSTALL_INC_DIR`, `CGAL_INSTALL_CMAKE_DIR`, and `CGAL_INSTALL_LIB_DIR` are documented to be relative paths:
https://github.com/CGAL/cgal/blob/afc0abb82f341e5dadaae545dc3ac51d30a8f5dc/Installation/CMakeLists.txt#L711-L712
https://github.com/CGAL/cgal/blob/afc0abb82f341e5dadaae545dc3ac51d30a8f5dc/Installation/CMakeLists.txt#L723-L725

It is true that our code does not support absolute paths. As a workaround, if you want to use absolute paths, then set `CMAKE_INSTALL_PREFIX` to the empty string.

And, anyway, we plan to drop support for non-header-only version of CGAL soon. That code will disappear.

**Closed by lrineau** 2020-09-29 08:07 UTC
Labels: CMake scripts, waiting for answer, wontfix
