### ISSUE TITLE
Polygon_Mesh_Processing Error

### ISSUE THREAD

**Issue by bradrothenberg** [CGAL/cgal#266] opened 2015-08-12 04:48 UTC
Hi,

I am trying to compile the Polygon_Mesh_Processing hole filling example, & I am receiving the following error:

'CGAL::Polygon_mesh_processing::internal::Fair_Polyhedron_3<PolygonMesh,SparseLinearSolver,WeightCalculator,VertexPointMap>::Sparse_linear_solver': must be a class or namespace when followed by '::'	Alpha2	C:\lib\CGAL\include\CGAL\Polygon_mesh_processing\internal\fair_impl.h	50

I am using VisualStudio 2015, vc140 --

are there any .cpp files that need to be compiled for the Polygon_Mesh_Processing to work properly?

**Comment by lrineau** [comment] 2015-08-12 05:58
Hi, we have been testing MSVC 2015 only very recently, and we know that there are new compilation errors with that version of MSVC. We hope to solve that kind of compilation error with MSVC 2015 before the next beta release CGAL-4.7-beta1, that should be published in less than two weeks). We will let you know here as soon as we have a patch.

Cc @janetournois, who do the MSVC 2015 testing. Maybe we already have a patch in hand.

**Comment by bradrothenberg** [comment] 2015-08-12 06:16
Thank You!

**Comment by janetournois** [comment] 2015-08-13 12:46
Hi,

thanks for your report.

I am currently testing vs2015 and I am not having any trouble with this example... can you please tell us what is your configuration?
Your versions of Eigen could be a clue...

Is it hole_filling_example.cpp that does not compile for you?

thanks

**Comment by janetournois** [comment] 2015-08-13 13:07
Hi again,
to answer your original question : CGAL itself must be built before building examples.

**Comment by bradrothenberg** [comment] 2015-08-13 16:54
Hi Jane -- 

I am trying to build the hole_filling_example.cpp -- my config is vs2015, x64 on windows 8.1, CGAL 4.7.1 -- we are using Eigen 3.1, & boost 1.59.

I have another machine with windows 10, & am getting the same compile-time error.

I have no problem compiling & running triangulate_polyline_example.cpp.

Thank You!

**Comment by janetournois** [comment] 2015-08-13 16:57
Can you please try to use the latest version of Eigen? (I am using 3.2.5)

**Comment by bradrothenberg** [comment] 2015-08-13 17:17
I just upgraded Eigen to 3.2.5, & am getting the same compile-time error. 

It doesn't know what SparseLinearSolver is:
Severity	Code	Description	Project	File	Line
Error	C2510	'Sparse_linear_solver': left of '::' must be a class/struct/union
 -- is there a place where the Fair_Polyhedron_3 function is called where the template parameters need to be defined?

**Comment by janetournois** [comment] 2015-08-14 12:27
Hi again,

I am still suspecting the Eigen version, because we have in fair.h a hack that prevents compilation of fairing by replacing the solver by a dummy "bool" when the Eigen version is < 3.2.

Can you check, in fair.h in particular, the status of macros CGAL_EIGEN3_ENABLED, and check (in fair.h, inside function "fair", at line 104), that Default_solver is the Eigen_solver, and not "bool"?

thanks!

**Comment by bradrothenberg** [comment] 2015-08-14 15:04
Hi Jane --

This now compiles. I didn't have the macro CGAL_EIGEN#_ENABLED. Thank You

Brad

**Comment by janetournois** [comment] 2015-08-14 15:06
Great! :-)

**Comment by lrineau** [comment] 2015-08-15 06:53
I think the compilation error should tell more explicitly that the issue is the lack of Eigen3.

**Comment by janetournois** [comment] 2015-08-17 10:32
I proposed a solution to avoid this problem to happen again in pull request #277

**Comment by lrineau** [comment] 2015-08-19 15:06
It is already fixed in `master`, and will be fixed in CGAL-4.7-beta2, coming soon.

**Closed by lrineau** 2015-08-19 15:06 UTC
Labels: bug
